"""
Algorithm 1 of the source (pruning of the operator-growth graph) on the Pauli-string basis of M sites, for the Hamiltonian terms, the root string `root` (an integer code) and the threshold eps. Grow the graph layer by layer from the root by commutation with H, taking as the weight of the edge from a string O to a generated string O' the absolute value of the coefficient of O' in (1/2)[H, O]; keep a string only when its accumulated weight, defined by the source, is at least eps, and stop when a layer adds no string. Return a (2, |S|) array whose first row lists the kept codes in ascending order and whose second row gives each string's accumulated weight. Raise ValueError if root is not a code in [0, 4^M) or if eps is not positive and finite. Pauli strings are encoded as in step 1: code = sum_s f_s 4^s with f_s = 0, 1, 2, 3 for I, X, Z, Y on site s = 0..M-1, site 1 being the least significant digit s = 0.

The source selects the operators that matter for a root observable by growing the algebra generated by nested commutators as a weighted layered graph and discarding vertices whose accumulated weight falls below a threshold. The accumulated weight of a vertex is the maximum, over all paths from the root to that vertex, of the product of the edge weights along the path. The root has accumulated weight 1.

Returns
-------
ndarray of float64 with shape (2, |S|): row 0 the kept codes ascending, row 1 their accumulated weights.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def graph_pruning(terms, M, root, eps):
    """ndarray of float64 with shape (2, |S|): row 0 the kept codes ascending, row 1 their accumulated weights."""
    return np.zeros((2, 1), dtype=np.float64)

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_graph_pruning(terms, M, root, eps):
    """Algorithm 1 of the source on the Pauli basis. Edge weight of O -> O' is |c_O'|/2 where
    [H, O] = sum c_O' O' (declared convention). Accumulated weight Omega(O') is the MAXIMUM over
    paths of the product of edge weights from the root; a string is kept when Omega >= eps and
    is (re)recorded when it is new or its Omega improves. Layers are expanded until one adds
    no new string. Returns (2, |S|) array: row 0 the codes ascending, row 1 their Omega."""
    terms = np.asarray(terms, dtype=np.float64)
    M = int(M)
    D = 4 ** M
    if int(root) != root or not (0 <= root < D):
        raise ValueError("root must be a Pauli code in [0, 4^M)")
    if not (np.isfinite(eps) and eps > 0.0):
        raise ValueError("eps must be finite and positive")
    Ktab = np.zeros((4, 4), dtype=np.int64)
    ops = {0: np.eye(2), 1: np.array([[0, 1], [1, 0]]), 2: np.diag([1.0, -1.0]), 3: np.array([[0, -1j], [1j, 0]])}
    for a in range(4):
        for b in range(4):
            ph = np.trace(ops[a ^ b].conj().T @ (ops[a] @ ops[b])) / 2.0
            Ktab[a, b] = int(round(np.angle(ph) / (np.pi / 2))) % 4
    root = int(root)
    omega = {root: 1.0}
    layer = np.array([root], dtype=np.int64)
    while True:
        # coefficients of [H, O] for every O in the layer, accumulated over the terms
        acc = {}
        for code_f, coef in terms:
            T = int(code_f)
            kexp = np.zeros(layer.size, dtype=np.int64)
            anti = np.zeros(layer.size, dtype=np.int64)
            for s in range(M):
                t_s = (T >> (2 * s)) & 3
                if t_s == 0:
                    continue
                p_s = (layer >> (2 * s)) & 3
                kexp += Ktab[t_s, p_s]
                anti += ((p_s != 0) & (p_s != t_s)).astype(np.int64)
            mask = (anti % 2) == 1
            phase = 1j ** (kexp[mask] % 4)                   # [T, P] = 2 T P = 2 i^k (T xor P)
            for src, tgt, val in zip(layer[mask].tolist(), (layer[mask] ^ T).tolist(), (2.0 * coef * phase).tolist()):
                acc[(src, tgt)] = acc.get((src, tgt), 0.0) + val
        new = {}
        for (src, tgt), c in acc.items():
            if abs(c) < 1e-14:                              # contributions cancelled
                continue
            om = omega[src] * abs(c) / 2.0                   # edge weight |c_O'| / 2
            if om < eps:
                continue
            if tgt not in omega or om > omega[tgt]:
                if om > new.get(tgt, -1.0):
                    new[tgt] = om
        if not new:
            break
        omega.update(new)
        layer = np.array(sorted(new.keys()), dtype=np.int64)
    codes = np.array(sorted(omega.keys()), dtype=np.float64)
    vals = np.array([omega[int(c)] for c in codes], dtype=np.float64)
    return np.vstack([codes, vals])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {
            "setup": "terms = _oracle_doubled_terms(_oracle_lfxxz_terms(4, 1.0, 0.3, 1.0), 4)\nM = 8\nroot = 1 + 4 ** 4\neps = 0.02",
            "call": "graph_pruning(terms, M, root, eps)",
            "gold_call": "_oracle_graph_pruning(terms, M, root, eps)",
        },
        {
            "setup": "terms = _oracle_doubled_terms(_oracle_lfxxz_terms(4, 1.0, 0.3, 1.0), 4)\nM = 8\nroot = 1 + 4 ** 4\neps = 0.2",
            "call": "graph_pruning(terms, M, root, eps)",
            "gold_call": "_oracle_graph_pruning(terms, M, root, eps)",
        },
        {
            "setup": "terms = _oracle_lfxxz_terms(4, 1.0, 0.3, 1.0)\nM = 4\nroot = 2 * 4\neps = 0.05",
            "call": "graph_pruning(terms, M, root, eps)",
            "gold_call": "_oracle_graph_pruning(terms, M, root, eps)",
        },
    ]
