"""
Propagate a state vector through one time step by summing the Chebyshev series

directly onto the vector, truncating it with an adaptive stopping rule, and report

how many terms were summed.



Inputs

------

hamiltonian: (d, d) complex ndarray, may be non-Hermitian

psi: (d,) complex ndarray, the state before the step

dt: float, the time step, > 0

tol: float, term-norm stopping tolerance, > 0 (default 1e-14)

patience: int, consecutive sub-tolerance terms required to stop, >= 1 (default 5)

max_order: int, hard cap on the expansion order, >= 1 (default 4000)



Returns

-------

psi_next: (d,) complex ndarray, the propagated unnormalised state

n_terms: int, the number of Chebyshev terms summed



Raises

------

ValueError: if hamiltonian is not square, psi does not match its dimension, dt or tol is not positive, or patience or max_order is below 1

Rather than forming the propagator matrix and then applying it, the expansion is

accumulated term by term directly onto the state: each order contributes its

expansion coefficient times the corresponding Chebyshev polynomial of the Hamiltonian

applied to the vector, and the running sum is the propagated state.



The Chebyshev vectors are generated by the three-term recursion applied to the state,



    T_0(H)|psi> = |psi>,

    T_1(H)|psi> = H|psi>,

    T_{m+1}(H)|psi> = 2 H T_m(H)|psi> - T_{m-1}(H)|psi>.



Every order then costs one matrix-vector product rather than a matrix-matrix product,

which is what makes the method practical for large sparse lattice problems. The

Hamiltonian enters unmodified: it is not shifted, not divided by a spectral

half-width, and not mapped into [-1, 1] in any way.



The series is truncated adaptively rather than at a fixed order, so that steps which

converge sooner do not pay for unnecessary orders. Orders 0 and 1 seed the recursion

and are always summed. From order 2 onward each new contribution is measured in the

Euclidean norm, and the sum stops once that norm has stayed below the tolerance for a

run of consecutive orders. Requiring a run rather than a single small term matters

because the Bessel coefficients oscillate in sign and an individual term can be

accidentally small near a zero crossing while later terms are not.



The order at which the rule fires is reported alongside the propagated vector, because

it is the term count, not the vector, that enters the accumulated rounding-error

bound.

Returns
-------
tuple (psi_next, n_terms), where psi_next is a complex ndarray of shape (d,) holding the unnormalised propagated state and n_terms is the native Python int number of Chebyshev terms summed
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def chebyshev_step(
    hamiltonian: np.ndarray,
    psi: np.ndarray,
    dt: float,
    tol: float = 1e-14,
    patience: int = 5,
    max_order: int = 4000,
) -> tuple:
    '''Advance a state by one time step with an adaptively truncated Chebyshev series.

    Parameters
    ----------
    hamiltonian : np.ndarray
        Square array of shape (d, d); may be non-Hermitian.
    psi : np.ndarray
        State vector of shape (d,).
    dt : float
        Length of the time step, must be > 0.
    tol : float
        Euclidean-norm tolerance a term must fall below to count toward stopping.
    patience : int
        Number of consecutive sub-tolerance terms required before stopping.
    max_order : int
        Hard cap on the Chebyshev order, must be >= 1.

    Returns
    -------
    psi_next : np.ndarray
        Propagated, unnormalised state of shape (d,).
    n_terms : int
        Number of Chebyshev terms summed, counting orders 0 and 1.

    Raises
    ------
    ValueError
        Raised if hamiltonian is not square, psi does not match its dimension, dt or tol is not positive, or patience or max_order is below 1.
    '''
    return psi_next, n_terms

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_chebyshev_step(
    hamiltonian: np.ndarray,
    psi: np.ndarray,
    dt: float,
    tol: float = 1e-14,
    patience: int = 5,
    max_order: int = 4000,
) -> tuple:
    H = np.asarray(hamiltonian, dtype=complex)
    v = np.asarray(psi, dtype=complex).ravel()
    t = float(dt)

    if H.ndim != 2 or H.shape[0] != H.shape[1] or H.shape[0] < 1:
        raise ValueError("hamiltonian must be a square 2D array")
    if v.shape[0] != H.shape[0]:
        raise ValueError("psi length must match the hamiltonian dimension")
    if not np.isfinite(t) or t <= 0.0:
        raise ValueError("dt must be finite and > 0")
    if not np.isfinite(float(tol)) or float(tol) <= 0.0:
        raise ValueError("tol must be finite and > 0")
    if not isinstance(patience, (int, np.integer)) or int(patience) < 1:
        raise ValueError("patience must be an integer >= 1")
    if not isinstance(max_order, (int, np.integer)) or int(max_order) < 1:
        raise ValueError("max_order must be an integer >= 1")

    cap = int(max_order)

    # --- step 06: the expansion coefficients ---
    try:
        c = _oracle_chebyshev_coefficients(t, cap)
    except NameError:
        c = chebyshev_coefficients(t, cap)

    t_prev = v.copy()                      # T_0(H)|psi>
    psi_next = c[0] * t_prev
    if cap < 1:
        return psi_next, 1

    t_curr = H @ v                         # T_1(H)|psi>
    psi_next = psi_next + c[1] * t_curr

    n_terms = 2
    run = 0
    for m in range(2, cap + 1):
        t_next = 2.0 * (H @ t_curr) - t_prev
        term = c[m] * t_next
        psi_next = psi_next + term
        n_terms += 1
        if np.linalg.norm(term) < float(tol):
            run += 1
            if run >= int(patience):
                break
        else:
            run = 0
        t_prev, t_curr = t_curr, t_next

    return psi_next, int(n_terms)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Normal: one step of the task configuration (first return value) ---
        {
            "setup": """import numpy as np
n = 100
H = np.zeros((n, n), dtype=complex)
idx = np.arange(n - 1)
H[idx, idx + 1] = 0.85 * 1.35
H[idx + 1, idx] = 0.85 * 0.65
H[n - 1, 0] = 0.85 * 1.35
H[0, n - 1] = 0.85 * 0.65
site = np.arange(1, n + 1)
psi = np.exp(-((site - 50.5) ** 2) / 200.0) * np.exp(1j * (np.pi / 2) * site)
psi = psi / np.linalg.norm(psi)
dt = 3.3333333333333335
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[0]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[0]",
        },
        # --- Normal: one step of the task configuration (second return value) ---
        {
            "setup": """import numpy as np
n = 100
H = np.zeros((n, n), dtype=complex)
idx = np.arange(n - 1)
H[idx, idx + 1] = 0.85 * 1.35
H[idx + 1, idx] = 0.85 * 0.65
H[n - 1, 0] = 0.85 * 1.35
H[0, n - 1] = 0.85 * 0.65
site = np.arange(1, n + 1)
psi = np.exp(-((site - 50.5) ** 2) / 200.0) * np.exp(1j * (np.pi / 2) * site)
psi = psi / np.linalg.norm(psi)
dt = 3.3333333333333335
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[1]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[1]",
        },
        # --- Normal: a small Hermitian matrix, spectrum inside [-1, 1] (first return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.0, 0.3, 0.0],
              [0.3, 0.0, 0.3],
              [0.0, 0.3, 0.0]], dtype=complex)
psi = np.array([1.0, 0.0, 0.0], dtype=complex)
dt = 1.0
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[0]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[0]",
        },
        # --- Normal: a small Hermitian matrix, spectrum inside [-1, 1] (second return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.0, 0.3, 0.0],
              [0.3, 0.0, 0.3],
              [0.0, 0.3, 0.0]], dtype=complex)
psi = np.array([1.0, 0.0, 0.0], dtype=complex)
dt = 1.0
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[1]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[1]",
        },
        # --- Boundary: patience of 1 stops at the first sub-tolerance term (first return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.0, 1.2],
              [0.4, 0.0]], dtype=complex)
psi = np.array([0.6, 0.8], dtype=complex)
dt = 2.0
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 1, 4000)[0]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 1, 4000)[0]",
        },
        # --- Boundary: patience of 1 stops at the first sub-tolerance term (second return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.0, 1.2],
              [0.4, 0.0]], dtype=complex)
psi = np.array([0.6, 0.8], dtype=complex)
dt = 2.0
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 1, 4000)[1]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 1, 4000)[1]",
        },
        # --- Edge: max_order caps the expansion before the rule can fire (first return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.0, 2.0],
              [0.5, 0.0]], dtype=complex)
psi = np.array([1.0, 0.0], dtype=complex)
dt = 6.0
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4)[0]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4)[0]",
        },
        # --- Edge: max_order caps the expansion before the rule can fire (second return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.0, 2.0],
              [0.5, 0.0]], dtype=complex)
psi = np.array([1.0, 0.0], dtype=complex)
dt = 6.0
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4)[1]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4)[1]",
        },
        # --- Edge: 1x1 matrix reduces to the scalar exponential (first return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.4 + 0.2j]], dtype=complex)
psi = np.array([1.0 + 0.0j], dtype=complex)
dt = 0.5
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[0]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[0]",
        },
        # --- Edge: 1x1 matrix reduces to the scalar exponential (second return value) ---
        {
            "setup": """import numpy as np
H = np.array([[0.4 + 0.2j]], dtype=complex)
psi = np.array([1.0 + 0.0j], dtype=complex)
dt = 0.5
""",
            "call": "chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[1]",
            "gold_call": "_oracle_chebyshev_step(H, psi, dt, 1e-14, 5, 4000)[1]",
        },
        # --- Invalid: state length does not match the matrix ---
        {
            "setup": """import numpy as np
H = np.eye(3, dtype=complex)
psi = np.ones(2, dtype=complex)
def run_model():
    _fn = chebyshev_step
    try:
        _fn(H, psi, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_oracle():
    _fn = _oracle_chebyshev_step
    try:
        _fn(H, psi, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_oracle()",
        },
        # --- Invalid: non-square Hamiltonian ---
        {
            "setup": """import numpy as np
H = np.zeros((2, 3), dtype=complex)
psi = np.ones(3, dtype=complex)
def run_model():
    _fn = chebyshev_step
    try:
        _fn(H, psi, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_oracle():
    _fn = _oracle_chebyshev_step
    try:
        _fn(H, psi, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_oracle()",
        },
        # --- Invalid: patience below 1 ---
        {
            "setup": """import numpy as np
H = np.eye(2, dtype=complex)
psi = np.ones(2, dtype=complex)
def run_model():
    _fn = chebyshev_step
    try:
        _fn(H, psi, 1.0, 1e-14, 0, 4000)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_oracle():
    _fn = _oracle_chebyshev_step
    try:
        _fn(H, psi, 1.0, 1e-14, 0, 4000)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_oracle()",
        },
    ]
