"""
Evaluate the effective parameters the same modulation produces in the limit of infinitely many cells inside a branch of fixed length.

It is worth asking what survives when the cells become so short that the branch contains arbitrarily many of them. In that limit the exact potential distribution and the equivalent exponential profile coincide, the boundary layers attached to the terminals shrink to nothing, and the effective parameters become properties of the cell alone: they no longer depend on the number of cells, on the branch length, or on where the terminals sit. The result is a closed pair of expressions built from the Fourier coefficients of the two profiles, with all the boundary machinery gone.




Both expressions share a single algebraic object, the inverse of the matrix that pairs two nonzero harmonics through the conductivity coefficient of their index difference, weighted by the product of the two indices. The zeroth harmonic is deliberately excluded, which is what makes the construction a Schur complement of the full Toeplitz matrix of the conductivity taken about its zeroth entry. That structure supplies both a check and a warning. The check is that the effective conductivity must reduce to the harmonic mean of the profile - the series average of a layered conductor, the classical static result, which must survive the modulation because the modulation cannot help a purely conductive path. The warning is that the two indices enter the matrix and the two contracted vectors asymmetrically, so exchanging the roles of the row index and the column index silently produces a different number that still looks plausible, and only the harmonic-mean check catches it. The advective coefficient has an equally instructive closed form once the same structure is unwound: the modulation speed times the difference between the cell average of the capacity and the product of the effective conductivity with the cell average of the capacity divided by the conductivity. If the capacity is uniform the two terms cancel and no drift appears however strongly the conductivity is modulated, so the drift is generated by the correlation between the two modulations and the relative phase controls both its size and its sign. The truncated version also converges more slowly than the potential profile does, because the reciprocal of a strongly modulated conductivity has slowly decaying harmonics of its own.

Returns
-------
np.ndarray: real array of shape (3) holding the many-cell effective conductivity, the many-cell effective advective coefficient and their ratio.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def compute_homogenized_limit(sigma_modes: "np.ndarray",
                              capacity_modes: "np.ndarray",
                              modulation_speed: float) -> "np.ndarray":
    """Evaluate the effective parameters in the many-cell limit.

    Parameters
    ----------
    sigma_modes : np.ndarray
        Complex conductivity coefficients of shape (2 * order + 1), indexed
        from harmonic -order to +order. The profile carries no harmonics
        beyond that range, so any coefficient whose harmonic index falls
        outside it is zero.
    capacity_modes : np.ndarray
        Complex capacity coefficients with the same shape and ordering, under
        the same convention.
    modulation_speed : float
        Speed of the travelling modulation in metres per second.

    Returns
    -------
    parameters : np.ndarray
        Real array of shape (3) holding the limiting effective conductivity,
        the limiting effective advective coefficient and their ratio, in that
        order.

    Raises
    ------
    ValueError
        If sigma_modes is not a one-dimensional array of odd length >= 3, if
        capacity_modes does not have the same shape as sigma_modes, if any
        coefficient is not finite, if modulation_speed is not a finite number,
        if the index-weighted conductivity coupling restricted to the nonzero
        harmonics is singular, or if the limiting effective conductivity does
        not come out positive.
    """
    return parameters  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_compute_homogenized_limit(sigma_modes: "np.ndarray",
                                      capacity_modes: "np.ndarray",
                                      modulation_speed: float) -> "np.ndarray":
    # Local imports keep the oracle self-contained when the harness
    # executes it in isolation.
    import numpy as np

    sigma = np.asarray(sigma_modes, dtype=complex)
    capacity = np.asarray(capacity_modes, dtype=complex)
    if sigma.ndim != 1 or sigma.size < 3 or sigma.size % 2 == 0:
        raise ValueError("sigma_modes must be a 1D array of odd length >= 3")
    if capacity.shape != sigma.shape:
        raise ValueError("capacity_modes must have the same shape as sigma_modes")
    if not (np.all(np.isfinite(sigma)) and np.all(np.isfinite(capacity))):
        raise ValueError("sigma_modes and capacity_modes must be finite")
    if not (isinstance(modulation_speed, (int, float, np.floating, np.integer))
            and np.isfinite(modulation_speed)):
        raise ValueError("modulation_speed must be a finite number")

    order = (sigma.size - 1) // 2
    nonzero = np.array([n for n in range(-order, order + 1) if n != 0])
    rows = nonzero[:, None]
    cols = nonzero[None, :]
    difference = rows - cols
    inside = np.abs(difference) <= order
    picker = np.where(inside, sigma[np.clip(difference + order, 0, 2 * order)], 0.0)
    # Row index is the projected harmonic, column index the summed harmonic.
    coupling = rows * cols * picker
    try:
        inverse = np.linalg.inv(coupling)
    except np.linalg.LinAlgError as exc:
        raise ValueError("the reduced conductivity coupling must be invertible") from exc

    left = nonzero * sigma[order - nonzero]
    right_sigma = nonzero * sigma[order + nonzero]
    right_capacity = nonzero * capacity[order + nonzero]
    conductivity = float(np.real(sigma[order] - left @ inverse @ right_sigma))
    advective = float(np.real(float(modulation_speed) * (left @ inverse @ right_capacity)))
    if conductivity <= 0.0:
        raise ValueError("the limiting effective conductivity must be positive")
    return np.array([conductivity, advective, advective / conductivity], dtype=float)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: benchmark modulation at the truncation used for the answer ---
        {
            "setup": """import numpy as np
order = 16
sigma_modes = np.zeros(2 * order + 1, dtype=complex)
capacity_modes = np.zeros(2 * order + 1, dtype=complex)
sigma_modes[order] = 1.0
sigma_modes[order + 1] = sigma_modes[order - 1] = 0.35
sigma_modes[order + 2] = 0.1 * np.exp(1j * np.pi / 3.0)
sigma_modes[order - 2] = 0.1 * np.exp(-1j * np.pi / 3.0)
capacity_modes[order] = 100.0
capacity_modes[order + 1] = 25.0 * np.exp(1j * 0.4 * np.pi)
capacity_modes[order - 1] = 25.0 * np.exp(-1j * 0.4 * np.pi)
modulation_speed = 0.06

def digest(values):
    grid = np.asarray(values, dtype=complex)
    flat = 1.0e6 * grid.reshape(-1)
    rank = np.arange(1.0, flat.size + 1.0)
    weight = rank / rank.sum()
    root = np.sqrt(rank) / np.sqrt(rank).sum()
    return float(flat.size + 3.0 * grid.shape[0]
                 + np.sqrt(np.sum(weight * np.abs(flat) ** 2))
                 + 0.5 * np.sum(weight * flat.real) + 0.25 * np.sum(root * flat.imag))
""",
            "call": "digest(compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
            "gold_call": "digest(_oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
        },
        # --- Valid: the same modulation with the travelling wave reversed ---
        {
            "setup": """import numpy as np
order = 8
sigma_modes = np.zeros(2 * order + 1, dtype=complex)
capacity_modes = np.zeros(2 * order + 1, dtype=complex)
sigma_modes[order] = 1.0
sigma_modes[order + 1] = sigma_modes[order - 1] = 0.35
sigma_modes[order + 2] = 0.1 * np.exp(1j * np.pi / 3.0)
sigma_modes[order - 2] = 0.1 * np.exp(-1j * np.pi / 3.0)
capacity_modes[order] = 100.0
capacity_modes[order + 1] = 25.0 * np.exp(1j * 0.4 * np.pi)
capacity_modes[order - 1] = 25.0 * np.exp(-1j * 0.4 * np.pi)
modulation_speed = -0.06

def digest(values):
    grid = np.asarray(values, dtype=complex)
    flat = 1.0e6 * grid.reshape(-1)
    rank = np.arange(1.0, flat.size + 1.0)
    weight = rank / rank.sum()
    root = np.sqrt(rank) / np.sqrt(rank).sum()
    return float(flat.size + 3.0 * grid.shape[0]
                 + np.sqrt(np.sum(weight * np.abs(flat) ** 2))
                 + 0.5 * np.sum(weight * flat.real) + 0.25 * np.sum(root * flat.imag))
""",
            "call": "digest(compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
            "gold_call": "digest(_oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
        },
        # --- Boundary: uniform capacity, where no effective drift can appear ---
        {
            "setup": """import numpy as np
order = 6
sigma_modes = np.zeros(2 * order + 1, dtype=complex)
capacity_modes = np.zeros(2 * order + 1, dtype=complex)
sigma_modes[order] = 1.0
sigma_modes[order + 1] = sigma_modes[order - 1] = 0.4
capacity_modes[order] = 100.0
modulation_speed = 0.25

def digest(values):
    grid = np.asarray(values, dtype=complex)
    flat = 1.0e6 * grid.reshape(-1)
    rank = np.arange(1.0, flat.size + 1.0)
    weight = rank / rank.sum()
    root = np.sqrt(rank) / np.sqrt(rank).sum()
    return float(flat.size + 3.0 * grid.shape[0]
                 + np.sqrt(np.sum(weight * np.abs(flat) ** 2))
                 + 0.5 * np.sum(weight * flat.real) + 0.25 * np.sum(root * flat.imag))
""",
            "call": "digest(compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
            "gold_call": "digest(_oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
        },
        # --- Boundary: uniform conductivity, whose harmonic mean is its own value ---
        {
            "setup": """import numpy as np
order = 4
sigma_modes = np.zeros(2 * order + 1, dtype=complex)
capacity_modes = np.zeros(2 * order + 1, dtype=complex)
sigma_modes[order] = 2.0
capacity_modes[order] = 80.0
capacity_modes[order + 1] = 20.0 * np.exp(1j * 0.7)
capacity_modes[order - 1] = 20.0 * np.exp(-1j * 0.7)
modulation_speed = 0.1

def digest(values):
    grid = np.asarray(values, dtype=complex)
    flat = 1.0e6 * grid.reshape(-1)
    rank = np.arange(1.0, flat.size + 1.0)
    weight = rank / rank.sum()
    root = np.sqrt(rank) / np.sqrt(rank).sum()
    return float(flat.size + 3.0 * grid.shape[0]
                 + np.sqrt(np.sum(weight * np.abs(flat) ** 2))
                 + 0.5 * np.sum(weight * flat.real) + 0.25 * np.sum(root * flat.imag))
""",
            "call": "digest(compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
            "gold_call": "digest(_oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
        },
        # --- Edge: smallest truncation with a strongly modulated pair ---
        {
            "setup": """import numpy as np
sigma_modes = np.array([0.45, 1.0, 0.45], dtype=complex)
capacity_modes = np.array([30.0 * np.exp(-1.9j), 60.0, 30.0 * np.exp(1.9j)], dtype=complex)
modulation_speed = 0.8

def digest(values):
    grid = np.asarray(values, dtype=complex)
    flat = 1.0e6 * grid.reshape(-1)
    rank = np.arange(1.0, flat.size + 1.0)
    weight = rank / rank.sum()
    root = np.sqrt(rank) / np.sqrt(rank).sum()
    return float(flat.size + 3.0 * grid.shape[0]
                 + np.sqrt(np.sum(weight * np.abs(flat) ** 2))
                 + 0.5 * np.sum(weight * flat.real) + 0.25 * np.sum(root * flat.imag))
""",
            "call": "digest(compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
            "gold_call": "digest(_oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed))",
        },
        # --- Invalid: mismatched coefficient arrays ---
        {
            "setup": """import numpy as np
sigma_modes = np.array([0.3, 1.0, 0.3], dtype=complex)
capacity_modes = np.array([1.0, 20.0, 1.0, 2.0, 2.0], dtype=complex)
modulation_speed = 0.1
def run_model():
    try:
        compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: even-length coefficient array has no zeroth harmonic ---
        {
            "setup": """import numpy as np
sigma_modes = np.ones(8, dtype=complex)
capacity_modes = np.ones(8, dtype=complex)
modulation_speed = 0.1
def run_model():
    try:
        compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_homogenized_limit(sigma_modes, capacity_modes, modulation_speed)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
