"""
Implement extract_effective_field which converts the rotation of a periodic pulse element into the constant field that generates it.

A pulse sequence element that is repeated many times acts, to leading order, like a constant
field applied for the whole modulation period. That field is what a second spin has to be matched
against for polarization transfer, so its Cartesian components, and in particular how little they
scatter across crystallites and resonance offsets, are the figure of merit that distinguishes a
robust element from a fragile one.

Reading the field off the element is the inverse of building a rotation from a constant field:
the scalar part of the sequence quaternion fixes the rotation angle accumulated over the whole
modulation period, and the vector part fixes the direction. Dividing the angle by the modulation
period turns the rotation into a frequency, and the branch is chosen so that the returned
magnitude lies between zero and one full turn per modulation period.

Returns
-------
np.ndarray, real array of shape leading_shape + (3,) holding the Cartesian components of the effective field in rad/s
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def extract_effective_field(q_total: "np.ndarray", tau_m: float) -> "np.ndarray":
    '''Extract the constant effective field generated by a periodic pulse element.

    The quaternion uses the same scalar-first convention as the interval
    quaternions, so the rotation angle is recovered from the scalar part and
    the norm of the vector part, and the rotation axis is recovered from the
    vector part. The magnitude is taken in the branch [0, 2*pi/tau_m], and an
    identity quaternion returns a vanishing field.

    Parameters
    ----------
    q_total : np.ndarray
        Real array of shape leading_shape + (4,) holding scalar-first
        quaternions of complete pulse sequence elements.
    tau_m : float
        Modulation period of the element in seconds. Must be positive and
        finite.

    Returns
    -------
    effective_field : np.ndarray
        Real array of shape leading_shape + (3,) holding the Cartesian
        components of the effective field in rad/s.

    Raises
    ------
    ValueError
        If tau_m is not positive and finite, if the trailing axis of q_total
        does not have length 4, or if q_total contains values that are not
        finite.
    '''
    return effective_field  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_extract_effective_field(q_total: "np.ndarray", tau_m: float) -> "np.ndarray":
    tau_m = float(tau_m)
    if not np.isfinite(tau_m) or tau_m <= 0.0:
        raise ValueError("tau_m must be positive and finite")
    q_total = np.asarray(q_total, dtype=float)
    if q_total.ndim < 1 or q_total.shape[-1] != 4:
        raise ValueError("q_total must have a trailing axis of length 4")
    if not np.all(np.isfinite(q_total)):
        raise ValueError("q_total must be finite")

    scalar = q_total[..., 0]
    vector = q_total[..., 1:]
    norm = np.sqrt(np.sum(vector ** 2, axis=-1))
    magnitude = 2.0 * np.arctan2(norm, scalar) / tau_m
    safe = np.where(norm == 0.0, 1.0, norm)
    axis = -vector / safe[..., None]
    return magnitude[..., None] * axis

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    common = "import numpy as np\ntau_m = 80.0e-6\n"
    element = (common
               + "beta_rl = float(np.arccos(1.0 / np.sqrt(3.0)))\n"
               + "amps = 2.0 * np.pi * np.array([99882.6002, 97593.2747, 99938.7784, 99788.5816, 98277.6433, 99577.6807, 98881.0528, 94404.7994])\n"
               + "phs = np.deg2rad(np.array([308.58, 91.90, 322.74, 235.95, 158.68, 107.58, 55.28, 30.57]))\n"
               + "comp = _oracle_compute_shielding_fourier_components(0.0, 2.0 * np.pi * 80.0e3, 0.5, 0.3, 0.9, 1.7, beta_rl)\n"
               + "off = _oracle_compute_offset_trajectory(comp, 2.0 * np.pi * 25.0e3, np.arange(1, 9) * 2.0e-6)\n"
               + "qtot = _oracle_compose_quaternion_sequence(_oracle_build_interval_quaternion(amps, phs, off, 2.0e-6))\n")
    return [
        # Normal: the effective field of a real irradiated element under a
        # rotor-modulated shielding.
        {
            "setup": element,
            "call": "[round(float(v) / (2.0 * np.pi), 6) for v in extract_effective_field(qtot, 16.0e-6)]",
            "gold_call": "[round(float(v) / (2.0 * np.pi), 6) for v in _oracle_extract_effective_field(qtot, 16.0e-6)]",
        },
        # Boundary: an element that returns the spin to its starting state
        # generates no effective field.
        {
            "setup": common,
            "call": "[round(float(v), 12) for v in extract_effective_field(np.array([1.0, 0.0, 0.0, 0.0]), tau_m)]",
            "gold_call": "[round(float(v), 12) for v in _oracle_extract_effective_field(np.array([1.0, 0.0, 0.0, 0.0]), tau_m)]",
        },
        # Edge: the optimization target itself, a third of a turn about x over
        # the modulation period.
        {
            "setup": common + "qt = np.array([np.cos(np.pi / 3.0), -np.sin(np.pi / 3.0), 0.0, 0.0])\n",
            "call": "[round(float(v) / (2.0 * np.pi), 6) for v in extract_effective_field(qt, tau_m)]",
            "gold_call": "[round(float(v) / (2.0 * np.pi), 6) for v in _oracle_extract_effective_field(qt, tau_m)]",
        },
        # Edge: a pure longitudinal rotation returns a field along the field
        # axis alone.
        {
            "setup": common + "qz = np.array([np.cos(0.4), 0.0, 0.0, -np.sin(0.4)])\n",
            "call": "[round(float(v) / (2.0 * np.pi), 6) for v in extract_effective_field(qz, tau_m)]",
            "gold_call": "[round(float(v) / (2.0 * np.pi), 6) for v in _oracle_extract_effective_field(qz, tau_m)]",
        },
        # Edge: a rotation beyond half a turn, where the scalar part is negative
        # and the branch choice decides the reported magnitude.
        {
            "setup": common + "qb = np.array([np.cos(2.3), -np.sin(2.3) * 0.6, -np.sin(2.3) * 0.0, -np.sin(2.3) * 0.8])\n",
            "call": "[round(float(v) / (2.0 * np.pi), 6) for v in extract_effective_field(qb, tau_m)]",
            "gold_call": "[round(float(v) / (2.0 * np.pi), 6) for v in _oracle_extract_effective_field(qb, tau_m)]",
        },
        # Edge: building a rotation from a constant field and reading it back
        # must return the same field.
        {
            "setup": common + "q_rt = _oracle_build_interval_quaternion(2.0 * np.pi * 3.0e3, 0.0, 2.0 * np.pi * 1.5e3, tau_m)\n",
            "call": "[round(float(v) / (2.0 * np.pi), 6) for v in extract_effective_field(q_rt, tau_m)]",
            "gold_call": "[round(float(v) / (2.0 * np.pi), 6) for v in _oracle_extract_effective_field(q_rt, tau_m)]",
        },
        # Normal: a batch of quaternions, which pins the shape handling used when
        # averaging the field over crystallites.
        {
            "setup": common + "ang = np.array([0.1, 1.0, 2.0, 3.0])\naxes = np.array([[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.6, 0.8, 0.0], [0.0, 0.6, -0.8]])\nqs = np.concatenate([np.cos(ang)[:, None], -np.sin(ang)[:, None] * axes], axis=1)\n",
            "call": "[round(float(v) / (2.0 * np.pi), 6) for v in extract_effective_field(qs, tau_m).ravel()]",
            "gold_call": "[round(float(v) / (2.0 * np.pi), 6) for v in _oracle_extract_effective_field(qs, tau_m).ravel()]",
        },
        # Invalid input must raise ValueError rather than return a field.
        {
            "setup": "\n\nimport numpy as np\ndef _exception_code(function, *args, **kwargs):\n    try:\n        function(*args, **kwargs)\n        return 0\n    except ValueError:\n        return 1\n    except Exception:\n        return 2\n",
            "call": "_exception_code(extract_effective_field, np.array([1.0, 0.0, 0.0, 0.0]), 0.0)",
            "gold_call": "_exception_code(_oracle_extract_effective_field, np.array([1.0, 0.0, 0.0, 0.0]), 0.0)",
        },
    ]
