"""
Implement compute_fidelity_and_gradient which scores a pulse element against a target rotation and returns the exact derivatives of that score.

Designing an irradiation element that produces the same rotation for every crystallite and every
resonance offset is an optimization over the piecewise-constant amplitudes and phases. The score
is how closely the rotation generated by the element matches a chosen target rotation, averaged
over the orientations present in a powder and over the offsets the element must tolerate.

Because the element quaternion is an ordered product of interval quaternions, the derivative with
respect to one interval parameter replaces that single factor by its own derivative and leaves
the rest of the product untouched. Storing the partial products accumulated from both ends of the
sequence therefore yields every derivative at a cost comparable to one evaluation of the score,
which is what makes gradient-based refinement of a long element practical.

The shielding of each crystallite is rotor modulated, so each crystallite and offset pair defines
its own sequence of interval offsets and its own element quaternion.

Returns
-------
np.ndarray, real array of shape (2*n_steps + 1,) holding the score followed by the amplitude-derivative block and then the phase-derivative block
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def compute_fidelity_and_gradient(amplitudes: "np.ndarray", phases: "np.ndarray", dt: float,
                                  offsets: "np.ndarray", crystallites: "np.ndarray",
                                  omega_aniso: float, eta: float, beta_rl: float,
                                  omega_r: float, q_target: "np.ndarray") -> "np.ndarray":
    '''Score a pulse element against a target rotation and differentiate the score.

    The score is the weighted mean, over crystallites and over resonance
    offsets, of the Euclidean inner product between q_target and the
    scalar-first quaternion of the whole element. Crystallites carry the
    weights supplied in the grid, and the offsets are weighted equally.

    Parameters
    ----------
    amplitudes : np.ndarray
        Real array of shape (n_steps,) holding the radio-frequency amplitude
        of each interval in rad/s. n_steps must be at least 1.
    phases : np.ndarray
        Real array of shape (n_steps,) holding the radio-frequency phase of
        each interval in radians.
    dt : float
        Duration of one interval in seconds. Must be positive and finite. The
        rotor-modulated shielding of interval j is sampled at the end of that
        interval, at time (j + 1) * dt with j counted from zero.
    offsets : np.ndarray
        Real array of shape (n_offsets,) holding the isotropic resonance
        offsets in rad/s over which the score is averaged. n_offsets must be
        at least 1.
    crystallites : np.ndarray
        Real array of shape (n_crystallites, 4) whose columns are the three
        Euler angles in radians carrying the shielding principal axis frame
        into the rotor frame, and the crystallite weight.
    omega_aniso : float
        Anisotropic shielding frequency in rad/s.
    eta : float
        Shielding asymmetry parameter, 0 <= eta <= 1.
    beta_rl : float
        Angle in radians between the rotor axis and the static field.
    omega_r : float
        Sample spinning frequency in rad/s.
    q_target : np.ndarray
        Real array of shape (4,) holding the scalar-first target quaternion.

    Returns
    -------
    result : np.ndarray
        Real array of shape (2*n_steps + 1,). Element 0 is the score. Elements
        1 to n_steps are the derivatives of the score with respect to the
        interval amplitudes, in rad/s units of amplitude. Elements n_steps + 1
        to 2*n_steps are the derivatives with respect to the interval phases.

    Raises
    ------
    ValueError
        If amplitudes and phases are not one-dimensional arrays of the same
        positive length, if dt is not positive and finite, if offsets is not
        a non-empty one-dimensional array, if crystallites is not an array of
        shape (n_crystallites, 4) with at least one row, if q_target does not
        have shape (4,), or if eta lies outside [0, 1].
    '''
    return result  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_compute_fidelity_and_gradient(amplitudes: "np.ndarray", phases: "np.ndarray", dt: float,
                                          offsets: "np.ndarray", crystallites: "np.ndarray",
                                          omega_aniso: float, eta: float, beta_rl: float,
                                          omega_r: float, q_target: "np.ndarray") -> "np.ndarray":
    amplitudes = np.asarray(amplitudes, dtype=float)
    phases = np.asarray(phases, dtype=float)
    offsets = np.asarray(offsets, dtype=float)
    crystallites = np.asarray(crystallites, dtype=float)
    q_target = np.asarray(q_target, dtype=float)

    if amplitudes.ndim != 1 or phases.ndim != 1 or amplitudes.shape != phases.shape:
        raise ValueError("amplitudes and phases must be one-dimensional arrays of equal length")
    if amplitudes.size < 1:
        raise ValueError("amplitudes must hold at least one interval")
    dt = float(dt)
    if not np.isfinite(dt) or dt <= 0.0:
        raise ValueError("dt must be positive and finite")
    if offsets.ndim != 1 or offsets.size < 1:
        raise ValueError("offsets must be a non-empty one-dimensional array")
    if crystallites.ndim != 2 or crystallites.shape[1] != 4 or crystallites.shape[0] < 1:
        raise ValueError("crystallites must have shape (n_crystallites, 4)")
    if q_target.shape != (4,):
        raise ValueError("q_target must have shape (4,)")
    if not (0.0 <= float(eta) <= 1.0):
        raise ValueError("eta must satisfy 0 <= eta <= 1")

    n_steps = amplitudes.size
    n_offsets = offsets.size
    times = np.arange(1, n_steps + 1) * dt

    components = np.array([
        _oracle_compute_shielding_fourier_components(0.0, omega_aniso, eta,
                                                     row[0], row[1], row[2], beta_rl)
        for row in crystallites])
    base = _oracle_compute_offset_trajectory(components, omega_r, times)
    # One row per crystallite and offset pair, each holding the interval offsets.
    delta = (base[:, None, :] + offsets[None, :, None]).reshape(-1, n_steps)
    weights = np.repeat(crystallites[:, 3], n_offsets) / n_offsets

    quaternions = _oracle_build_interval_quaternion(amplitudes[None, :], phases[None, :],
                                                    delta, dt)

    identity = np.zeros((delta.shape[0], 4))
    identity[:, 0] = 1.0
    prefix = [identity]
    for index in range(n_steps):
        prefix.append(_quaternion_multiply(quaternions[:, index, :], prefix[-1]))
    suffix = [None] * (n_steps + 1)
    suffix[n_steps] = identity
    for index in range(n_steps - 1, -1, -1):
        suffix[index] = _quaternion_multiply(suffix[index + 1], quaternions[:, index, :])

    fidelity = float(weights @ (prefix[n_steps] @ q_target))

    magnitude = np.sqrt(amplitudes[None, :] ** 2 + delta ** 2)
    safe = np.where(magnitude == 0.0, 1.0, magnitude)
    half_angle = magnitude * dt / 2.0
    sine = np.sin(half_angle)
    cosine = np.cos(half_angle)
    cos_phi = np.cos(phases)[None, :]
    sin_phi = np.sin(phases)[None, :]

    transverse = (delta ** 2 / safe ** 3 * sine
                  + amplitudes[None, :] ** 2 * dt / (2.0 * safe ** 2) * cosine)
    longitudinal = delta * (amplitudes[None, :] / safe ** 3 * sine
                            - amplitudes[None, :] * dt / (2.0 * safe ** 2) * cosine)
    d_amplitude = np.stack([-dt / 2.0 * amplitudes[None, :] / safe * sine,
                            -transverse * cos_phi,
                            -transverse * sin_phi,
                            longitudinal], axis=-1)
    # Limit of a vanishing rotation, where the axis direction is set by the phase alone.
    degenerate = (magnitude == 0.0)
    if np.any(degenerate):
        limit = np.stack([np.zeros_like(sine), -dt / 2.0 * np.broadcast_to(cos_phi, sine.shape),
                          -dt / 2.0 * np.broadcast_to(sin_phi, sine.shape),
                          np.zeros_like(sine)], axis=-1)
        d_amplitude = np.where(degenerate[..., None], limit, d_amplitude)

    ratio = sine * amplitudes[None, :] / safe
    d_phase = np.stack([np.zeros_like(ratio), ratio * sin_phi,
                        -ratio * cos_phi, np.zeros_like(ratio)], axis=-1)

    gradient_amplitude = np.empty(n_steps)
    gradient_phase = np.empty(n_steps)
    for index in range(n_steps):
        left = suffix[index + 1]
        chain_a = _quaternion_multiply(left, _quaternion_multiply(d_amplitude[:, index, :],
                                                                  prefix[index]))
        chain_p = _quaternion_multiply(left, _quaternion_multiply(d_phase[:, index, :],
                                                                  prefix[index]))
        gradient_amplitude[index] = weights @ (chain_a @ q_target)
        gradient_phase[index] = weights @ (chain_p @ q_target)

    return np.concatenate([[fidelity], gradient_amplitude, gradient_phase])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    shape = ("import numpy as np\n"
             "beta_rl = float(np.arccos(1.0 / np.sqrt(3.0)))\n"
             "amps = 2.0 * np.pi * np.array([99882.6002, 97593.2747, 99938.7784, 99788.5816, 98277.6433, 99577.6807, 98881.0528, 94404.7994, 99306.0922, 99774.6973])\n"
             "phs = np.deg2rad(np.array([308.58, 91.90, 322.74, 235.95, 158.68, 107.58, 55.28, 30.57, 8.96, 6.07]))\n"
             "qt = np.array([np.cos(np.pi / 3.0), -np.sin(np.pi / 3.0), 0.0, 0.0])\n"
             "omega_r = 2.0 * np.pi * 25.0e3\n")
    return [
        # Normal: the graded shielding and target on a small but genuine powder,
        # scored over a symmetric offset band.
        {
            "setup": shape + "cr = _oracle_build_powder_grid(3, 3, 2)\noff = 2.0 * np.pi * np.linspace(-35.0e3, 35.0e3, 3)\n",
            "call": "[round(float(v), 10) for v in compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt)]",
            "gold_call": "[round(float(v), 10) for v in _oracle_compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt)]",
        },
        # Boundary: with no anisotropy every crystallite sees the same offset, so
        # the score collapses to a pure offset average.
        {
            "setup": shape + "cr = _oracle_build_powder_grid(3, 3, 2)\noff = 2.0 * np.pi * np.linspace(-35.0e3, 35.0e3, 3)\n",
            "call": "[round(float(v), 10) for v in compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 0.0, 0.5, beta_rl, omega_r, qt)]",
            "gold_call": "[round(float(v), 10) for v in _oracle_compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 0.0, 0.5, beta_rl, omega_r, qt)]",
        },
        # Boundary: a single crystallite at a single offset removes all averaging
        # and exposes the bare sequence quaternion overlap.
        {
            "setup": shape + "cr = np.array([[0.3, 0.9, 1.7, 1.0]])\noff = np.array([0.0])\n",
            "call": "[round(float(v), 10) for v in compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt)]",
            "gold_call": "[round(float(v), 10) for v in _oracle_compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt)]",
        },
        # Edge: the maximum shielding asymmetry, which changes every crystallite
        # trajectory and therefore every derivative.
        {
            "setup": shape + "cr = _oracle_build_powder_grid(4, 2, 2)\noff = 2.0 * np.pi * np.array([-20.0e3, 0.0, 20.0e3])\n",
            "call": "[round(float(v), 10) for v in compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 120.0e3, 1.0, beta_rl, omega_r, qt)]",
            "gold_call": "[round(float(v), 10) for v in _oracle_compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 120.0e3, 1.0, beta_rl, omega_r, qt)]",
        },
        # Edge: the score is an average of inner products of unit quaternions, so
        # it can never leave the interval from minus one to one.
        {
            "setup": shape + "cr = _oracle_build_powder_grid(4, 4, 3)\noff = 2.0 * np.pi * np.linspace(-1.0e5, 1.0e5, 5)\n",
            "call": "(lambda r: [round(float(r[0]), 10), float(abs(r[0]) <= 1.0)])(compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt))",
            "gold_call": "(lambda r: [round(float(r[0]), 10), float(abs(r[0]) <= 1.0)])(_oracle_compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt))",
        },
        # Edge: intervals with no irradiation carry no phase, so every phase
        # derivative must vanish while the amplitude derivatives do not.
        {
            "setup": shape + "cr = np.array([[0.2, 1.1, 0.4, 0.5], [2.0, 2.0, 3.0, 0.5]])\noff = 2.0 * np.pi * np.array([-10.0e3, 10.0e3])\nzeros = np.zeros(10)\n",
            "call": "[round(float(v), 12) for v in compute_fidelity_and_gradient(zeros, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt)]",
            "gold_call": "[round(float(v), 12) for v in _oracle_compute_fidelity_and_gradient(zeros, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, omega_r, qt)]",
        },
        # Edge: a static sample, where the shielding no longer averages and the
        # element has to cope with a fixed anisotropic shift.
        {
            "setup": shape + "cr = _oracle_build_powder_grid(3, 2, 1)\noff = 2.0 * np.pi * np.array([0.0, 30.0e3])\n",
            "call": "[round(float(v), 10) for v in compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, 0.0, qt)]",
            "gold_call": "[round(float(v), 10) for v in _oracle_compute_fidelity_and_gradient(amps, phs, 2.0e-6, off, cr, 2.0 * np.pi * 80.0e3, 0.5, beta_rl, 0.0, qt)]",
        },
        # Invalid input must raise ValueError rather than return a score.
        {
            "setup": "\n\nimport numpy as np\ndef _exception_code(function, *args, **kwargs):\n    try:\n        function(*args, **kwargs)\n        return 0\n    except ValueError:\n        return 1\n    except Exception:\n        return 2\n",
            "call": "_exception_code(compute_fidelity_and_gradient, np.ones(4), np.zeros(4), 2.0e-6, np.zeros(1), np.array([[0.0, 0.0, 0.0, 1.0]]), 1.0, 0.5, 0.9553166181245093, 1.0, np.zeros(3))",
            "gold_call": "_exception_code(_oracle_compute_fidelity_and_gradient, np.ones(4), np.zeros(4), 2.0e-6, np.zeros(1), np.array([[0.0, 0.0, 0.0, 1.0]]), 1.0, 0.5, 0.9553166181245093, 1.0, np.zeros(3))",
        },
    ]
