"""
Principal logarithmic Mueller generators.

A homogeneous medium is generated by its path-integrated differential matrix,
so the real principal matrix logarithm of an intensity-normalized Mueller
matrix recovers that generator. All sixteen entries participate.

Returns
-------
A finite real (n,4,4) array of logarithmic generators.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def principal_mueller_logarithms(normalized_stack: np.ndarray, imag_tol: float = 1e-8) -> np.ndarray:
    """Return the real principal matrix logarithm of every normalized matrix.

    normalized_stack must be a finite real array of shape (n,4,4) with n>=1
    whose [0,0] entries each lie within 1e-8 of one. imag_tol must be a
    finite positive real number and not a Boolean. Take the principal
    logarithm of each complete 4x4 matrix. Raise ValueError for any contract
    violation or when any imaginary component of a logarithm has magnitude
    above imag_tol. Return the real parts with shape (n,4,4).
    """
    return result

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np

def _oracle_principal_mueller_logarithms(normalized_stack: np.ndarray, imag_tol: float = 1e-8) -> np.ndarray:
    from scipy.linalg import logm

    matrices = np.asarray(normalized_stack, dtype=float)
    if matrices.ndim != 3 or matrices.shape[0] < 1 or matrices.shape[1:] != (4, 4):
        raise ValueError("normalized_stack must have shape (n, 4, 4) with n >= 1")
    if not np.all(np.isfinite(matrices)):
        raise ValueError("normalized_stack must be finite")
    if isinstance(imag_tol, (bool, np.bool_)) or not isinstance(imag_tol, (int, float, np.integer, np.floating)):
        raise ValueError("imag_tol must be a real number")
    if not np.isfinite(imag_tol) or imag_tol <= 0:
        raise ValueError("imag_tol must be finite and positive")
    if np.any(np.abs(matrices[:, 0, 0] - 1.0) > 1e-8):
        raise ValueError("matrices must be intensity-normalized")
    result = np.empty_like(matrices)
    for index in range(matrices.shape[0]):
        value = np.asarray(logm(matrices[index]))
        if np.max(np.abs(np.imag(value))) > imag_tol:
            raise ValueError("matrix logarithm is not real")
        result[index] = np.real(value)
    return result

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [{'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'principal_mueller_logarithms(x)',
      'gold_call': '_oracle_principal_mueller_logarithms(x)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'principal_mueller_logarithms(np.concatenate([turn,ident]),1e-7)',
      'gold_call': '_oracle_principal_mueller_logarithms(np.concatenate([turn,ident]),1e-7)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'principal_mueller_logarithms(x[1:3],3e-9)',
      'gold_call': '_oracle_principal_mueller_logarithms(x[1:3],3e-9)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x[0])',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x[0])'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x[:, :3])',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x[:, :3])'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x[:0])',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x[:0])'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, bad)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, bad)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, nonfinite)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, nonfinite)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, flip)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, flip)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x, 0.0)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x, 0.0)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x, -1e-08)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x, -1e-08)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x, np.nan)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x, np.nan)'},
     {'setup': 'import numpy as np\n'
               'from scipy.linalg import expm\n'
               'g1=np.array([[0.,-.08,.03,.01],[-.08,-.04,.21,.05],[.03,-.21,-.03,-.34],[.01,-.05,.34,-.05]])\n'
               'g2=np.array([[0.,.05,-.02,-.02],[.05,-.02,-.12,.08],[-.02,.12,-.06,.19],[-.02,-.08,-.19,-.03]])\n'
               'x=np.stack([expm(g1+.25*i*g2) for i in range(5)])\n'
               'x=x/x[:,:1,:1]\n'
               'big=np.zeros((4,4)); big[1,2]=3.02; big[2,1]=-3.02; big[0,1]=big[1,0]=-.2; '
               'big[2,3]=-.4; big[3,2]=.4\n'
               'turn=expm(big)[None]; turn=turn/turn[:,:1,:1]\n'
               'ident=np.eye(4)[None]\n'
               'bad=x.copy(); bad[0,0,0]=.99\n'
               'nonfinite=x.copy(); nonfinite[2,1,1]=np.nan\n'
               'flip=np.diag([1.,-1.,1.,1.])[None]\n'
               'def rejects(fn,*a):\n'
               ' try: fn(*a)\n'
               ' except ValueError: return 1\n'
               ' return 0\n',
      'call': 'rejects(principal_mueller_logarithms, x, True)',
      'gold_call': 'rejects(_oracle_principal_mueller_logarithms, x, True)'}]
