"""
Rank exact moiety-balance rule multisets under iterative support cuts.

The source's minRules formulation represents a mechanism as nonnegative integer rule multiplicities, requires the selected rule columns to reproduce the overall moiety-change vector exactly, and minimizes the total number of rules. Successive solutions are generated by adding a support-based integer cut that excludes the previously selected rule support. This benchmark resolves equal-length solutions by lexicographic comparison of their expanded one-based rule-label tuples.

Returns
-------
Integer table containing the cut-ranked rule-count vectors.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def rank_parsimonious_rule_sets(
    rule_matrix: 'np.ndarray',
    target_change: 'np.ndarray',
    max_steps: int,
    limit: int,
) -> 'np.ndarray':
    """Return the source-style cut-ranked rule-count vectors.

    A candidate is a nonnegative integer count vector whose rule columns sum
    exactly to ``target_change`` and whose total count does not exceed
    ``max_steps``. Select candidates iteratively by minimum total count. For an
    equal objective, compare their expanded tuples of one-based rule labels
    lexicographically.

    After selecting a candidate with support ``S``, every subsequently ranked
    integer count vector ``y`` must satisfy

    ``sum(y[r] for r in S) <= len(S) - 1``.

    This integer support cutoff excludes the previously selected support and
    every count vector containing that complete support before the next
    candidate is selected.

    Parameters
    ----------
    rule_matrix
        Integer moiety-change matrix with shape ``(n_moieties, n_rules)``.
    target_change
        Nonzero integer overall moiety-change vector.
    max_steps
        Positive upper bound on total rule multiplicity.
    limit
        Positive maximum number of ranked candidates to return.

    Returns
    -------
    np.ndarray
        Integer array with one row per candidate. Column zero is the total rule
        count and the remaining columns are counts for rules 1 through
        ``n_rules``. The shape is ``(n_found, n_rules + 1)``.

    Raises
    ------
    ValueError
        If dimensions, integer domains, or scalar bounds are invalid.
    """
    return result

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_rank_parsimonious_rule_sets(
    rule_matrix: 'np.ndarray',
    target_change: 'np.ndarray',
    max_steps: int,
    limit: int,
) -> 'np.ndarray':
    matrix = np.asarray(rule_matrix)
    target = np.asarray(target_change)

    if matrix.ndim != 2 or matrix.shape[0] == 0 or matrix.shape[1] == 0:
        raise ValueError("rule_matrix must be a nonempty two-dimensional array")
    if target.ndim != 1 or target.size != matrix.shape[0]:
        raise ValueError("target_change has incompatible shape")
    if (
        not np.issubdtype(matrix.dtype, np.number)
        or not np.isrealobj(matrix)
        or np.any(~np.isfinite(matrix))
    ):
        raise ValueError("rule_matrix must be finite and numeric")
    if (
        not np.issubdtype(target.dtype, np.number)
        or not np.isrealobj(target)
        or np.any(~np.isfinite(target))
    ):
        raise ValueError("target_change must be finite and numeric")
    if np.any(matrix != np.rint(matrix)) or np.any(target != np.rint(target)):
        raise ValueError("rule changes and target must be integers")
    if not np.any(target != 0):
        raise ValueError("target_change must be nonzero")
    if (
        isinstance(max_steps, (bool, np.bool_))
        or not isinstance(max_steps, (int, np.integer))
        or int(max_steps) <= 0
    ):
        raise ValueError("max_steps must be a positive integer")
    if (
        isinstance(limit, (bool, np.bool_))
        or not isinstance(limit, (int, np.integer))
        or int(limit) <= 0
    ):
        raise ValueError("limit must be a positive integer")

    matrix = matrix.astype(int, copy=False)
    target = target.astype(int, copy=False)
    n_rules = matrix.shape[1]
    suffix_min = np.minimum.accumulate(matrix[:, ::-1], axis=1)[:, ::-1]
    suffix_max = np.maximum.accumulate(matrix[:, ::-1], axis=1)[:, ::-1]
    cuts = []
    selected = []

    def _admissible(residual, start, remaining):
        if remaining == 0:
            return not np.any(residual)
        if start >= n_rules:
            return False
        return bool(
            np.all(residual >= remaining * suffix_min[:, start])
            and np.all(residual <= remaining * suffix_max[:, start])
        )

    for n_steps in range(1, int(max_steps) + 1):
        labels = []

        def _search(start, remaining, residual):
            if len(selected) == int(limit):
                return True
            if remaining == 0:
                counts = np.bincount(labels, minlength=n_rules).astype(int)
                if any(
                    int(np.sum(counts[support])) > support.size - 1
                    for support in cuts
                ):
                    return False
                selected.append(
                    np.concatenate((np.array([n_steps], dtype=int), counts))
                )
                cuts.append(np.flatnonzero(counts))
                return len(selected) == int(limit)

            for rule in range(start, n_rules):
                next_residual = residual - matrix[:, rule]
                if not _admissible(next_residual, rule, remaining - 1):
                    continue
                labels.append(rule)
                done = _search(rule, remaining - 1, next_residual)
                labels.pop()
                if done:
                    return True
            return False

        if _admissible(target, 0, n_steps):
            _search(0, n_steps, target.copy())
        if len(selected) == int(limit):
            break

    if not selected:
        return np.empty((0, n_rules + 1), dtype=int)

    return np.vstack(selected)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {
            "setup": "import numpy as np\nT=np.array([[-1,-1,0,0,0],[0,1,-1,0,0],[0,0,0,1,-1],[1,0,1,-1,1]])\nt=np.array([-1,0,0,1])",
            "call": "rank_parsimonious_rule_sets(T.copy(),t.copy(),3,5)",
            "gold_call": "_oracle_rank_parsimonious_rule_sets(T.copy(),t.copy(),3,5)",
        },
        {
            "setup": "import numpy as np\nT=np.array([[1,2,-1]])\nt=np.array([2])",
            "call": "rank_parsimonious_rule_sets(T.copy(),t.copy(),4,4)",
            "gold_call": "_oracle_rank_parsimonious_rule_sets(T.copy(),t.copy(),4,4)",
        },
        {
            "setup": "import numpy as np\nT=np.array([[1,0],[0,2]])\nt=np.array([1,1])",
            "call": "rank_parsimonious_rule_sets(T.copy(),t.copy(),3,3)",
            "gold_call": "_oracle_rank_parsimonious_rule_sets(T.copy(),t.copy(),3,3)",
        },
        {
            "setup": "import numpy as np\nT=np.array([[1,1]])\nt=np.array([1])",
            "call": "rank_parsimonious_rule_sets(T.copy(),t.copy(),1,2)",
            "gold_call": "_oracle_rank_parsimonious_rule_sets(T.copy(),t.copy(),1,2)",
        },
        {
            "setup": "import numpy as np\nT=np.array([[1,.5],[0,1.]])\nt=np.array([1,1])\ndef check(fn):\n try: fn(T.copy(),t.copy(),3,2)\n except ValueError: return 1\n except Exception: return 2\n return 0",
            "call": "check(rank_parsimonious_rule_sets)",
            "gold_call": "check(_oracle_rank_parsimonious_rule_sets)",
        },
    ]
