"""
Compute the first-order, order-hbar relative correction to the Gaussian fluctuation integral of one coordinate that arises from its anharmonicity at the beads.

The harmonic (Gaussian) treatment of the fluctuations about a discretized orbit is corrected order by order in hbar. The first correction is generated by the third and fourth derivatives of the potential in that coordinate at each bead, weighted by the imaginary-time step, and by the fluctuation propagator supplied to the function. Both derivative orders contribute at the same order in hbar, and the correction is returned as one dimensionless number relative to the harmonic result. The same expression applies to a coordinate transverse to a tunnelling orbit and to a chain collapsed at a potential minimum.

Returns
-------
float: the first-order relative correction to the Gaussian fluctuation integral from the bead-local cubic and quartic anharmonicity (dimensionless)
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def anharmonic_fluctuation_correction(propagator: "np.ndarray", cubic: "np.ndarray", quartic: "np.ndarray", beta: float) -> float:
    '''First-order relative correction from bead-local cubic and quartic anharmonicity.

    Parameters
    ----------
    propagator : np.ndarray
        Symmetric positive-definite (N, N) array, the fluctuation propagator
        of the coordinate on the closed chain, in bohr^2 per unit of action.
    cubic : np.ndarray
        Length-N array of third derivatives of the potential with respect to
        the fluctuation coordinate at each bead, in hartree / bohr^3, in the
        same chain order as the propagator.
    quartic : np.ndarray
        Length-N array of the corresponding fourth derivatives, in
        hartree / bohr^4.
    beta : float
        Inverse temperature in 1/hartree (hbar = 1); the imaginary-time step
        of the chain is beta / N.

    Returns
    -------
    correction : float
        The first-order relative correction, dimensionless, to be added to 1
        in the corrected fluctuation integral. It is the sum of the
        contributions of the two derivative orders.

    Raises
    ------
    ValueError
        If propagator is not square, cubic and quartic are not
        one-dimensional arrays of its size, or beta is not positive.
    '''
    return correction

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_anharmonic_fluctuation_correction(propagator: "np.ndarray", cubic: "np.ndarray", quartic: "np.ndarray", beta: float) -> float:
    g = np.asarray(propagator, dtype=float)
    t3 = np.asarray(cubic, dtype=float)
    t4 = np.asarray(quartic, dtype=float)
    if g.ndim != 2 or g.shape[0] != g.shape[1]:
        raise ValueError("propagator must be a square matrix")
    n = g.shape[0]
    if t3.shape != (n,) or t4.shape != (n,):
        raise ValueError("cubic and quartic must be one-dimensional arrays of length N")
    if not float(beta) > 0.0:
        raise ValueError("beta must be positive")
    dtau = float(beta) / n
    tv, qv, d = dtau * t3, dtau * t4, np.diag(g)
    quartic_term = -0.125 * np.sum(qv * d ** 2)
    td = tv * d
    cubic_term = 0.125 * (td @ g @ td) + (tv @ (g ** 3) @ tv) / 12.0
    return float(quartic_term + cubic_term)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    base = """import numpy as np
def propagator(curv, beta, m):
    n = curv.size
    dtau = beta / n
    lap = 2.0 * np.eye(n) - np.roll(np.eye(n), 1, axis=1) - np.roll(np.eye(n), -1, axis=1)
    return np.linalg.inv((m / dtau) * lap + dtau * np.diag(curv))
m, we, beta = 1836.15267, 0.00415, 2975.0
"""
    return [
        # Normal: Morse-type couplings whose anharmonicity varies along a 32-bead chain.
        {
            "setup": base + """
n = 32
chi = 0.0138 + 0.0597 * np.exp(-np.cos(2.0 * np.pi * (np.arange(n) + 0.5) / n) ** 2 / 0.3)
alpha = np.sqrt(2.0 * m * we * chi)
G = propagator(np.full(n, m * we ** 2), beta, m)
cub, qua = -3.0 * m * we ** 2 * alpha, 7.0 * m * we ** 2 * alpha ** 2
""",
            "call": "anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
            "gold_call": "_oracle_anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
        },
        # Normal: uniform couplings on a 64-bead collapsed chain.
        {
            "setup": base + """
n = 64
alpha = np.sqrt(2.0 * m * we * 0.0138)
G = propagator(np.full(n, m * we ** 2), beta, m)
cub, qua = np.full(n, -3.0 * m * we ** 2 * alpha), np.full(n, 7.0 * m * we ** 2 * alpha ** 2)
""",
            "call": "anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
            "gold_call": "_oracle_anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
        },
        # Boundary: purely quartic anharmonicity, so only one derivative order contributes.
        {
            "setup": base + """
n = 20
G = propagator(np.full(n, m * we ** 2) * (1.0 + 0.2 * np.sin(2.0 * np.pi * np.arange(n) / n)), beta, m)
cub, qua = np.zeros(n), np.linspace(0.5, 2.0, n) * 1e-3
""",
            "call": "anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
            "gold_call": "_oracle_anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
        },
        # Boundary: purely cubic anharmonicity on the same chain.
        {
            "setup": base + """
n = 20
G = propagator(np.full(n, m * we ** 2) * (1.0 + 0.2 * np.sin(2.0 * np.pi * np.arange(n) / n)), beta, m)
cub, qua = np.linspace(-2.0, 1.0, n) * 1e-3, np.zeros(n)
""",
            "call": "anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
            "gold_call": "_oracle_anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)",
        },
        # Edge: very small chain (N = 4) with sign-changing cubic couplings, reduced units.
        {
            "setup": base + """
G = propagator(np.array([1.0, 1.2, 0.9, 1.1]), 4.0 * np.pi, 1.0)
cub, qua = np.array([0.3, -0.2, 0.1, -0.4]), np.array([0.5, 0.4, 0.6, 0.3])
""",
            "call": "anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), 4.0 * np.pi)",
            "gold_call": "_oracle_anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), 4.0 * np.pi)",
        },
        # Invalid: coupling arrays do not match the propagator size.
        {
            "setup": base + """
G = np.eye(4)
cub, qua = np.zeros(3), np.zeros(3)
def run_model():
    try:
        anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)
        return 0
    except ValueError:
        return 1
def run_oracle():
    try:
        _oracle_anharmonic_fluctuation_correction(G.copy(), cub.copy(), qua.copy(), beta)
        return 0
    except ValueError:
        return 1
""",
            "call": "run_model()",
            "gold_call": "run_oracle()",
        },
    ]
