"""
Compute the stationary wealth distribution generated by a converged saving policy, as the invariant law of a discrete-time process observed at a finite step.

The grid is uniform on the closed interval from the borrowing limit to the upper truncation point, with one node per row of the supplied saving policy and node zero at the borrowing limit. The two columns are the two income states, in the order low income then high income.

Over a single step of length h, an agent at node i in income state j does one of two things. With probability equal to one minus the switching rate of that state times h, wealth advances from the node position by h times the saving rate at that node and state, and the resulting position is distributed onto the two grid nodes bracketing it by linear interpolation, while the income state is unchanged; a landing position outside the grid is placed at the nearest endpoint. With the remaining probability the income state switches to the other one and wealth is left unchanged over that step.

Return the invariant law of that process as a 2-D array with one row per node and two columns, expressed as a density, so that the sum of all its entries multiplied by the grid spacing equals one. Under this convention the entry at node zero multiplied by the grid spacing is the weight the law places on the borrowing limit in that income state.

Inputs are the saving policy, the two switching rates, the step length, the borrowing limit and the upper truncation point.

Raises ValueError if the saving policy is not a two-dimensional finite array with exactly two columns and at least two rows, if any real input is not finite, if either switching rate is not strictly positive, if the step length is not strictly positive, if either switching rate multiplied by the step length is not strictly less than one, if the upper truncation point does not exceed the borrowing limit, or if the computed law has a negative entry.

The forward equation of a heterogeneous-agent model is the adjoint of the operator that appears in the optimisation problem, and discretising it well is a separate exercise from discretising the value function. One route writes the adjoint of the upwind operator directly. Another, which is what this step implements, does not discretise a differential operator at all: it treats the economy as a Markov chain on the grid, in which an agent takes one step of finite length along its saving policy and is redistributed onto neighbouring nodes by interpolation, and then asks for the invariant law of that chain. The chain's transition rule is a statement about where mass goes; the equation determining the invariant law is a statement about where mass at each node came from, and the two are related by an adjoint. Getting that relation the wrong way round produces a system that still has a solution and still normalises, but describes a different economy entirely.

Two features of the one-step rule carry economic content. First, the wealth update and the income switch do not both happen within a step: an agent whose income state changes has its wealth left where it was. That convention comes from the underlying discrete-time formulation of the process rather than from a numerical convenience, and reversing the order of the two events changes the computed distribution materially at any finite step length.

Second, the borrowing constraint is what generates an atom. In continuous time an agent whose saving rate is zero at the limit simply stays there. At a finite step, agents close to the limit whose saving rate would carry them below it are held at the limit instead, and the mass they contribute accumulates at a single node rather than spreading over an interval. That node therefore carries a weight which does not shrink as the grid is refined, unlike the density elsewhere, and it is the discrete counterpart of the point mass that the continuous stationary measure carries at the constraint.

An exact identity provides a check. Summing the invariant law over wealth for each income state leaves only the switching terms, so the total population share in each state must equal the opposite switching rate divided by the sum of the two, independently of the saving policy, the grid and the step length. Any implementation error in the transport part of the operator that fails to conserve mass shows up here immediately.

Returns
-------
np.ndarray, shape (n, 2) of dtype float, the invariant law of the one-step process as a density on the wealth grid, normalised so that the sum of all entries times the grid spacing is one, with columns holding the low and high income states in that order
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def stationary_distribution(s: np.ndarray, lam1: float, lam2: float, h: float,
                            xlow: float, xbar: float) -> np.ndarray:
    '''Return the invariant law of the one-step wealth process on the grid.

    Parameters
    ----------
    s : np.ndarray
        Shape (n, 2) saving policy on the wealth grid, columns being the low and high
        income states.
    lam1 : float
        Switching rate out of the low income state, strictly positive.
    lam2 : float
        Switching rate out of the high income state, strictly positive.
    h : float
        Step length of the discrete-time process, strictly positive.
    xlow : float
        Borrowing limit, the first grid node.
    xbar : float
        Upper truncation point, the last grid node.

    Returns
    -------
    out : np.ndarray
        Shape (n, 2) float array holding the invariant law as a density, normalised so that
        its sum multiplied by the grid spacing equals one.
    '''
    return out

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
import scipy.sparse as sp
import scipy.sparse.linalg as spl


def _oracle_stationary_distribution(s: np.ndarray, lam1: float, lam2: float, h: float,
                                    xlow: float, xbar: float) -> np.ndarray:
    s = np.asarray(s, dtype=float)
    if s.ndim != 2 or s.shape[1] != 2 or s.shape[0] < 2:
        raise ValueError("s must be a 2-D array with two columns and at least two rows")
    if not np.all(np.isfinite(s)):
        raise ValueError("s must be finite")
    for name, val in (("lam1", lam1), ("lam2", lam2), ("h", h), ("xlow", xlow), ("xbar", xbar)):
        if isinstance(val, (bool, np.bool_)) or not isinstance(val, (int, float, np.integer, np.floating)):
            raise ValueError(name + " must be a real scalar")
        if not np.isfinite(float(val)):
            raise ValueError(name + " must be finite")
    lam1, lam2, h = float(lam1), float(lam2), float(h)
    xlow, xbar = float(xlow), float(xbar)
    if not (lam1 > 0.0 and lam2 > 0.0):
        raise ValueError("both switching rates must be strictly positive")
    if not h > 0.0:
        raise ValueError("h must be strictly positive")
    if not (lam1 * h < 1.0 and lam2 * h < 1.0):
        raise ValueError("each switching rate times h must be strictly less than one")
    if not xbar > xlow:
        raise ValueError("xbar must exceed xlow")

    n = s.shape[0]
    dx = (xbar - xlow) / (n - 1)
    x = xlow + dx * np.arange(n)
    lam = np.array([lam1, lam2])

    mats = []
    for j in (0, 1):
        xt = np.clip(x + h * s[:, j], x[0], x[-1])
        t = (xt - x[0]) / dx
        k = np.clip(np.floor(t).astype(int), 0, n - 2)
        w = t - k
        rows = np.concatenate([np.arange(n), np.arange(n)])
        cols = np.concatenate([k, k + 1])
        vals = np.concatenate([1.0 - w, w])
        mats.append(sp.csr_matrix((vals, (rows, cols)), shape=(n, n)))

    eye = sp.eye(n)
    M = sp.bmat([[(1.0 - lam[0] * h) * mats[0].T - eye, lam[1] * h * eye],
                 [lam[0] * h * eye, (1.0 - lam[1] * h) * mats[1].T - eye]]).tocsc()
    rhs = -M[1:, 0].toarray().ravel()
    g = np.empty(2 * n)
    g[0] = 1.0
    g[1:] = spl.spsolve(M[1:, 1:].tocsc(), rhs)
    if not np.all(np.isfinite(g)):
        raise ValueError("the invariant law could not be computed")
    total = float(g.sum() * dx)
    if not total > 0.0:
        raise ValueError("the invariant law places no positive weight on the first node")
    g = g / total
    G = g.reshape(2, n).T.copy()
    if np.min(G) < -1e-10 * max(1.0, float(np.max(np.abs(G)))):
        raise ValueError("the computed law has a negative entry")
    return np.maximum(G, 0.0).astype(float)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        {
            "setup": """import numpy as np
xlow, xbar, nint = -0.25, 24.75, 1250
x = xlow + (xbar - xlow) / nint * np.arange(nint + 1)
s1 = -0.35 * np.sqrt(np.maximum(x - xlow, 0.0))
s2 = 0.41 - 0.062 * (x - xlow)
s = np.column_stack([s1, s2])
""",
            "call": "stationary_distribution(s, 0.25, 0.15, 1.0, xlow, xbar)",
            "gold_call": "_oracle_stationary_distribution(s, 0.25, 0.15, 1.0, xlow, xbar)",
        },
        {
            "setup": """import numpy as np
xlow, xbar, nint = -0.25, 24.75, 1250
x = xlow + (xbar - xlow) / nint * np.arange(nint + 1)
s1 = -0.35 * np.sqrt(np.maximum(x - xlow, 0.0))
s2 = 0.41 - 0.062 * (x - xlow)
s = np.column_stack([s1, s2])
G = stationary_distribution(s, 0.25, 0.15, 1.0, xlow, xbar)
Gg = _oracle_stationary_distribution(s, 0.25, 0.15, 1.0, xlow, xbar)
dx = (xbar - xlow) / nint
def shares():
    return [float(G[:, 0].sum() * dx), float(G[:, 1].sum() * dx)]
def gold_shares():
    return [float(Gg[:, 0].sum() * dx), float(Gg[:, 1].sum() * dx)]
""",
            "call": "shares()",
            "gold_call": "gold_shares()",
        },
        {
            "setup": """import numpy as np
xlow, xbar, nint = -0.15, 5.85, 60
x = xlow + (xbar - xlow) / nint * np.arange(nint + 1)
s = np.column_stack([-0.2 * (x - xlow), 0.3 - 0.1 * (x - xlow)])
""",
            "call": "stationary_distribution(s, 0.4, 0.4, 0.01, xlow, xbar)",
            "gold_call": "_oracle_stationary_distribution(s, 0.4, 0.4, 0.01, xlow, xbar)",
        },
        {
            "setup": """import numpy as np
xlow, xbar, nint = -0.15, 5.85, 60
x = xlow + (xbar - xlow) / nint * np.arange(nint + 1)
s = np.column_stack([-0.2 * (x - xlow), 0.3 - 0.1 * (x - xlow)])
""",
            "call": "stationary_distribution(s, 0.4, 0.4, 2.4, xlow, xbar)",
            "gold_call": "_oracle_stationary_distribution(s, 0.4, 0.4, 2.4, xlow, xbar)",
        },
        {
            "setup": """import numpy as np
s = np.zeros((5, 2))
def run_model():
    try:
        stationary_distribution(s, 0.25, 0.15, 5.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_stationary_distribution(s, 0.25, 0.15, 5.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        {
            "setup": """import numpy as np
s = np.zeros((5, 2))
def run_model():
    try:
        stationary_distribution(s, 0.25, 0.0, 1.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_stationary_distribution(s, 0.25, 0.0, 1.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        {
            "setup": """import numpy as np
s = np.zeros((5, 3))
def run_model():
    try:
        stationary_distribution(s, 0.25, 0.15, 1.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_stationary_distribution(s, 0.25, 0.15, 1.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        {
            "setup": """import numpy as np
s = np.zeros((5, 2))
s[2, 0] = np.inf
def run_model():
    try:
        stationary_distribution(s, 0.25, 0.15, 1.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_stationary_distribution(s, 0.25, 0.15, 1.0, -0.25, 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
