"""
This step performs the long-range precomputations needed to make the structured QR recurrence efficient. It computes A-transpose times U directly from the banded and semiseparable representation, forms an augmented upper generator by combining S with A-transpose times U, and builds suffix Gram matrices for the active portions of U. It also builds prefix products that accumulate the interaction between rows of U and W. These lookup quantities replace repeated long inner products during the QR iterations with fixed-size matrix operations, and the step initializes the structured perturbation state used by the first Householder update.

Efficient BPS Householder QR requires several long-range contractions to be available without repeatedly scanning the remaining matrix rows. The quantity $A^\top U$ is computed directly from the banded-plus-semiseparable representation and combined with $S$ to form the augmented upper generator $\widetilde S=[S,\;A^\top U]$. The recurrence also requires suffix Gram matrices $G_k=U[k:n,:]^\top U[k:n,:]$, generated by the backward update $G_k=G_{k+1}+U[k,:]^\top U[k,:]$, and prefix products $P_k=\sum_{t=1}^{k}U[t,:]W[t,:]^\top$, generated by forward accumulation. Computing these quantities once in $O(n)$ time converts the long inner products required during the QR recurrence into fixed-size matrix operations and initializes the zero perturbation state used at the first Householder step.

Returns
-------
Precomputed matrices (ATU, S_tilde, UU, and UW), and the zero-initialized state matrices (J, K, E, X, Y, Z)
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np

def precompute_bps_quantities(
    bands: np.ndarray,
    U: np.ndarray,
    V: np.ndarray,
    W: np.ndarray,
    S: np.ndarray,
) -> tuple[dict, dict]:
    """
    Precompute structured contractions and initialize the perturbation state.

    Parameters
    ----------
    bands : np.ndarray
        Compact banded component with shape (6, n), ordered by offsets
        (-2, -1, 0, +1, +2, +3).
    U, V : np.ndarray
        Lower-semiseparable generators, each with shape (n, 2).
    W, S : np.ndarray
        Upper-semiseparable generators, each with shape (n, 2).

    Returns
    -------
    precomp : dict
        Contains A_T_U with shape (n, 2), S_tilde with shape (n, 4),
        UU_lookup with shape (n, 2, 2), and UW_lookup with shape (n, 2, 2).
    state : dict
        Contains zero initial matrices J, K, E, X, Y, Z and the zero-based
        recurrence index k=0.

    Raises
    ------
    ValueError
        If the band representation or generator arrays have incompatible dimensions, 
        contain invalid numerical data, or do not define a valid BPS input.
    """
    return precomp, state

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np

def _band_entry(bands: np.ndarray, i: int, j: int) -> np.float64:
    d = j - i
    if d < -2 or d > 3:
        return np.float64(0.0)
    return np.float64(bands[d + 2, i])

def _oracle_precompute_bps_quantities(
    bands: np.ndarray,
    U: np.ndarray,
    V: np.ndarray,
    W: np.ndarray,
    S: np.ndarray,
) -> tuple[dict, dict]:
    """Reference implementation."""
    bands = np.asarray(bands, dtype=np.float64)
    U = np.asarray(U, dtype=np.float64)
    V = np.asarray(V, dtype=np.float64)
    W = np.asarray(W, dtype=np.float64)
    S = np.asarray(S, dtype=np.float64)

    if bands.ndim != 2 or bands.shape[0] != 6 or bands.shape[1] < 1:
        raise ValueError("bands must have shape (6, n), n >= 1")
    n = bands.shape[1]
    if U.shape != (n, 2) or V.shape != (n, 2):
        raise ValueError("U and V must each have shape (n, 2)")
    if W.shape != (n, 2) or S.shape != (n, 2):
        raise ValueError("W and S must each have shape (n, 2)")
    if not all(np.all(np.isfinite(x)) for x in (bands, U, V, W, S)):
        raise ValueError("all inputs must contain finite values")

    # Backward suffix Gram lookup.
    UU_lookup = np.empty((n, 2, 2), dtype=np.float64)
    gram = np.zeros((2, 2), dtype=np.float64)
    for k in range(n - 1, -1, -1):
        gram = gram + np.outer(U[k], U[k])
        UU_lookup[k] = gram

    # Forward prefix U W^T lookup.
    UW_lookup = np.empty((n, 2, 2), dtype=np.float64)
    prefix = np.zeros((2, 2), dtype=np.float64)
    for k in range(n):
        prefix = prefix + np.outer(U[k], W[k])
        UW_lookup[k] = prefix

    # B^T U in O(n) because the number of band diagonals is fixed.
    BTU = np.zeros((n, 2), dtype=np.float64)
    for i in range(n):
        j0 = max(0, i - 2)
        j1 = min(n - 1, i + 3)
        for j in range(j0, j1 + 1):
            BTU[j] += _band_entry(bands, i, j) * U[i]

    # A^T U = B^T U + lower-semiseparable contribution
    #                   + upper-semiseparable contribution.
    A_T_U = BTU.copy()
    for j in range(n):
        if j + 1 < n:
            suffix_after = UU_lookup[j + 1]
            A_T_U[j] += suffix_after @ V[j]
        if j > 0:
            prefix_before = UW_lookup[j - 1]
            A_T_U[j] += prefix_before @ S[j]

    S_tilde = np.concatenate((S, A_T_U), axis=1)

    precomp = {
        "A_T_U": A_T_U,
        "S_tilde": S_tilde,
        "UU_lookup": UU_lookup,
        "UW_lookup": UW_lookup,
    }
    state = {
        "J": np.zeros((2, 2), dtype=np.float64),
        "K": np.zeros((2, 2), dtype=np.float64),
        "E": np.zeros((2, 5), dtype=np.float64),
        "X": np.zeros((2, 2), dtype=np.float64),
        "Y": np.zeros((2, 2), dtype=np.float64),
        "Z": np.zeros((2, 5), dtype=np.float64),
        "k": 0,
    }
    return precomp, state

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return normal, boundary, edge, and invalid test case specifications."""
    return [
        {
            "setup": """import numpy as np
def make_case(n):
    i=np.arange(1,n+1,dtype=np.float64)
    bands=np.zeros((6,n),dtype=np.float64)
    bands[2]=5.0+0.2*np.sin(0.01*i)
    if n>=2:
        bands[1,1:]=0.6; bands[3,:-1]=-0.8
    if n>=3:
        bands[0,2:]=-0.1; bands[4,:-2]=0.15
    if n>=4:
        bands[5,:-3]=-0.05
    scale=1.0/np.sqrt(n)
    U=scale*np.column_stack((1+0.2*np.sin(0.017*i),0.7+0.15*np.cos(0.011*i)))
    V=scale*np.column_stack((0.9+0.1*np.cos(0.013*i),-0.6+0.12*np.sin(0.019*i)))
    W=scale*np.column_stack((0.8+0.18*np.sin(0.023*i),0.5+0.10*np.cos(0.029*i)))
    S=scale*np.column_stack((-0.7+0.11*np.cos(0.031*i),0.6+0.14*np.sin(0.037*i)))
    return bands,U,V,W,S
bands,U,V,W,S=make_case(8)""",
            "call":'(lambda o: (np.concatenate([np.asarray(o[0]["A_T_U"]).reshape(-1),np.asarray(o[0]["S_tilde"]).reshape(-1),np.asarray(o[0]["UU_lookup"]).reshape(-1),np.asarray(o[0]["UW_lookup"]).reshape(-1),np.asarray(o[1]["J"]).reshape(-1),np.asarray(o[1]["K"]).reshape(-1),np.asarray(o[1]["E"]).reshape(-1),np.asarray(o[1]["X"]).reshape(-1),np.asarray(o[1]["Y"]).reshape(-1),np.asarray(o[1]["Z"]).reshape(-1)]).tolist()+[int(o[1]["k"])]) )(precompute_bps_quantities(bands,U,V,W,S))',
            "gold_call":'(lambda o: (np.concatenate([np.asarray(o[0]["A_T_U"]).reshape(-1),np.asarray(o[0]["S_tilde"]).reshape(-1),np.asarray(o[0]["UU_lookup"]).reshape(-1),np.asarray(o[0]["UW_lookup"]).reshape(-1),np.asarray(o[1]["J"]).reshape(-1),np.asarray(o[1]["K"]).reshape(-1),np.asarray(o[1]["E"]).reshape(-1),np.asarray(o[1]["X"]).reshape(-1),np.asarray(o[1]["Y"]).reshape(-1),np.asarray(o[1]["Z"]).reshape(-1)]).tolist()+[int(o[1]["k"])]) )(_oracle_precompute_bps_quantities(bands,U,V,W,S))'},
        {
            "setup": """import numpy as np
def make_case(n):
    i=np.arange(1,n+1,dtype=np.float64)
    bands=np.zeros((6,n),dtype=np.float64)
    bands[2]=5.0+0.2*np.sin(0.01*i)
    if n>=2:
        bands[1,1:]=0.6; bands[3,:-1]=-0.8
    if n>=3:
        bands[0,2:]=-0.1; bands[4,:-2]=0.15
    if n>=4:
        bands[5,:-3]=-0.05
    scale=1.0/np.sqrt(n)
    U=scale*np.column_stack((1+0.2*np.sin(0.017*i),0.7+0.15*np.cos(0.011*i)))
    V=scale*np.column_stack((0.9+0.1*np.cos(0.013*i),-0.6+0.12*np.sin(0.019*i)))
    W=scale*np.column_stack((0.8+0.18*np.sin(0.023*i),0.5+0.10*np.cos(0.029*i)))
    S=scale*np.column_stack((-0.7+0.11*np.cos(0.031*i),0.6+0.14*np.sin(0.037*i)))
    return bands,U,V,W,S
bands,U,V,W,S=make_case(1)""",
            "call":'(lambda o: (np.concatenate([np.asarray(o[0]["A_T_U"]).reshape(-1),np.asarray(o[0]["S_tilde"]).reshape(-1),np.asarray(o[0]["UU_lookup"]).reshape(-1),np.asarray(o[0]["UW_lookup"]).reshape(-1),np.asarray(o[1]["J"]).reshape(-1),np.asarray(o[1]["K"]).reshape(-1),np.asarray(o[1]["E"]).reshape(-1),np.asarray(o[1]["X"]).reshape(-1),np.asarray(o[1]["Y"]).reshape(-1),np.asarray(o[1]["Z"]).reshape(-1)]).tolist()+[int(o[1]["k"])]) )(precompute_bps_quantities(bands,U,V,W,S))',
            "gold_call":'(lambda o: (np.concatenate([np.asarray(o[0]["A_T_U"]).reshape(-1),np.asarray(o[0]["S_tilde"]).reshape(-1),np.asarray(o[0]["UU_lookup"]).reshape(-1),np.asarray(o[0]["UW_lookup"]).reshape(-1),np.asarray(o[1]["J"]).reshape(-1),np.asarray(o[1]["K"]).reshape(-1),np.asarray(o[1]["E"]).reshape(-1),np.asarray(o[1]["X"]).reshape(-1),np.asarray(o[1]["Y"]).reshape(-1),np.asarray(o[1]["Z"]).reshape(-1)]).tolist()+[int(o[1]["k"])]) )(_oracle_precompute_bps_quantities(bands,U,V,W,S))'},
        {
            "setup": """import numpy as np
def make_case(n):
    i=np.arange(1,n+1,dtype=np.float64)
    bands=np.zeros((6,n),dtype=np.float64)
    bands[2]=5.0+0.2*np.sin(0.01*i)
    if n>=2:
        bands[1,1:]=0.6; bands[3,:-1]=-0.8
    if n>=3:
        bands[0,2:]=-0.1; bands[4,:-2]=0.15
    if n>=4:
        bands[5,:-3]=-0.05
    scale=1.0/np.sqrt(n)
    U=scale*np.column_stack((1+0.2*np.sin(0.017*i),0.7+0.15*np.cos(0.011*i)))
    V=scale*np.column_stack((0.9+0.1*np.cos(0.013*i),-0.6+0.12*np.sin(0.019*i)))
    W=scale*np.column_stack((0.8+0.18*np.sin(0.023*i),0.5+0.10*np.cos(0.029*i)))
    S=scale*np.column_stack((-0.7+0.11*np.cos(0.031*i),0.6+0.14*np.sin(0.037*i)))
    return bands,U,V,W,S
bands,U,V,W,S=make_case(64)""",
            "call":'(lambda o: (np.concatenate([np.asarray(o[0]["A_T_U"]).reshape(-1),np.asarray(o[0]["S_tilde"]).reshape(-1),np.asarray(o[0]["UU_lookup"]).reshape(-1),np.asarray(o[0]["UW_lookup"]).reshape(-1),np.asarray(o[1]["J"]).reshape(-1),np.asarray(o[1]["K"]).reshape(-1),np.asarray(o[1]["E"]).reshape(-1),np.asarray(o[1]["X"]).reshape(-1),np.asarray(o[1]["Y"]).reshape(-1),np.asarray(o[1]["Z"]).reshape(-1)]).tolist()+[int(o[1]["k"])]) )(precompute_bps_quantities(bands,U,V,W,S))',
            "gold_call":'(lambda o: (np.concatenate([np.asarray(o[0]["A_T_U"]).reshape(-1),np.asarray(o[0]["S_tilde"]).reshape(-1),np.asarray(o[0]["UU_lookup"]).reshape(-1),np.asarray(o[0]["UW_lookup"]).reshape(-1),np.asarray(o[1]["J"]).reshape(-1),np.asarray(o[1]["K"]).reshape(-1),np.asarray(o[1]["E"]).reshape(-1),np.asarray(o[1]["X"]).reshape(-1),np.asarray(o[1]["Y"]).reshape(-1),np.asarray(o[1]["Z"]).reshape(-1)]).tolist()+[int(o[1]["k"])]) )(_oracle_precompute_bps_quantities(bands,U,V,W,S))'},
        {
            "setup": """import numpy as np
def make_case(n):
    i=np.arange(1,n+1,dtype=np.float64)
    bands=np.zeros((6,n),dtype=np.float64)
    bands[2]=5.0+0.2*np.sin(0.01*i)
    if n>=2:
        bands[1,1:]=0.6; bands[3,:-1]=-0.8
    if n>=3:
        bands[0,2:]=-0.1; bands[4,:-2]=0.15
    if n>=4:
        bands[5,:-3]=-0.05
    scale=1.0/np.sqrt(n)
    U=scale*np.column_stack((1+0.2*np.sin(0.017*i),0.7+0.15*np.cos(0.011*i)))
    V=scale*np.column_stack((0.9+0.1*np.cos(0.013*i),-0.6+0.12*np.sin(0.019*i)))
    W=scale*np.column_stack((0.8+0.18*np.sin(0.023*i),0.5+0.10*np.cos(0.029*i)))
    S=scale*np.column_stack((-0.7+0.11*np.cos(0.031*i),0.6+0.14*np.sin(0.037*i)))
    return bands,U,V,W,S
bands,U,V,W,S=make_case(8)
bad_U=U[:7]
def run_model():
    try:
        precompute_bps_quantities(bands,bad_U,V,W,S); return 0
    except ValueError: return 1
    except Exception: return 2
def run_oracle():
    try:
        _oracle_precompute_bps_quantities(bands,bad_U,V,W,S); return 0
    except ValueError: return 1
    except Exception: return 2
""",
            "call":"run_model()","gold_call":"run_oracle()"
        },
        {
            "setup": """import numpy as np
def make_case(n):
    i=np.arange(1,n+1,dtype=np.float64)
    bands=np.zeros((6,n),dtype=np.float64)
    bands[2]=5.0+0.2*np.sin(0.01*i)
    if n>=2:
        bands[1,1:]=0.6; bands[3,:-1]=-0.8
    if n>=3:
        bands[0,2:]=-0.1; bands[4,:-2]=0.15
    if n>=4:
        bands[5,:-3]=-0.05
    scale=1.0/np.sqrt(n)
    U=scale*np.column_stack((1+0.2*np.sin(0.017*i),0.7+0.15*np.cos(0.011*i)))
    V=scale*np.column_stack((0.9+0.1*np.cos(0.013*i),-0.6+0.12*np.sin(0.019*i)))
    W=scale*np.column_stack((0.8+0.18*np.sin(0.023*i),0.5+0.10*np.cos(0.029*i)))
    S=scale*np.column_stack((-0.7+0.11*np.cos(0.031*i),0.6+0.14*np.sin(0.037*i)))
    return bands,U,V,W,S
bands,U,V,W,S=make_case(8)
bands[0,0]=np.nan
def run_model():
    try:
        precompute_bps_quantities(bands,U,V,W,S); return 0
    except ValueError: return 1
    except Exception: return 2
def run_oracle():
    try:
        _oracle_precompute_bps_quantities(bands,U,V,W,S); return 0
    except ValueError: return 1
    except Exception: return 2
""",
            "call":"run_model()","gold_call":"run_oracle()"
        },
    ]
