"""
Solve the interface and traction-free conditions of one axial mode for the Love displacement function coefficients of every layer.

The potential of sub-problem 06 satisfies the field equations but not the interface and surface conditions, so a homogeneous solution is added in every layer. It is generated by Love's displacement function L, with u_r = -d2L/drdz and u_z = 2(1 - nu) laplacian(L) - d2L/dz2 and the stresses that follow from the isotropic elastic law of the layer. For one axial mode, L in layer i is [E_i I_0(eta r) + F_i K_0(eta r) + P_i eta r I_1(eta r) + Q_i eta r K_1(eta r)] sin(eta z); the innermost layer contains the axis and carries only E_1 and P_1. This function returns the coefficients for which the total fields of this axial mode, potential part plus Love part, satisfy the mechanical conditions of the problem at every interface and at the outer surface r = r_l. The rows of that linear system differ in scale by many orders of magnitude, so the solve must be scaled to remain accurate.

Return convention: the first two entries are E_1 and P_1, and each following block of four holds E_i, F_i, P_i and Q_i of the next layer outward. potential_terms uses the amplitude convention of sub-problem 06, with entry [i, 0] at the outer radius of layer i and entry [i, 1] at its inner radius.

Returns
-------
np.ndarray of shape (4 * l - 2,), float: the Love coefficients ordered from the innermost layer outward.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np

def compute_love_mode_coefficients(radii: np.ndarray, poisson: np.ndarray,
                                   shear: np.ndarray, axial_eigenvalue: float,
                                   potential_terms: np.ndarray) -> np.ndarray:
    """Love displacement function coefficients of one axial mode.

    Parameters
    ----------
    radii : np.ndarray
        Shape (l,). Outer radius of each layer in metres, strictly increasing,
        with l >= 2.
    poisson : np.ndarray
        Shape (l,). Poisson ratio of each layer, each in (0, 0.5).
    shear : np.ndarray
        Shape (l,). Shear modulus of each layer in Pa, all > 0.
    axial_eigenvalue : float
        Axial eigenvalue eta of this mode in inverse metres (> 0).
    potential_terms : np.ndarray
        Shape (l, 2, 6). Entry [i, 0] holds the six potential amplitudes of
        layer i evaluated at its outer radius radii[i], and entry [i, 1] holds
        them at its inner radius radii[i-1]. Entry [0, 1] is never used.

    Returns
    -------
    coefficients : np.ndarray
        Array of shape (4 * l - 2,). The first two entries are the bounded
        coefficients E and P of the innermost layer; each following block of
        four holds E, F, P and Q of the next layer outward.

    Raises
    ------
    ValueError
        If radii, poisson and shear do not share a single length l >= 2;
        if radii is not finite, positive and strictly increasing; if any
        poisson entry is not finite and inside the open interval (0,
        0.5); if any shear entry is not finite and greater than 0; if
        potential_terms is not a finite array of shape (l, 2, 6); if
        axial_eigenvalue is not a finite number greater than 0; or if
        the assembled interface system has an identically zero row or
        column.
    """
    return coefficients  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np

def _oracle_compute_love_mode_coefficients(radii: np.ndarray, poisson: np.ndarray,
                                           shear: np.ndarray,
                                           axial_eigenvalue: float,
                                           potential_terms: np.ndarray) -> np.ndarray:
    # Local imports keep the oracle self-contained when the harness
    # executes it in isolation.
    import numpy as np
    from scipy.special import i0, i1, k0, k1

    radii = np.asarray(radii, dtype=float).ravel()
    poisson = np.asarray(poisson, dtype=float).ravel()
    shear = np.asarray(shear, dtype=float).ravel()
    potential_terms = np.asarray(potential_terms, dtype=float)
    n_layers = radii.size
    if n_layers < 2 or poisson.size != n_layers or shear.size != n_layers:
        raise ValueError("radii, poisson and shear must share one length l >= 2")
    if not np.all(np.isfinite(radii)) or radii[0] <= 0.0 or np.any(np.diff(radii) <= 0.0):
        raise ValueError("radii must be finite, positive and strictly increasing")
    if not (np.all(np.isfinite(poisson)) and np.all(poisson > 0.0) and np.all(poisson < 0.5)):
        raise ValueError("poisson entries must be finite and in the open interval (0, 0.5)")
    if not (np.all(np.isfinite(shear)) and np.all(shear > 0.0)):
        raise ValueError("shear entries must be finite and > 0")
    if potential_terms.shape != (n_layers, 2, 6) or not np.all(np.isfinite(potential_terms)):
        raise ValueError("potential_terms must be a finite array of shape (l, 2, 6)")
    if not (isinstance(axial_eigenvalue, (int, float, np.floating, np.integer))
            and np.isfinite(axial_eigenvalue) and float(axial_eigenvalue) > 0.0):
        raise ValueError("axial_eigenvalue must be a finite number > 0")

    eta = float(axial_eigenvalue)

    def _love_rows(radius, nu, modulus):
        """Rows of amplitudes per unit E, F, P and Q at one radius of one layer."""
        x = eta * radius
        bessel_i0, bessel_i1 = i0(x), i1(x)
        bessel_k0, bessel_k1 = k0(x), k1(x)
        eta2, eta3 = eta ** 2, eta ** 3
        radial = np.array([-eta2 * bessel_i1, eta2 * bessel_k1,
                           -eta2 * x * bessel_i0, eta2 * x * bessel_k0])
        axial = np.array([eta2 * bessel_i0, eta2 * bessel_k0,
                          4.0 * (1.0 - nu) * eta2 * bessel_i0 + eta2 * x * bessel_i1,
                          -4.0 * (1.0 - nu) * eta2 * bessel_k0 + eta2 * x * bessel_k1])
        normal = 2.0 * modulus * np.array([
            -eta3 * (bessel_i0 - bessel_i1 / x),
            -eta3 * (bessel_k0 + bessel_k1 / x),
            2.0 * nu * eta3 * bessel_i0 - eta3 * (bessel_i0 + x * bessel_i1),
            -2.0 * nu * eta3 * bessel_k0 - eta3 * (-bessel_k0 + x * bessel_k1)])
        hoop = 2.0 * modulus * np.array([
            -eta2 / radius * bessel_i1,
            eta2 / radius * bessel_k1,
            2.0 * nu * eta3 * bessel_i0 - eta2 / radius * x * bessel_i0,
            -2.0 * nu * eta3 * bessel_k0 + eta2 / radius * x * bessel_k0])
        axial_normal = 2.0 * modulus * np.array([
            eta3 * bessel_i0, eta3 * bessel_k0,
            2.0 * (2.0 - nu) * eta3 * bessel_i0 + eta3 * x * bessel_i1,
            -2.0 * (2.0 - nu) * eta3 * bessel_k0 + eta3 * x * bessel_k1])
        shear_row = 2.0 * modulus * np.array([
            eta3 * bessel_i1, -eta3 * bessel_k1,
            2.0 * (1.0 - nu) * eta3 * bessel_i1 + eta3 * x * bessel_i0,
            2.0 * (1.0 - nu) * eta3 * bessel_k1 - eta3 * x * bessel_k0])
        rows = np.array([radial, axial, normal, hoop, axial_normal, shear_row])
        return rows

    def _columns(i):
        return (0, 2) if i == 0 else (2 + 4 * (i - 1), 2 + 4 * i)

    def _block(i, radius):
        rows = _love_rows(radius, poisson[i], shear[i])
        return rows[:, [0, 2]] if i == 0 else rows

    size = 4 * n_layers - 2
    matrix = np.zeros((size, size), dtype=float)
    rhs = np.zeros(size, dtype=float)

    row = 0
    # Radial displacement, axial displacement, radial stress and shear stress
    # are continuous across every bonded interface. Hoop and axial stress jump.
    for i in range(n_layers - 1):
        radius = radii[i]
        inner_block = _block(i, radius)
        outer_block = _block(i + 1, radius)
        inner_start, inner_stop = _columns(i)
        outer_start, outer_stop = _columns(i + 1)
        for component in (0, 1, 2, 5):
            matrix[row, inner_start:inner_stop] = inner_block[component]
            matrix[row, outer_start:outer_stop] = -outer_block[component]
            rhs[row] = potential_terms[i + 1, 1, component] - potential_terms[i, 0, component]
            row += 1
    # The outer cylindrical surface is traction free.
    radius = radii[-1]
    outer_block = _block(n_layers - 1, radius)
    start, stop = _columns(n_layers - 1)
    for component in (2, 5):
        matrix[row, start:stop] = outer_block[component]
        rhs[row] = -potential_terms[n_layers - 1, 0, component]
        row += 1

    # Displacement rows and traction rows differ by many orders of magnitude,
    # so the system is equilibrated by rows and then by columns before solving.
    row_scale = np.max(np.abs(matrix), axis=1)
    if np.any(row_scale <= 0.0):
        raise ValueError("interface system has an identically zero row")
    matrix = matrix / row_scale[:, None]
    rhs = rhs / row_scale
    column_scale = np.max(np.abs(matrix), axis=0)
    if np.any(column_scale <= 0.0):
        raise ValueError("interface system has an identically zero column")

    return np.linalg.solve(matrix / column_scale, rhs) / column_scale

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: benchmark three-layer via, lowest axial mode (normal scenario) ---
        {
            "setup": """import numpy as np
def digest(*parts):
    # The harness compares plain numbers, so each array this step returns is
    # reduced to two descriptors of order one: a normalized weighted sum that
    # pins down its shape, and the log of its weighted magnitude that pins down
    # its scale. Both stay of order one whatever the component is worth, so an
    # error in a small component cannot hide behind a large one.
    total = 0.0
    for k, part in enumerate(parts):
        x = np.asarray(part, dtype=float).ravel()
        w = 1.0 + 0.5 * np.arange(x.size) / max(x.size, 1)
        mag = float(np.dot(np.abs(x), w)) + 1e-12
        total += (k + 1.0) * float(np.dot(x, w)) / mag + np.log(mag)
    return float(total / len(parts))
radii = np.array([15.0e-6, 16.0e-6, 30.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
young = np.array([110.0e9, 70.0e9, 170.0e9])
shear = young / (2.0 * (1.0 + poisson))
eta = np.pi / (2.0 * 200.0e-6)
scales = np.array([1.0e-9, 1.0e-9, 1.0e8, 1.0e8, 1.0e8, 1.0e7])
potential = (np.linspace(-1.0, 1.0, 36).reshape(3, 2, 6) + 0.3) * scales
""",
            "call": "digest(compute_love_mode_coefficients(radii, poisson, shear, eta, potential))",
            "gold_call": "digest(_oracle_compute_love_mode_coefficients(radii, poisson, shear, eta, potential))",
        },
        # --- Valid: fourth axial mode, larger eta r across the stack ---
        {
            "setup": """import numpy as np
def digest(*parts):
    total = 0.0
    for k, part in enumerate(parts):
        x = np.asarray(part, dtype=float).ravel()
        w = 1.0 + 0.5 * np.arange(x.size) / max(x.size, 1)
        mag = float(np.dot(np.abs(x), w)) + 1e-12
        total += (k + 1.0) * float(np.dot(x, w)) / mag + np.log(mag)
    return float(total / len(parts))
radii = np.array([15.0e-6, 16.0e-6, 30.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
young = np.array([110.0e9, 70.0e9, 170.0e9])
shear = young / (2.0 * (1.0 + poisson))
eta = 7.0 * np.pi / (2.0 * 200.0e-6)
scales = np.array([1.0e-9, 1.0e-9, 1.0e8, 1.0e8, 1.0e8, 1.0e7])
potential = (np.linspace(-1.0, 1.0, 36).reshape(3, 2, 6) + 0.3) * scales
""",
            "call": "digest(compute_love_mode_coefficients(radii, poisson, shear, eta, potential))",
            "gold_call": "digest(_oracle_compute_love_mode_coefficients(radii, poisson, shear, eta, potential))",
        },
        # --- Boundary: two layers only, the smallest system the method admits ---
        {
            "setup": """import numpy as np
def digest(*parts):
    total = 0.0
    for k, part in enumerate(parts):
        x = np.asarray(part, dtype=float).ravel()
        w = 1.0 + 0.5 * np.arange(x.size) / max(x.size, 1)
        mag = float(np.dot(np.abs(x), w)) + 1e-12
        total += (k + 1.0) * float(np.dot(x, w)) / mag + np.log(mag)
    return float(total / len(parts))
radii = np.array([15.0e-6, 30.0e-6])
poisson = np.array([0.35, 0.28])
shear = np.array([110.0e9, 170.0e9]) / (2.0 * (1.0 + poisson))
eta = np.pi / (2.0 * 200.0e-6)
scales = np.array([1.0e-9, 1.0e-9, 1.0e8, 1.0e8, 1.0e8, 1.0e7])
potential = (np.linspace(-1.0, 1.0, 24).reshape(2, 2, 6) + 0.3) * scales
""",
            "call": "digest(compute_love_mode_coefficients(radii, poisson, shear, eta, potential))",
            "gold_call": "digest(_oracle_compute_love_mode_coefficients(radii, poisson, shear, eta, potential))",
        },
        # --- Edge: zero right-hand side must give the trivial solution ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 16.0e-6, 30.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
shear = np.array([110.0e9, 70.0e9, 170.0e9]) / (2.0 * (1.0 + poisson))
eta = np.pi / (2.0 * 200.0e-6)
potential = np.zeros((3, 2, 6))
def check(fn):
    sol = np.asarray(fn(radii, poisson, shear, eta, potential), dtype=float)
    return int(sol.size == 10), int(np.max(np.abs(sol)) < 1e-30)
""",
            "call": "check(compute_love_mode_coefficients)",
            "gold_call": "check(_oracle_compute_love_mode_coefficients)",
        },
        # --- Consistency: the solved coefficients reproduce the imposed conditions ---
        {
            "setup": """import numpy as np
from scipy.special import i0, i1, k0, k1
radii = np.array([15.0e-6, 16.0e-6, 30.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
shear = np.array([110.0e9, 70.0e9, 170.0e9]) / (2.0 * (1.0 + poisson))
eta = np.pi / (2.0 * 200.0e-6)
scales = np.array([1.0e-9, 1.0e-9, 1.0e8, 1.0e8, 1.0e8, 1.0e7])
potential = (np.linspace(-1.0, 1.0, 36).reshape(3, 2, 6) + 0.3) * scales
def rows(r, nu, g):
    x = eta * r
    a0, a1, b0, b1 = i0(x), i1(x), k0(x), k1(x)
    e2, e3 = eta ** 2, eta ** 3
    ur = np.array([-e2 * a1, e2 * b1, -e2 * x * a0, e2 * x * b0])
    uz = np.array([e2 * a0, e2 * b0, 4.0 * (1.0 - nu) * e2 * a0 + e2 * x * a1,
                   -4.0 * (1.0 - nu) * e2 * b0 + e2 * x * b1])
    srr = 2.0 * g * np.array([-e3 * (a0 - a1 / x), -e3 * (b0 + b1 / x),
                              2.0 * nu * e3 * a0 - e3 * (a0 + x * a1),
                              -2.0 * nu * e3 * b0 - e3 * (-b0 + x * b1)])
    srz = 2.0 * g * np.array([e3 * a1, -e3 * b1,
                              2.0 * (1.0 - nu) * e3 * a1 + e3 * x * a0,
                              2.0 * (1.0 - nu) * e3 * b1 - e3 * x * b0])
    return np.array([ur, uz, srr, srz])
def check(fn):
    sol = np.asarray(fn(radii, poisson, shear, eta, potential), dtype=float)
    parts = [np.array([sol[0], 0.0, sol[1], 0.0]), sol[2:6], sol[6:10]]
    worst = 0.0
    for i in range(2):
        r = radii[i]
        left = rows(r, poisson[i], shear[i]) @ parts[i] + potential[i, 0, [0, 1, 2, 5]]
        right = rows(r, poisson[i + 1], shear[i + 1]) @ parts[i + 1] + potential[i + 1, 1, [0, 1, 2, 5]]
        scale = np.maximum(np.abs(left), 1.0e-30)
        worst = max(worst, float(np.max(np.abs(left - right) / scale)))
    free = rows(radii[-1], poisson[-1], shear[-1]) @ parts[-1] + potential[-1, 0, [0, 1, 2, 5]]
    traction = max(abs(free[2]) / max(abs(potential[-1, 0, 2]), 1.0e-30),
                   abs(free[3]) / max(abs(potential[-1, 0, 5]), 1.0e-30))
    return int(worst < 1e-8), int(traction < 1e-8)
""",
            "call": "check(compute_love_mode_coefficients)",
            "gold_call": "check(_oracle_compute_love_mode_coefficients)",
        },
        # --- Invalid: a single layer leaves nothing to match ---
        {
            "setup": """import numpy as np
radii = np.array([30.0e-6])
poisson = np.array([0.28])
shear = np.array([66.4e9])
potential = np.zeros((1, 2, 6))
def run_model():
    try:
        compute_love_mode_coefficients(radii, poisson, shear, 7854.0, potential)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_love_mode_coefficients(radii, poisson, shear, 7854.0, potential)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: potential table of the wrong shape ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 30.0e-6])
poisson = np.array([0.35, 0.28])
shear = np.array([40.7e9, 66.4e9])
potential = np.zeros((2, 6))
def run_model():
    try:
        compute_love_mode_coefficients(radii, poisson, shear, 7854.0, potential)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_love_mode_coefficients(radii, poisson, shear, 7854.0, potential)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: Poisson ratio at the incompressible limit ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 30.0e-6])
poisson = np.array([0.5, 0.28])
shear = np.array([40.7e9, 66.4e9])
potential = np.zeros((2, 2, 6))
def run_model():
    try:
        compute_love_mode_coefficients(radii, poisson, shear, 7854.0, potential)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_love_mode_coefficients(radii, poisson, shear, 7854.0, potential)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
