"""
Identify the candidate denominator pairs that can be separated in the partial-fraction decomposition.

Equations (4.19) and (4.29) use polynomial ideal membership as the pair-separation criterion. For each ordered candidate pair, construct a Gröbner basis of the two affine denominator factors over the supplied prime field and reduce the reconstructed numerator. Membership holds exactly when the polynomial remainder is zero; simple factor divisibility is not sufficient.

Returns
-------
Return a one-dimensional integer NumPy array containing one membership flag for each candidate pair in the supplied order. Each flag must be 1 for zero remainder and 0 otherwise. Raise ValueError for malformed coefficient arrays, malformed factors, invalid pair indices, repeated indices within a pair, or an invalid prime.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np

def pair_ideal_membership(
    numerator_coefficients: np.ndarray,
    factors: np.ndarray,
    pairs: np.ndarray,
    prime: int,
) -> np.ndarray:
    """Test membership in each pair-generated affine ideal.

    Parameters
    ----------
    numerator_coefficients : np.ndarray
        Integer matrix C where C[i,j] multiplies u**i * v**j.
    factors : np.ndarray
        Integer array of shape (f,3), with rows [c,a,b]
        representing c + a*u + b*v.
    pairs : np.ndarray
        Integer array of shape (m,2) containing factor-index pairs.
    prime : int
        Odd prime modulus.

    Returns
    -------
    np.ndarray
        Integer vector of length m. Entry k is 1 when the numerator
        belongs to the ideal generated by the selected factor pair,
        and 0 otherwise.

    Raises
    ------
    ValueError
        If an input is malformed, the modulus is invalid, or a pair
        contains equal or out-of-range factor indices.
    """
    return None

# =============================================================================
# GOLD SOLUTION
# =============================================================================

from math import comb

import numpy as np


def _is_prime_integer(value):
    if isinstance(value, (bool, np.bool_)) or not isinstance(
        value, (int, np.integer)
    ):
        return False

    value = int(value)
    if value < 3:
        return False

    divisor = 2
    while divisor * divisor <= value:
        if value % divisor == 0:
            return False
        divisor += 1

    return True


def _oracle_pair_ideal_membership(
    numerator_coefficients,
    factors,
    pairs,
    prime,
):
    coefficients = np.asarray(numerator_coefficients)
    factors = np.asarray(factors)
    pairs = np.asarray(pairs)

    if (
        coefficients.ndim != 2
        or coefficients.size == 0
        or not np.issubdtype(coefficients.dtype, np.integer)
    ):
        raise ValueError(
            "numerator_coefficients must be a nonempty integer matrix"
        )

    if (
        factors.ndim != 2
        or factors.shape[1] != 3
        or factors.size == 0
        or not np.issubdtype(factors.dtype, np.integer)
    ):
        raise ValueError("factors must be an integer (f,3) array")

    if (
        pairs.ndim != 2
        or pairs.shape[1] != 2
        or pairs.size == 0
        or not np.issubdtype(pairs.dtype, np.integer)
    ):
        raise ValueError("pairs must be an integer (m,2) array")

    if not _is_prime_integer(prime):
        raise ValueError("prime must be an odd prime")

    prime = int(prime)

    def evaluate_tensor(point_u, point_v):
        return sum(
            int(coefficients[i, j])
            * pow(point_u, i, prime)
            * pow(point_v, j, prime)
            for i in range(coefficients.shape[0])
            for j in range(coefficients.shape[1])
        ) % prime

    def vanishes_on_line(constant, u_coefficient, v_coefficient):
        result_degree = (
            coefficients.shape[0] + coefficients.shape[1] - 2
        )
        result = np.zeros(result_degree + 1, dtype=np.int64)

        if v_coefficient % prime:
            inverse = pow(v_coefficient % prime, -1, prime)
            alpha = -constant * inverse % prime
            beta = -u_coefficient * inverse % prime

            # Substitute v = alpha + beta*u.
            for i in range(coefficients.shape[0]):
                for j in range(coefficients.shape[1]):
                    coefficient = int(coefficients[i, j]) % prime

                    for k in range(j + 1):
                        result[i + k] += (
                            coefficient
                            * comb(j, k)
                            * pow(alpha, j - k, prime)
                            * pow(beta, k, prime)
                        )
                        result[i + k] %= prime
        else:
            inverse = pow(u_coefficient % prime, -1, prime)
            alpha = -constant * inverse % prime
            beta = -v_coefficient * inverse % prime

            # Substitute u = alpha + beta*v.
            for i in range(coefficients.shape[0]):
                for j in range(coefficients.shape[1]):
                    coefficient = int(coefficients[i, j]) % prime

                    for k in range(i + 1):
                        result[j + k] += (
                            coefficient
                            * comb(i, k)
                            * pow(alpha, i - k, prime)
                            * pow(beta, k, prime)
                        )
                        result[j + k] %= prime

        return bool(np.all(result % prime == 0))

    flags = []

    for left, right in pairs:
        left = int(left)
        right = int(right)

        if (
            left == right
            or left < 0
            or right < 0
            or left >= len(factors)
            or right >= len(factors)
        ):
            raise ValueError(
                "pair indices must be distinct and in range"
            )

        constant_1, u_1, v_1 = (
            int(value) % prime for value in factors[left]
        )
        constant_2, u_2, v_2 = (
            int(value) % prime for value in factors[right]
        )

        determinant = (u_1 * v_2 - u_2 * v_1) % prime

        if determinant:
            inverse = pow(determinant, -1, prime)

            point_u = (
                (v_1 * constant_2 - v_2 * constant_1)
                * inverse
            ) % prime

            point_v = (
                (u_2 * constant_1 - u_1 * constant_2)
                * inverse
            ) % prime

            flags.append(
                int(evaluate_tensor(point_u, point_v) == 0)
            )
            continue

        if u_1 == v_1 == u_2 == v_2 == 0:
            if constant_1 or constant_2:
                flags.append(1)
            else:
                flags.append(
                    int(np.all(coefficients % prime == 0))
                )
            continue

        if u_1 or v_1:
            constant = constant_1
            u_coefficient = u_1
            v_coefficient = v_1
            other_constant = constant_2
            other_u = u_2
            other_v = v_2
        else:
            constant = constant_2
            u_coefficient = u_2
            v_coefficient = v_2
            other_constant = constant_1
            other_u = u_1
            other_v = v_1

        inconsistent = (
            (
                u_coefficient * other_constant
                - other_u * constant
            ) % prime != 0
            or (
                v_coefficient * other_constant
                - other_v * constant
            ) % prime != 0
        )

        if inconsistent:
            # Parallel inconsistent affine equations generate 1.
            flags.append(1)
        else:
            flags.append(
                int(
                    vanishes_on_line(
                        constant,
                        u_coefficient,
                        v_coefficient,
                    )
                )
            )

    return np.asarray(flags, dtype=np.int64)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Compare results from independent equivalent input objects."""
    return [{'setup': 'import numpy as np\n'
               'from copy import deepcopy\n'
               'coefficients=np.array([[42,25,10,3],[52,15,99,0],[17,5,0,0],[1,0,0,0]],dtype=np.int64)\n'
               'factors=np.array([[1,1,0],[2,0,1],[4,1,1],[5,2,100]],dtype=np.int64)\n'
               'pairs=np.array([[0,1],[1,2],[0,3],[2,3]],dtype=np.int64)\n'
               'p=101',
      'call': 'pair_ideal_membership(*deepcopy((coefficients, factors, pairs, p)))',
      'gold_call': '_oracle_pair_ideal_membership(*deepcopy((coefficients, factors, pairs, p)))'},
     {'setup': 'import numpy as np\n'
               'from copy import deepcopy\n'
               'coefficients=np.zeros((2,2),dtype=np.int64)\n'
               'factors=np.array([[1,1,0],[2,0,1]],dtype=np.int64)\n'
               'pairs=np.array([[0,1]],dtype=np.int64)\n'
               'p=101',
      'call': 'pair_ideal_membership(*deepcopy((coefficients, factors, pairs, p)))',
      'gold_call': '_oracle_pair_ideal_membership(*deepcopy((coefficients, factors, pairs, p)))'},
     {'setup': 'import numpy as np\n'
               'from copy import deepcopy\n'
               'def _expect_value_error(function, arguments):\n'
               '    try:\n'
               '        function(*arguments)\n'
               '    except ValueError:\n'
               '        return 1\n'
               "    raise AssertionError('Expected ValueError')\n"
               'coefficients=np.array([[1]],dtype=np.int64)\n'
               'factors=np.array([[1,1,0]],dtype=np.int64)\n'
               'pairs=np.array([[0,1]],dtype=np.int64)\n'
               'p=101\n'
               'arguments=(coefficients,factors,pairs,p)',
      'call': '_expect_value_error(pair_ideal_membership, deepcopy(arguments))',
      'gold_call': '_expect_value_error(_oracle_pair_ideal_membership, deepcopy(arguments))'}]
