"""
Step 03: Autocorrelation of a thawed Gaussian with local or constant reference Hessian.

Autocorrelation of a thawed Gaussian wavepacket propagated with a local or a constant reference Hessian.

A single thawed Gaussian can approximate the evolution of a vibrational wavepacket after a vertical transition at the cost of
one classical trajectory. The Gaussian evolves exactly in an effective quadratic potential built about its instantaneous
centre q_t,
    V_eff(q) = V(q_t) + grad V(q_t) . (q - q_t) + (1/2) (q - q_t)^T K (q - q_t),
so the centre follows the true anharmonic classical trajectory while the width and the phase feel only the matrix K. In the
local harmonic variant K is the Hessian of the true surface at q_t. Replacing it by one constant reference matrix removes all
Hessian evaluations along the path and, when that matrix is positive definite, keeps the width oscillations bounded. The
choice of that reference (the excited-state minimum, the Franck-Condon point or the initial-state Hessian) decides which part
of the dynamics is described best.

The quantity that enters vibronic spectra is the autocorrelation C(t) = <psi_0|psi_t> between the initial vibrational state
and the propagated Gaussian, which includes the complete phase acquired by the wavepacket. Because the effective Hamiltonian
is quadratic, its propagation splits into a kinetic flow, generated by the kinetic energy alone, and a potential flow,
generated by V_eff alone with the centre and K held fixed, and each flow maps a Gaussian to a Gaussian exactly. Symmetric
compositions of the two flows give time-reversible integrators of any even order. Coordinates are mass-weighted with unit
masses and hbar = 1.

Returns
-------
numpy.ndarray of shape (n_steps + 1, 2), real and imaginary parts of the thawed Gaussian autocorrelation C(t_n) with its full phase
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def thawed_gaussian_autocorrelation(displacement: float, surface_params: "np.ndarray", ground_params: "np.ndarray", hessian_mode: int, time_step: float, n_steps: int) -> "np.ndarray":
    '''Autocorrelation C(t_n) = <psi_0|psi_n>, t_n = n time_step, of a thawed Gaussian propagated by a fourth-order composition.

    psi_0(q) = pi^(-1/2) (omega_1 omega_2)^(1/4) exp(-(1/2) q^T R diag(omega_1, omega_2) R^T q) is the vibrational ground state
    of the initial electronic state, with R = [[cos(theta), -sin(theta)], [sin(theta), cos(theta)]], and it is also the Gaussian
    at t = 0. One step of length dt applies, for each weight w in (w_1, w_0, w_1) with w_1 = 1 / (2 - 2^(1/3)) and
    w_0 = -2^(1/3) / (2 - 2^(1/3)), the exact kinetic flow for a time w dt / 2, the exact potential flow for a time w dt and the
    exact kinetic flow for a time w dt / 2. The kinetic flow is free evolution under -(1/2)(d^2/dq1^2 + d^2/dq2^2). The
    potential flow is evolution under V_eff with the centre q_c of the Gaussian at the start of that flow, where K is the
    Hessian of the excited-state surface at q_c when hessian_mode is 0, and a fixed matrix otherwise. psi_n is the Gaussian
    after n steps, including its full phase.

    Parameters
    ----------
    displacement : float
        Stretch coordinate d of the excited-state minimum.
    surface_params : np.ndarray
        Array [omega_e, chi, omega_b, gamma, delta] of the excited-state surface.
    ground_params : np.ndarray
        Array [omega_1, omega_2, theta] with omega_1, omega_2 > 0 and theta in radians.
    hessian_mode : int
        Choice of K: 0 for the Hessian of the excited-state surface at the current centre (local harmonic), 1 for the
        Hessian at the excited-state minimum (d, delta), 2 for the Hessian of the excited-state surface at the origin,
        which is the initial-state minimum, and 3 for the initial-state Hessian R diag(omega_1^2, omega_2^2) R^T.
    time_step : float
        Time step dt > 0.
    n_steps : int
        Number of steps n_steps >= 0.

    Returns
    -------
    result : np.ndarray
        Array of shape (n_steps + 1, 2) whose row n is [Re C(t_n), Im C(t_n)].

    Raises
    ------
    ValueError
        If hessian_mode is not 0, 1, 2 or 3, if time_step <= 0, if n_steps < 0, or if omega_1 or omega_2 is not strictly
        positive.
    '''
    return result  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _surface_row(point, displacement: float, par: "np.ndarray"):
    """Surface row [V, grad, Hessian entries] at one point and the Hessian as a 2 x 2 matrix."""
    import numpy as np
    row = _oracle_excited_surface_derivatives(np.asarray([point], dtype=float), displacement, par)[0]
    return row, np.array([[row[3], row[4]], [row[4], row[5]]])


def _gaussian_series(displacement: float, surface_params: "np.ndarray", ground_params: "np.ndarray", hessian_mode: int, time_step: float, n_steps: int):
    """Centre q, momentum p, width matrices Q and P and phase S of psi_t = pi^(-1/2) det(Q)^(-1/2)
    exp(i[(1/2) x^T P Q^(-1) x + p^T x + S]) at every step, with det(Q)^(1/2) continued along the steps."""
    import numpy as np
    mode = int(hessian_mode)
    if mode not in (0, 1, 2, 3) or mode != hessian_mode:
        raise ValueError("hessian_mode must be 0, 1, 2 or 3")
    if not time_step > 0.0 or int(n_steps) < 0:
        raise ValueError("time_step must be positive and n_steps non-negative")
    w1, w2, theta = (float(v) for v in np.asarray(ground_params, dtype=float).ravel()[:3])
    if w1 <= 0.0 or w2 <= 0.0:
        raise ValueError("ground-state frequencies must be strictly positive")
    par = np.asarray(surface_params, dtype=float).ravel()
    c, s = np.cos(theta), np.sin(theta)
    rot = np.array([[c, -s], [s, c]])
    Q = rot @ np.diag([w1 ** -0.5, w2 ** -0.5]) + 0j
    P = 1j * (rot @ np.diag([w1 ** 0.5, w2 ** 0.5]))
    q = np.zeros(2)
    p = np.zeros(2)
    S = 0.0
    if mode == 1:
        fixed = _surface_row([displacement, par[4]], displacement, par)[1]
    elif mode == 2:
        fixed = _surface_row([0.0, 0.0], displacement, par)[1]
    elif mode == 3:
        fixed = rot @ np.diag([w1 * w1, w2 * w2]) @ rot.T
    else:
        fixed = None
    w_outer = 1.0 / (2.0 - 2.0 ** (1.0 / 3.0))
    w_inner = -(2.0 ** (1.0 / 3.0)) / (2.0 - 2.0 ** (1.0 / 3.0))
    n = int(n_steps)
    qs = np.empty((n + 1, 2))
    ps = np.empty((n + 1, 2))
    Qs = np.empty((n + 1, 2, 2), dtype=complex)
    Ps = np.empty((n + 1, 2, 2), dtype=complex)
    Ss = np.empty(n + 1)
    roots = np.empty(n + 1, dtype=complex)
    qs[0], ps[0], Qs[0], Ps[0], Ss[0] = q, p, Q, P, S
    roots[0] = np.sqrt(np.linalg.det(Q))
    for i in range(n):
        for w in (w_outer, w_inner, w_outer):
            h = w * time_step
            q = q + 0.5 * h * p
            Q = Q + 0.5 * h * P
            S += 0.25 * h * float(p @ p)
            row, local = _surface_row(q, displacement, par)
            K = local if fixed is None else fixed
            p = p - h * row[1:3]
            P = P - h * (K @ Q)
            S -= h * row[0]
            q = q + 0.5 * h * p
            Q = Q + 0.5 * h * P
            S += 0.25 * h * float(p @ p)
        qs[i + 1], ps[i + 1], Qs[i + 1], Ps[i + 1], Ss[i + 1] = q, p, Q, P, S
        r = np.sqrt(np.linalg.det(Q))
        roots[i + 1] = r if abs(r - roots[i]) <= abs(r + roots[i]) else -r
    return qs, ps, Qs, Ps, Ss, roots


def _oracle_thawed_gaussian_autocorrelation(displacement: float, surface_params: "np.ndarray", ground_params: "np.ndarray", hessian_mode: int, time_step: float, n_steps: int) -> "np.ndarray":
    """Reference implementation."""
    import numpy as np
    q, p, Q, P, S, roots = _gaussian_series(displacement, surface_params, ground_params, hessian_mode, time_step, n_steps)
    w1, w2, theta = (float(v) for v in np.asarray(ground_params, dtype=float).ravel()[:3])
    c, s = np.cos(theta), np.sin(theta)
    rot = np.array([[c, -s], [s, c]])
    A0 = 1j * (rot @ np.diag([w1, w2]) @ rot.T)
    norm0 = np.pi ** -0.5 * (w1 * w2) ** 0.25
    A = P @ np.linalg.inv(Q)
    M = -0.5j * (A - np.conj(A0)[None, :, :])
    b = 1j * (p - np.einsum("nij,nj->ni", A, q))
    const = 1j * (0.5 * np.einsum("ni,nij,nj->n", q, A, q) - np.einsum("ni,ni->n", p, q) + S)
    sqrt_det_m = np.prod(np.sqrt(np.linalg.eigvals(M)), axis=1)
    quad = np.einsum("ni,ni->n", b, np.linalg.solve(M, b[:, :, None])[:, :, 0])
    val = norm0 * np.pi ** 0.5 / (roots * sqrt_det_m) * np.exp(0.25 * quad + const)
    return np.column_stack([val.real, val.imag])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Normal: local harmonic propagation on the benchmark-like surface, where the width grows without bound ---
        {
            "setup": "import numpy as np\n"
                     "par = np.array([0.85, 0.02, 0.45, 0.3, 0.8])\n"
                     "gp = np.array([1.0, 0.5, np.deg2rad(20.0)])\n",
            "call": "thawed_gaussian_autocorrelation(2.2, par.copy(), gp.copy(), 0, 0.05, 400)",
            "gold_call": "_oracle_thawed_gaussian_autocorrelation(2.2, par.copy(), gp.copy(), 0, 0.05, 400)",
            "tol": 1e-8,
        },
        # --- Normal: reference Hessian at the excited-state minimum with a negative Duschinsky angle ---
        {
            "setup": "import numpy as np\n"
                     "par = np.array([1.1, 0.04, 0.6, -0.4, -0.5])\n"
                     "gp = np.array([0.8, 0.9, -0.6])\n",
            "call": "thawed_gaussian_autocorrelation(1.3, par.copy(), gp.copy(), 1, 0.04, 500)",
            "gold_call": "_oracle_thawed_gaussian_autocorrelation(1.3, par.copy(), gp.copy(), 1, 0.04, 500)",
            "tol": 1e-8,
        },
        # --- Edge: Franck-Condon reference Hessian that is indefinite, so the width spreads exponentially ---
        {
            "setup": "import numpy as np\n"
                     "par = np.array([0.7, 0.05, 0.3, -1.2, 2.0])\n"
                     "gp = np.array([1.2, 0.45, 0.9])\n",
            "call": "thawed_gaussian_autocorrelation(-4.0, par.copy(), gp.copy(), 2, 0.05, 160)",
            "gold_call": "_oracle_thawed_gaussian_autocorrelation(-4.0, par.copy(), gp.copy(), 2, 0.05, 160)",
            "tol": 1e-8,
        },
        # --- Edge: stiff initial-state Hessian and long propagation, over which the width matrix rotates many times ---
        {
            "setup": "import numpy as np\n"
                     "par = np.array([0.95, 0.025, 0.4, 0.55, -0.6])\n"
                     "gp = np.array([2.6, 1.9, 1.1])\n",
            "call": "thawed_gaussian_autocorrelation(1.1, par.copy(), gp.copy(), 3, 0.02, 1500)",
            "gold_call": "_oracle_thawed_gaussian_autocorrelation(1.1, par.copy(), gp.copy(), 3, 0.02, 1500)",
            "tol": 1e-8,
        },
        # --- Normal: vertical reference Hessian on a strongly anharmonic stretch with a stiff bend, long times ---
        {
            "setup": "import numpy as np\n"
                     "par = np.array([1.6, 0.03, 1.2, 0.25, 0.5])\n"
                     "gp = np.array([1.4, 1.5, -0.3])\n",
            "call": "thawed_gaussian_autocorrelation(1.7, par.copy(), gp.copy(), 2, 0.025, 1200)",
            "gold_call": "_oracle_thawed_gaussian_autocorrelation(1.7, par.copy(), gp.copy(), 2, 0.025, 1200)",
            "tol": 1e-8,
        },
        # --- Boundary: zero steps returns only C(0) = 1 ---
        {
            "setup": "import numpy as np\n"
                     "par = np.array([0.85, 0.02, 0.45, 0.3, 0.8])\n"
                     "gp = np.array([1.7, 0.25, -1.4])\n",
            "call": "thawed_gaussian_autocorrelation(2.0, par.copy(), gp.copy(), 2, 0.1, 0)",
            "gold_call": "_oracle_thawed_gaussian_autocorrelation(2.0, par.copy(), gp.copy(), 2, 0.1, 0)",
            "tol": 1e-12,
        },
        # --- Error: an unknown Hessian mode must raise ValueError ---
        {
            "setup": "import numpy as np\n"
                     "def _probe(fn):\n"
                     "    try:\n"
                     "        fn(1.0, np.array([0.85, 0.02, 0.45, 0.3, 0.8]), np.array([1.0, 0.5, 0.2]), 4, 0.1, 5)\n"
                     "    except ValueError:\n"
                     "        return 1\n"
                     "    except Exception:\n"
                     "        return 2\n"
                     "    return 0\n",
            "call": "_probe(thawed_gaussian_autocorrelation)",
            "gold_call": "_probe(_oracle_thawed_gaussian_autocorrelation)",
        },
    ]
