"""
Build a scale-certified trajectory generated by the selected RCGLS transition.

Equivalent scalings of a coordinate sketch can change internal RCGLS coefficients without changing the underlying iterate and residual trajectory. This stage examines that trajectory-level consistency while preserving the conditioned coordinate stream used by the method.

Returns
-------
tuple[np.ndarray,np.ndarray,np.ndarray,np.ndarray,np.ndarray,np.ndarray,np.ndarray], float64 histories for canonical squared residuals, canonical RCGLS step coefficients, canonical conjugacy coefficients, rescaled RCGLS step coefficients, rescaled conjugacy coefficients, iterate-equivalence defects, and residual-equivalence defects.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np

def rcgls_residual_history(
    A: np.ndarray,
    b: np.ndarray,
    x0: np.ndarray,
    indices: tuple[int, ...] | list[int],
    scale_factors: tuple[float, ...] | list[float] | np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Build a scale-certified trajectory generated by the selected RCGLS transition.

    Parameters
    ----------
    A : np.ndarray
        Finite real matrix with shape ``(n, d)``.
    b : np.ndarray
        Finite real vector with shape ``(n,)``.
    x0 : np.ndarray
        Finite real initial iterate with shape ``(d,)``.
    indices : tuple[int, ...] or list[int]
        Nonempty one-based conditioned coordinate stream.
    scale_factors : tuple[float, ...], list[float], or np.ndarray
        Finite nonzero sketch-rescaling factors, one per conditioned update.

    Returns
    -------
    residual_sq : np.ndarray
        Squared residual after each canonical RCGLS update, shape ``(m,)``.
    mu_values : np.ndarray
        Canonical RCGLS step coefficients, shape ``(m,)``.
    tau_values : np.ndarray
        Canonical conjugacy coefficients after the first update, shape ``(m-1,)``.
    scaled_mu_values : np.ndarray
        RCGLS step coefficients for the rescaled sketch stream, shape ``(m,)``.
    scaled_tau_values : np.ndarray
        Conjugacy coefficients for the rescaled sketch stream, shape ``(m-1,)``.
    iterate_defects : np.ndarray
        Euclidean differences between canonical and rescaled iterates after each update, shape ``(m,)``.
    residual_defects : np.ndarray
        Euclidean differences between canonical and rescaled residuals after each update, shape ``(m,)``.

    Raises
    ------
    ValueError
        If inputs, indices, or scale factors are invalid, a required sketch is undefined,
        or either RCGLS trajectory breaks down or becomes nonfinite.
    """
    return residual_sq, mu_values, tau_values, scaled_mu_values, scaled_tau_values, iterate_defects, residual_defects

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np

def _oracle_rcgls_residual_history(A,b,x0,indices,scale_factors):
    """Reference implementation of canonical and equivalently rescaled fixed-stream RCGLS."""
    A64,b64,x_can=_oracle_prepare_least_squares_problem(A,b,x0)
    x_scaled=x_can.copy()
    if not isinstance(indices,(tuple,list)) or len(indices)<1: raise ValueError("indices must be nonempty tuple/list")
    d=A64.shape[1]; checked=[]
    for index in indices:
        if isinstance(index,(bool,np.bool_)) or not isinstance(index,(int,np.integer)): raise ValueError("indices must be integers")
        j=int(index)
        if j<1 or j>d: raise ValueError("coordinate out of range")
        checked.append(j)
    try:
        scales=np.asarray(scale_factors,dtype=np.float64)
    except (TypeError,ValueError) as exc:
        raise ValueError("scale_factors must be real numeric") from exc
    if scales.ndim!=1 or scales.shape!=(len(checked),): raise ValueError("scale_factors length mismatch")
    if not np.all(np.isfinite(scales)) or np.any(scales==0.0): raise ValueError("scale_factors must be finite and nonzero")

    r_can=b64-A64@x_can
    r_scaled=r_can.copy()
    S0=_oracle_normalized_coordinate_sketch(A64,checked[0]).reshape(d,1)
    Sc0=scales[0]*S0
    p_can,v_can=_oracle_rcgls_sketch_seed(A64,r_can,S0)
    p_scaled,v_scaled=_oracle_rcgls_sketch_seed(A64,r_scaled,Sc0)
    den_can=float(v_can@v_can); den_scaled=float(v_scaled@v_scaled)
    if den_can<=0.0 or den_scaled<=0.0 or not np.isfinite(den_can+den_scaled): raise ValueError("RCGLS breakdown")
    g_can=A64.T@r_can; g_scaled=A64.T@r_scaled
    d_can=S0.T@g_can; d_scaled=Sc0.T@g_scaled
    mu_can=float(d_can@d_can)/den_can; mu_scaled=float(d_scaled@d_scaled)/den_scaled
    if not np.isfinite(mu_can) or not np.isfinite(mu_scaled): raise ValueError("nonfinite mu")
    x_can=x_can+mu_can*p_can; r_can=r_can-mu_can*v_can
    x_scaled=x_scaled+mu_scaled*p_scaled; r_scaled=r_scaled-mu_scaled*v_scaled

    residual=[float(r_can@r_can)]; mus=[mu_can]; taus=[]; smus=[mu_scaled]; staus=[]
    idef=[float(np.linalg.norm(x_can-x_scaled))]; rdef=[float(np.linalg.norm(r_can-r_scaled))]
    if not np.all(np.isfinite([residual[0],idef[0],rdef[0]])): raise ValueError("nonfinite first update")

    for k in range(1,len(checked)):
        S=_oracle_normalized_coordinate_sketch(A64,checked[k]).reshape(d,1)
        Ss=scales[k]*S
        p_can,v_can,tau,mu_can,r_can,rs,_,_=_oracle_rcgls_conjugate_direction(A64,r_can,S,p_can,v_can)
        p_scaled,v_scaled,stau,mu_scaled,r_scaled,srs,_,_=_oracle_rcgls_conjugate_direction(A64,r_scaled,Ss,p_scaled,v_scaled)
        x_can=x_can+mu_can*p_can
        x_scaled=x_scaled+mu_scaled*p_scaled
        residual.append(rs); mus.append(mu_can); taus.append(tau); smus.append(mu_scaled); staus.append(stau)
        idef.append(float(np.linalg.norm(x_can-x_scaled))); rdef.append(float(np.linalg.norm(r_can-r_scaled)))
        if not np.isclose(rs,srs,rtol=5e-12,atol=5e-12): raise ValueError("equivalent sketch scaling changed residual history")
    arrays=(np.asarray(residual,dtype=np.float64),np.asarray(mus,dtype=np.float64),np.asarray(taus,dtype=np.float64),
            np.asarray(smus,dtype=np.float64),np.asarray(staus,dtype=np.float64),np.asarray(idef,dtype=np.float64),np.asarray(rdef,dtype=np.float64))
    if any(not np.all(np.isfinite(a)) for a in arrays): raise ValueError("nonfinite history")
    return arrays

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {'setup':"""import numpy as np
A=np.array([[2.,0.,1.],[1.,3.,0.],[0.,1.,2.],[1.,-1.,1.]])
b=np.array([1.,2.,-1.,.5]); x0=np.zeros(3); indices=[1,3,2]; scales=[2.0,0.5,3.0]""",'call':'rcgls_residual_history(A,b,x0,indices,scales)','gold_call':'_oracle_rcgls_residual_history(A,b,x0,indices,scales)'},
        {'setup':"""import numpy as np
A=np.array([[2.,1.],[0.,3.],[1.,-1.]])
b=np.array([1.,-2.,.5]); x0=np.array([.2,-.1]); indices=[2]; scales=[-4.0]""",'call':'rcgls_residual_history(A,b,x0,indices,scales)','gold_call':'_oracle_rcgls_residual_history(A,b,x0,indices,scales)'},
        {'setup':"""import numpy as np
A=np.array([[-.98912135,-.36778665,1.28792526,.19397442],[.92023090,.57710379,-.63646365,.54195222],[-.31659545,-.32238912,.09716732,-1.52593041],[1.19216610,-.67108968,1.00026942,.13632112],[1.53203308,-.65996941,-.31179486,.33776913],[-2.20747110,.82792144,1.54163039,1.12680679],[.75476964,-.14597789,1.28190223,1.07403062],[.39262084,.00511431,-.36176687,-1.23023220]])
b=np.array([1.22622929,-2.17204389,-.37014735,.16438007,.85988118,1.76166124,.99332378,-.29152143]); x0=np.zeros(4); indices=[3,1,2,3,4,1]; scales=[2.0,0.5,4.0,0.25,8.0,0.125]""",'call':'rcgls_residual_history(A,b,x0,indices,scales)','gold_call':'_oracle_rcgls_residual_history(A,b,x0,indices,scales)'},
        {'setup':"""import numpy as np
A=np.eye(2); b=np.ones(2); x0=np.zeros(2); indices=[]; scales=[]
def run_model():
    try: rcgls_residual_history(A,b,x0,indices,scales); return 0
    except ValueError: return 1
    except Exception: return 2
def run_gold():
    try: _oracle_rcgls_residual_history(A,b,x0,indices,scales); return 0
    except ValueError: return 1
    except Exception: return 2""",'call':'run_model()','gold_call':'run_gold()'},
        {'setup':"""import numpy as np
A=np.eye(2); b=np.ones(2); x0=np.zeros(2); indices=[1,2]; scales=[1.0,0.0]
def run_model():
    try: rcgls_residual_history(A,b,x0,indices,scales); return 0
    except ValueError: return 1
    except Exception: return 2
def run_gold():
    try: _oracle_rcgls_residual_history(A,b,x0,indices,scales); return 0
    except ValueError: return 1
    except Exception: return 2""",'call':'run_model()','gold_call':'run_gold()'},
        {'setup':"""import numpy as np
A=np.eye(2); b=np.ones(2); x0=np.zeros(2); indices=[1,2]; scales=[1.0]
def run_model():
    try: rcgls_residual_history(A,b,x0,indices,scales); return 0
    except ValueError: return 1
    except Exception: return 2
def run_gold():
    try: _oracle_rcgls_residual_history(A,b,x0,indices,scales); return 0
    except ValueError: return 1
    except Exception: return 2""",'call':'run_model()','gold_call':'run_gold()'},
    ]
