"""
Compute the complete numerical solution over the prescribed space-time mesh using the implicit structure-preserving discretization defined by the reference work.



The calculation must begin from the regularized initial state, repeatedly construct the appropriate implicit update, solve the resulting interior system, and enforce the required spatial boundary values at every time level. The returned object must represent the complete numerical solution rather than only the terminal state or interior unknowns.



This stage must be implemented through the preceding computational components rather than by substituting an unrelated numerical method.

The transformed option-pricing problem is evolved forward in computational time after the original terminal-value formulation has been rewritten as an initial-boundary-value problem. The reference method uses an implicit nonstandard discretization designed to preserve important qualitative properties of the continuous problem.



Because each time level depends on the solution being computed at that level, the numerical evolution requires repeated structured linear solves together with consistent treatment of the spatial boundaries.

Returns
-------
Returns a two-dimensional NumPy array containing the numerical solution on the complete space-time mesh, with dimensions corresponding to the prescribed spatial and temporal discretizations.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def solve_nsfd_surface(initial: "np.ndarray", coefficients: "np.ndarray", r: float, T: float, K: float, S_max: float, M: int, N: int) -> "np.ndarray":
    """Return the complete numerical surface generated by the reference implicit formulation.

    Parameters
    ----------
    initial : numpy.ndarray
        Regularized payoff table with shape `(M+1, 2)`; its second column contains the initial values.
    coefficients : numpy.ndarray
        Coefficient table with shape `(M-1, 4)` supplied by the coefficient stage.
    r, T, K, S_max : float
        Positive model and domain parameters.
    M : int
        Number of spatial intervals; must be at least 2.
    N : int
        Number of time intervals; must be at least 1.

    Returns
    -------
    numpy.ndarray
        Float64 surface of shape `(N+1, M+1)`.

    Raises
    ------
    ValueError
        If input shapes or scalar requirements are violated.
    
    Notes
    -----
    The initial row is the supplied regularized state; subsequent rows are generated from the supplied coefficient data.
    """
    return None

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_solve_nsfd_surface(initial: "np.ndarray", coefficients: "np.ndarray", r: float, T: float, K: float, S_max: float, M: int, N: int) -> "np.ndarray":
    import numpy as np
    from scipy.linalg import solve_banded
    initial=np.asarray(initial,dtype=np.float64); coefficients=np.asarray(coefficients,dtype=np.float64)
    if not (isinstance(M,(int,np.integer)) and int(M)>=2): raise ValueError("M must be an integer >= 2")
    if not (isinstance(N,(int,np.integer)) and int(N)>=1): raise ValueError("N must be an integer >= 1")
    M=int(M); N=int(N)
    if initial.shape!=(M+1,2): raise ValueError("initial must have shape (M+1,2)")
    if coefficients.shape!=(M-1,4): raise ValueError("coefficients must have shape (M-1,4)")
    if not (r>0 and T>0 and K>0 and S_max>K): raise ValueError("invalid physical or domain parameters")
    dt=T/N
    solution=np.empty((N+1,M+1),dtype=np.float64); solution[0]=initial[:,1]
    for k in range(1,N+1):
        t=k*dt
        system=_oracle_assemble_nsfd_timestep(solution[k-1],coefficients,S_max,K,r,t,M)
        n=M-1; banded=np.zeros((3,n),dtype=np.float64); banded[0,1:]=system[:-1,2]; banded[1,:]=system[:,1]; banded[2,:-1]=system[:-1,0]
        interior=solve_banded((1,1),banded,system[:,3])
        solution[k,0]=0.0; solution[k,M]=S_max-K*np.exp(-r*t); solution[k,1:M]=interior
    return solution

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {
            "setup": """import numpy as np
K=1.2
S_max=8.4
epsilon=0.07
M=21
N=25
r=0.035
sigma=0.35
T=1.1
initial=_oracle_build_smoothed_payoff(K,S_max,epsilon,M)
coefficients=_oracle_compute_nsfd_coefficients(r,sigma,T,S_max,M,N)""",
            "call": "solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)",
            "gold_call": "_oracle_solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)"
        },
        {
            "setup": """import numpy as np
K=1.0
S_max=2.0
epsilon=0.25
M=2
N=1
r=0.04
sigma=0.4
T=1.0
initial=_oracle_build_smoothed_payoff(K,S_max,epsilon,M)
coefficients=_oracle_compute_nsfd_coefficients(r,sigma,T,S_max,M,N)""",
            "call": "solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)",
            "gold_call": "_oracle_solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)"
        },
        {
            "setup": """import numpy as np
K=0.8
S_max=4.0
epsilon=0.1
M=7
N=9
r=0.02
sigma=0.25
T=0.5
initial=_oracle_build_smoothed_payoff(K,S_max,epsilon,M)
coefficients=_oracle_compute_nsfd_coefficients(r,sigma,T,S_max,M,N)""",
            "call": "solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)",
            "gold_call": "_oracle_solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)"
        },
        {
            "setup": """import numpy as np
K=1.1
S_max=6.0
epsilon=0.12
M=6
N=6
r=0.05
sigma=0.30
T=0.6
initial=_oracle_build_smoothed_payoff(K,S_max,epsilon,M)
coefficients=_oracle_compute_nsfd_coefficients(r,sigma,T,S_max,M,N)""",
            "call": "solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)",
            "gold_call": "_oracle_solve_nsfd_surface(initial.copy(),coefficients.copy(),r,T,K,S_max,M,N)"
        }
    ]
