"""
Correlation self-energy generated by the partner's charge fluctuations

The two molecules exchange no electrons, so the only way one can influence the other is by having

its charge fluctuate. At leading non-vanishing order in the intermolecular coupling, an electron

propagating on one molecule is dressed by a single charge fluctuation borrowed from the partner

and returned to it, which costs two powers of the coupling constant. The resulting correlation

self-energy therefore carries the Green's function of the molecule it acts on and the

fluctuation propagator of the other molecule, combined over frequency so that the energy carried

by the electron and the energy carried by the fluctuation add up to the frequency at which the

self-energy is evaluated. Note carefully which molecule supplies which factor: the self-energy of

a molecule is built from its own Green's function and its partner's propagator, never from its own

propagator.



The lesser and greater components are formed from the corresponding components of the two inputs,

component by component; there is no mixing between them at this order. As with the propagators of

step 04, one component is pure imaginary with a non-negative imaginary part and the other pure

imaginary with a non-positive one, and preserving that structure exactly rather than to within

round-off keeps the self-consistency of step 07 from drifting.



The frequency combination here is a convolution rather than the correlation of step 04: the two

arguments add to the output frequency instead of differing by it. Getting these two the wrong way

round is a common and silent error, because both produce arrays of the right shape and roughly

the right magnitude.

Returns
-------
#     np.ndarray of shape (2, n), complex: lesser then greater correlation self-energy, in eV  # ============================================================================
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def correlation_selfenergies(g_lesser: np.ndarray, g_greater: np.ndarray, pi_lesser: np.ndarray,
                             pi_greater: np.ndarray, u_coupling: float, dw: float) -> np.ndarray:
    '''Lesser and greater correlation self-energies of one molecule.

    Parameters
    ----------
    g_lesser, g_greater : np.ndarray
        Lesser and greater Green's functions of the molecule being dressed, in eV^-1.
    pi_lesser, pi_greater : np.ndarray
        Lesser and greater charge-fluctuation propagators of the PARTNER molecule, in eV^-1.
    u_coupling : float
        Intermolecular density-density coupling U in eV; non-negative.
    dw : float
        Grid spacing in eV; positive.

    Returns
    -------
    result : np.ndarray
        Complex array of shape (2, n): row 0 the lesser correlation self-energy and row 1 the
        greater, both in eV.

    Raises
    ------
    ValueError
        If dw is not positive, if u_coupling is negative, or if the four input arrays do not all
        have the same length.
    '''
    return result  # placeholder

# ============================================================================

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _fft_linear_convolve(a, b):
    m = len(a) + len(b) - 1
    size = 1
    while size < m:
        size *= 2
    return np.fft.ifft(np.fft.fft(a, size) * np.fft.fft(b, size))[:m]


def _shifted_convolution(a, b, dw):
    """(1/2pi) * int dw' a(w') b(w - w'), as an exact index shift on this grid."""
    n = len(a)
    half = n // 2
    full = _fft_linear_convolve(np.asarray(a, dtype=complex), np.asarray(b, dtype=complex))
    return full[np.arange(n) + half] * dw / (2.0 * np.pi)


def _oracle_correlation_selfenergies(g_lesser, g_greater, pi_lesser, pi_greater, u_coupling, dw):
    if not (dw > 0.0):
        raise ValueError("dw must be positive")
    if u_coupling < 0.0:
        raise ValueError("u_coupling must be non-negative")
    arrs = [np.asarray(a, dtype=complex) for a in (g_lesser, g_greater, pi_lesser, pi_greater)]
    if len({a.shape[-1] for a in arrs}) != 1:
        raise ValueError("all input arrays must have the same length")
    gl, gg, pl, pg = arrs
    s_lesser = 1j * u_coupling ** 2 * _shifted_convolution(gl, pl, dw)
    s_greater = 1j * u_coupling ** 2 * _shifted_convolution(gg, pg, dw)
    return np.vstack([1j * s_lesser.imag, 1j * s_greater.imag])

# ============================================================================

# =============================================================================
# TEST CASES
# =============================================================================

_SETUP = ("import numpy as np\n"
          "_KB = 8.617333262e-5\n"
          "_n = 1024\n"
          "_dw = 20.0 / _n\n"
          "_w = (np.arange(_n) - _n // 2) * _dw\n"
          "def _fc(a, b):\n"
          "    m = len(a) + len(b) - 1\n"
          "    s = 1\n"
          "    while s < m: s *= 2\n"
          "    return np.fft.ifft(np.fft.fft(a, s) * np.fft.fft(b, s))[:m]\n"
          "def _corr(a, b):\n"
          "    h = _n // 2\n"
          "    return _fc(np.asarray(a, complex), np.asarray(b, complex)[::-1])[np.arange(_n) + (_n - 1 - h)] * _dw / (2 * np.pi)\n"
          "def _greens(eps, gam, V, T, gl, gr, fr):\n"
          "    mu_l = fr * V\n"
          "    mu_r = -(1.0 - fr) * V\n"
          "    f1 = 0.5 * (1.0 - np.tanh(np.clip((_w - mu_l) / (2.0 * _KB * T), -400, 400)))\n"
          "    f2 = 0.5 * (1.0 - np.tanh(np.clip((_w - mu_r) / (2.0 * _KB * T), -400, 400)))\n"
          "    sl = 1j * (gl * f1 + gr * f2)\n"
          "    sg = -1j * (gl * (1 - f1) + gr * (1 - f2))\n"
          "    gret = 1.0 / (_w - eps + 0.5j * gam)\n"
          "    return gret * sl * np.conj(gret), gret * sg * np.conj(gret)\n"
          "def _bub(gl, gg):\n"
          "    return -1j * _corr(gl, gg), -1j * _corr(gg, gl)\n"
          "_GL, _GG = _greens(-0.7800536, 0.080, 2.0, 300.0, 0.050, 0.030, 0.70)\n"
          "_PL, _PG = _bub(_GL, _GG)\n"
          "_QL, _QG = _bub(*_greens(-0.50, 0.050, 0.0, 300.0, 0.025, 0.025, 0.5))")


def test_cases():
    """Return list of test case specifications."""
    return [
        {
            "setup": _SETUP,
            "call": 'correlation_selfenergies(_GL, _GG, _PL, _PG, 0.90, _dw)',
            "gold_call": '_oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, 0.90, _dw)',
            "note": 'normal, the operating point of the task with identical partners',
        },
        {
            "setup": _SETUP,
            "call": 'correlation_selfenergies(_GL, _GG, _QL, _QG, 0.75, _dw)',
            "gold_call": '_oracle_correlation_selfenergies(_GL, _GG, _QL, _QG, 0.75, _dw)',
            "note": 'normal, a driven molecule dressed by an unbiased partner',
        },
        {
            "setup": _SETUP,
            "call": 'correlation_selfenergies(_GL, _GG, _PL, _PG, 0.0, _dw)',
            "gold_call": '_oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, 0.0, _dw)',
            "note": 'boundary, zero coupling must switch the correlation self-energy off entirely',
        },
        {
            "setup": _SETUP,
            "call": ('np.array([np.abs(correlation_selfenergies(_GL, _GG, _PL, _PG, 0.90, _dw).real).max()])'),
            "gold_call": ('np.array([np.abs(_oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, 0.90, _dw).real).max()])'),
            "note": 'contract, both components must be pure imaginary',
        },
        {
            "setup": _SETUP,
            "call": ('np.array([float(correlation_selfenergies(_GL, _GG, _PL, _PG, 2.00, _dw)[0].imag.sum()'
                     ' / correlation_selfenergies(_GL, _GG, _PL, _PG, 0.90, _dw)[0].imag.sum())])'),
            "gold_call": ('np.array([float(_oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, 2.00, _dw)[0].imag.sum()'
                          ' / _oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, 0.90, _dw)[0].imag.sum())])'),
            "note": 'contract, the self-energy must scale as the square of the coupling',
        },
        {
            "setup": _SETUP,
            "call": 'correlation_selfenergies(*_greens(-1.20, 0.200, 3.5, 450.0, 0.120, 0.080, 0.35), _QL, _QG, 1.40, _dw)',
            "gold_call": '_oracle_correlation_selfenergies(*_greens(-1.20, 0.200, 3.5, 450.0, 0.120, 0.080, 0.35), _QL, _QG, 1.40, _dw)',
            "note": 'normal, a broad strongly driven level dressed at large coupling',
        },
        {
            "setup": _SETUP + '\ndef _raises(fn):\n    try:\n        fn()\n    except ValueError:\n        return 1.0\n    return 0.0\n',
            "call": ('np.array([_raises(lambda: correlation_selfenergies(_GL, _GG, _PL, _PG, 1.0, 0.0)),'
                     ' _raises(lambda: correlation_selfenergies(_GL, _GG, _PL, _PG, -1.0, _dw)),'
                     ' _raises(lambda: correlation_selfenergies(_GL[:10], _GG, _PL, _PG, 1.0, _dw))])'),
            "gold_call": ('np.array([_raises(lambda: _oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, 1.0, 0.0)),'
                          ' _raises(lambda: _oracle_correlation_selfenergies(_GL, _GG, _PL, _PG, -1.0, _dw)),'
                          ' _raises(lambda: _oracle_correlation_selfenergies(_GL[:10], _GG, _PL, _PG, 1.0, _dw))])'),
            "note": 'contract, bad spacing, negative coupling and mismatched lengths must raise ValueError',
        },
    ]
