"""
Compute the total reduced Hamiltonian H = H_N + eps*H_1PN + eps^2*H_2PN for a single phase-space point. This is used for the initial and final energies and for the final relative error.

In ADM coordinates the conservative two-body dynamics through 2PN is generated by H_N = P^2/2 - 1/r plus the 1PN and 2PN corrections. These contain P^2, (N.P)^2 and powers of 1/r, with eta-dependent coefficients. The dependence on (N.P) makes H non-separable, which is why a special splitting is needed.

Returns
-------
float: value of the Hamiltonian H(P, Q).
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def pn_hamiltonian(P, Q, eta, eps):
    """Total non-spinning 2PN ADM Hamiltonian H = H_N + eps*H_1PN + eps**2*H_2PN.

    P, Q : 1-D arrays (length 2 or 3), reduced canonical momentum and relative position.
    eta  : symmetric mass ratio, 0 < eta <= 0.25.
    eps  : post-Newtonian parameter 1/c**2, eps >= 0.
    Returns the Hamiltonian value as a float.
    Raises ValueError for |Q| = 0, mismatched shapes, eta outside (0, 0.25] or eps < 0.
    """
    return 0.0

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_pn_hamiltonian(P, Q, eta, eps):
    # Oracle: non-spinning ADM Hamiltonian through 2PN in reduced variables (G = M = 1).
    P = np.asarray(P, dtype=float).ravel()
    Q = np.asarray(Q, dtype=float).ravel()
    if P.shape != Q.shape or P.size not in (2, 3):
        raise ValueError("P and Q must be 1-D arrays of equal length 2 or 3")
    if not (0.0 < eta <= 0.25):
        raise ValueError("eta must satisfy 0 < eta <= 0.25")
    if eps < 0.0:
        raise ValueError("eps must be non-negative")
    r = float(np.sqrt(Q @ Q))
    if r == 0.0:
        raise ValueError("separation |Q| must be positive")
    p2 = float(P @ P)
    s = float(Q @ P) / r
    H_N = 0.5 * p2 - 1.0 / r
    H_1 = ((3.0 * eta - 1.0) / 8.0 * p2 ** 2
           - 0.5 * ((3.0 + eta) * p2 + eta * s ** 2) / r
           + 0.5 / r ** 2)
    c1 = 5.0 - 20.0 * eta - 3.0 * eta ** 2
    H_2 = ((1.0 - 5.0 * eta + 5.0 * eta ** 2) / 16.0 * p2 ** 3
           + (c1 * p2 ** 2 - 2.0 * eta ** 2 * s ** 2 * p2 - 3.0 * eta ** 2 * s ** 4) / (8.0 * r)
           + 0.5 * ((5.0 + 8.0 * eta) * p2 + 3.0 * eta * s ** 2) / r ** 2
           - (1.0 + 3.0 * eta) / (4.0 * r ** 3))
    return float(H_N + eps * H_1 + eps ** 2 * H_2)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return independent numerical test specifications."""
    return [
        {
            "name": (
                "normal_task_initial_state"
            ),
            "setup": (
                "import numpy as np\n"
            ),
            "call": (
                "pn_hamiltonian(\n"
                "    np.array([0.0, 0.18]),\n"
                "    np.array([25.34, 0.0]),\n"
                "    0.1708984375,\n"
                "    0.6309573444801932,\n"
                ")\n"
            ),
            "gold_call": (
                "_oracle_pn_hamiltonian(\n"
                "    np.array([0.0, 0.18]),\n"
                "    np.array([25.34, 0.0]),\n"
                "    0.1708984375,\n"
                "    0.6309573444801932,\n"
                ")\n"
            ),
            "tol": 1e-12,
        },
        {
            "name": (
                "boundary_eps_zero_newtonian_limit"
            ),
            "setup": (
                "import numpy as np\n"
            ),
            "call": (
                "pn_hamiltonian(\n"
                "    np.array([0.1, 0.2]),\n"
                "    np.array([3.0, 4.0]),\n"
                "    0.25,\n"
                "    0.0,\n"
                ")\n"
            ),
            "gold_call": (
                "_oracle_pn_hamiltonian(\n"
                "    np.array([0.1, 0.2]),\n"
                "    np.array([3.0, 4.0]),\n"
                "    0.25,\n"
                "    0.0,\n"
                ")\n"
            ),
            "tol": 1e-12,
        },
        {
            "name": (
                "edge_3d_state_with_radial_momentum"
            ),
            "setup": (
                "import numpy as np\n"
            ),
            "call": (
                "pn_hamiltonian(\n"
                "    np.array([0.05, 0.21, -0.03]),\n"
                "    np.array([8.0, -3.0, 1.5]),\n"
                "    0.2,\n"
                "    0.3,\n"
                ")\n"
            ),
            "gold_call": (
                "_oracle_pn_hamiltonian(\n"
                "    np.array([0.05, 0.21, -0.03]),\n"
                "    np.array([8.0, -3.0, 1.5]),\n"
                "    0.2,\n"
                "    0.3,\n"
                ")\n"
            ),
            "tol": 1e-12,
        },
        {
            "name": (
                "invalid_zero_separation_raises_valueerror"
            ),
            "setup": (
                "import numpy as np\n"
                "\n"
                "\n"
                "def run_model():\n"
                "    try:\n"
                "        pn_hamiltonian(\n"
                "            np.array([0.0, 0.18]),\n"
                "            np.array([0.0, 0.0]),\n"
                "            0.1708984375,\n"
                "            0.6309573444801932,\n"
                "        )\n"
                "        return 0\n"
                "    except ValueError:\n"
                "        return 1\n"
                "    except Exception:\n"
                "        return 2\n"
                "\n"
                "\n"
                "def run_gold():\n"
                "    try:\n"
                "        _oracle_pn_hamiltonian(\n"
                "            np.array([0.0, 0.18]),\n"
                "            np.array([0.0, 0.0]),\n"
                "            0.1708984375,\n"
                "            0.6309573444801932,\n"
                "        )\n"
                "        return 0\n"
                "    except ValueError:\n"
                "        return 1\n"
                "    except Exception:\n"
                "        return 2\n"
            ),
            "call": (
                "run_model()\n"
            ),
            "gold_call": (
                "run_gold()\n"
            ),
            "tol": 0,
        },
    ]
