"""
Enumerate the elementary flux modes of a reaction network as primitive integer vectors.

Elementary flux modes are the support-minimal nonnegative steady-state flux vectors; they are the extreme rays of the flux cone and can be generated by double-description sweeps over the species balances.

Returns
-------
np.ndarray: primitive integer elementary flux modes, shape (p, r).
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np
def compute_elementary_flux_modes(
    source_complexes: np.ndarray, product_complexes: np.ndarray
) -> np.ndarray:
    """Return the elementary flux modes of an irreversible reaction network.

    Let ``N`` be the ``(m, r)`` stoichiometric matrix whose column ``k`` is
    ``product_complexes[k] - source_complexes[k]``. A flux mode is a nonzero
    vector ``v >= 0`` with ``N @ v = 0``; it is elementary when no other flux
    mode has a support (set of nonzero entries) strictly contained in its
    support. Every reaction is irreversible, so a reversible pair appears as
    two separate reactions.

    Parameters
    ----------
    source_complexes : np.ndarray
        Integer array with shape ``(r, m)``.
    product_complexes : np.ndarray
        Integer array with shape ``(r, m)``.

    Returns
    -------
    np.ndarray
        Integer array with shape ``(p, r)``, one elementary flux mode per
        row, each scaled to nonnegative integers whose greatest common divisor
        is 1. Rows are ordered by comparing the increasing tuples of the
        indices of their nonzero entries lexicographically. A network without
        flux modes gives shape ``(0, r)``.

    Raises
    ------
    ValueError
        If the two arrays are not two-dimensional with the same shape and at
        least one reaction, if any entry is negative, non-finite or not an
        integer, or if some reaction has identical source and product
        complexes.
    """
    return np.zeros((0, 0), dtype=int)

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
def _oracle_compute_elementary_flux_modes(
    source_complexes: np.ndarray, product_complexes: np.ndarray
) -> np.ndarray:
    """Reference implementation (canonical-basis double description)."""
    import numpy as np
    from math import gcd

    source = np.asarray(source_complexes, dtype=float)
    product = np.asarray(product_complexes, dtype=float)
    if source.ndim != 2 or source.shape != product.shape or source.shape[0] == 0:
        raise ValueError("complex arrays must share a two-dimensional (r, m) shape")
    for values in (source, product):
        if not np.all(np.isfinite(values)):
            raise ValueError("complex entries must be finite")
        if np.any(values < 0.0) or np.any(values != np.round(values)):
            raise ValueError("complex entries must be nonnegative integers")
    if np.any(np.all(product == source, axis=1)):
        raise ValueError("every reaction must change at least one species")
    stoich = (product - source).astype(np.int64).T
    reactions = stoich.shape[1]

    def primitive(vector):
        divisor = 0
        for value in vector:
            divisor = gcd(divisor, int(abs(value)))
        return vector // divisor

    rays = [np.eye(reactions, dtype=np.int64)[index] for index in range(reactions)]
    for row in stoich:
        values = [int(row @ ray) for ray in rays]
        supports = [frozenset(np.flatnonzero(ray).tolist()) for ray in rays]
        kept = [ray for ray, value in zip(rays, values) if value == 0]
        positive = [index for index, value in enumerate(values) if value > 0]
        negative = [index for index, value in enumerate(values) if value < 0]
        for plus in positive:
            for minus in negative:
                union = supports[plus] | supports[minus]
                # Combinatorial adjacency test: no third ray may have its
                # support inside the union of the two parent supports.
                adjacent = all(
                    not supports[other] <= union
                    for other in range(len(rays))
                    if other not in (plus, minus)
                )
                if adjacent:
                    combined = values[plus] * rays[minus] - values[minus] * rays[plus]
                    kept.append(primitive(combined))
        rays = kept

    unique = {}
    for ray in rays:
        unique[tuple(int(value) for value in ray)] = ray
    ordered = sorted(unique.values(), key=lambda ray: tuple(np.flatnonzero(ray).tolist()))
    if not ordered:
        return np.zeros((0, reactions), dtype=int)
    return np.array(ordered, dtype=int)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases() -> list[dict[str, str]]:
    """Return scalar-only test specifications."""
    builder = (
        "import numpy as np\n"
        "def _net(m, rx):\n"
        "    S = np.zeros((len(rx), m), dtype=int)\n"
        "    P = np.zeros((len(rx), m), dtype=int)\n"
        "    for r, (a, b) in enumerate(rx):\n"
        "        for i in a: S[r, i] += 1\n"
        "        for i in b: P[r, i] += 1\n"
        "    return S, P\n"
        "def _isig(a, shape):\n"
        "    a = np.asarray(a)\n"
        "    if a.shape != shape: return -1\n"
        "    f = a.ravel()\n"
        "    w = np.arange(1, f.size + 1)\n"
        "    return int(np.sum(f * w) + 3 * np.sum(f * f * (w % 5 + 1)))\n"
    )
    status = (
        "def _status(fn):\n"
        "    try:\n"
        "        fn()\n"
        "        return 0\n"
        "    except ValueError:\n"
        "        return 1\n"
        "    except Exception:\n"
        "        return 2\n"
    )
    dual = (
        "S, P = _net(8, [([0], [1]), ([1, 2], [0, 3]), ([4, 3], [6]), ([6], [4, 3]),"
        " ([6], [4, 2]), ([5, 3], [7]), ([7], [5, 3]), ([7], [5, 2]),"
        " ([4], [5]), ([5], [4])])\n"
    )
    triangle = (
        "S, P = _net(3, [([0], [1]), ([1], [0]), ([1], [2]), ([2], [1]),"
        " ([2], [0]), ([0], [2])])\n"
    )
    return [
        {
            "setup": builder + dual,
            "call": "_isig(compute_elementary_flux_modes(S, P), (5, 10))",
            "gold_call": "_isig(_oracle_compute_elementary_flux_modes(S, P), (5, 10))",
        },
        {
            "setup": builder + "S, P = _net(3, [([0, 1], [2, 1]), ([0], [1]), ([1], [0]), ([2], []), ([], [0])])\n",
            "call": "_isig(compute_elementary_flux_modes(S, P), (2, 5))",
            "gold_call": "_isig([[1, 0, 0, 1, 1], [0, 1, 1, 0, 0]], (2, 5))",
        },
        {
            "setup": builder + "S, P = _net(4, [([0], [1]), ([1, 2], [0, 3]), ([0, 3], [1, 2]), ([3], [2])])\n",
            "call": "_isig(compute_elementary_flux_modes(S, P), (2, 4))",
            "gold_call": "_isig(_oracle_compute_elementary_flux_modes(S, P), (2, 4))",
        },
        {
            "setup": builder + triangle,
            "call": "_isig(compute_elementary_flux_modes(S, P), (5, 6))",
            "gold_call": "_isig(_oracle_compute_elementary_flux_modes(S, P), (5, 6))",
        },
        {
            "setup": builder + "S, P = _net(3, [([0], [1]), ([1], [2]), ([2, 2], [0, 0])])\n",
            "call": "_isig(compute_elementary_flux_modes(S, P), (1, 3))",
            "gold_call": "_isig(_oracle_compute_elementary_flux_modes(S, P), (1, 3))",
        },
        {
            "setup": builder + (
                "S, P = _net(4, [([0], [1]), ([1], [2]), ([2], [0]), ([1, 1], [3]),"
                " ([3], [2, 2]), ([2], [1])])\n"
            ),
            "call": "_isig(compute_elementary_flux_modes(S, P), (4, 6))",
            "gold_call": "_isig([[1, 1, 1, 0, 0, 0], [2, 0, 2, 1, 1, 0], [0, 1, 0, 0, 0, 1], [0, 0, 0, 1, 1, 2]], (4, 6))",
        },
        {
            "setup": builder + "S, P = _net(3, [([0], [1]), ([1], [2])])\n",
            "call": "_isig(compute_elementary_flux_modes(S, P), (0, 2))",
            "gold_call": "_isig(_oracle_compute_elementary_flux_modes(S, P), (0, 2))",
        },
        {
            "setup": builder + status + "S = np.array([[1, 0], [0, 1]]); P = np.array([[0, 1], [1, -1]])\n",
            "call": "_status(lambda: compute_elementary_flux_modes(S, P))",
            "gold_call": "_status(lambda: _oracle_compute_elementary_flux_modes(S, P))",
        },
    ]
