"""
Compute the opposite-spin diffusion block generated by onsite interactions.

For the onsite Fermi–Hubbard interaction, equal-spin diffusion blocks vanish and the nonzero tensor couples spin-up and spin-down phase-space variables. The required contraction combines particle and hole matrices over an intermediate site while preserving the ordered pair indexing of the one-body variables. Use the explicit onsite diffusion tensor displayed in Appendix A, Eq. (A5), with its stated index orientation.

Returns
-------
np.ndarray, the complex opposite-spin diffusion block with shape (n_sites**2, n_sites**2) in row-major pair ordering
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def compute_opposite_spin_diffusion(
    n_up: "np.ndarray",
    n_down: "np.ndarray",
    interaction: float,
) -> "np.ndarray":
    """Compute the spin-up to spin-down diffusion block.

    Parameters
    ----------
    n_up : np.ndarray
        Finite complex square spin-up phase-space matrix.
    n_down : np.ndarray
        Finite complex square spin-down phase-space matrix with the same shape.
    interaction : float
        Finite real onsite interaction strength.

    Returns
    -------
    diffusion_block : np.ndarray
        Complex array with shape ``(n_sites**2, n_sites**2)``. Row and column
        pair indices use row-major ordering ``i * n_sites + j``.

    Raises
    ------
    ValueError
        If the spin matrices are incompatible or non-finite, or if ``interaction``
        is not a finite real scalar.
    """
    return diffusion_block

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import math
from numbers import Real

import numpy as np


def _oracle_compute_opposite_spin_diffusion(
    n_up: "np.ndarray",
    n_down: "np.ndarray",
    interaction: float,
) -> "np.ndarray":
    """Reference implementation."""
    up = np.asarray(n_up, dtype=complex)
    down = np.asarray(n_down, dtype=complex)
    if (
        up.ndim != 2
        or up.shape[0] != up.shape[1]
        or up.shape[0] < 1
        or down.shape != up.shape
        or not np.all(np.isfinite(up))
        or not np.all(np.isfinite(down))
    ):
        raise ValueError("n_up and n_down must be finite compatible square arrays")
    if isinstance(interaction, bool) or not isinstance(interaction, Real):
        raise ValueError("interaction must be a finite real scalar")
    interaction_value = float(interaction)
    if not math.isfinite(interaction_value):
        raise ValueError("interaction must be a finite real scalar")

    n_sites = up.shape[0]
    hole_up = np.eye(n_sites, dtype=complex) - up
    hole_down = np.eye(n_sites, dtype=complex) - down
    block = np.zeros((n_sites * n_sites, n_sites * n_sites), dtype=complex)
    for i in range(n_sites):
        for j in range(n_sites):
            row = i * n_sites + j
            for k in range(n_sites):
                for ell in range(n_sites):
                    column = k * n_sites + ell
                    contraction = 0.0j
                    for a in range(n_sites):
                        contraction += (
                            hole_up[a, j]
                            * up[i, a]
                            * hole_down[a, ell]
                            * down[k, a]
                            - up[a, j]
                            * hole_up[i, a]
                            * down[a, ell]
                            * hole_down[k, a]
                        )
                    block[row, column] = 1j * interaction_value * contraction
    return block

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return deterministic test specifications."""
    return [
        {
            "setup": """import numpy as np
n_up = np.array([
    [0.82 + 0.00j, 0.12 + 0.05j, -0.04 + 0.02j],
    [0.12 - 0.05j, 0.47 + 0.00j, 0.09 - 0.03j],
    [-0.04 - 0.02j, 0.09 + 0.03j, 0.21 + 0.00j],
], dtype=complex)
n_down = np.array([
    [0.18 + 0.00j, -0.07 + 0.02j, 0.05 - 0.01j],
    [-0.07 - 0.02j, 0.53 + 0.00j, -0.11 + 0.04j],
    [0.05 + 0.01j, -0.11 - 0.04j, 0.79 + 0.00j],
], dtype=complex)
hopping = np.array([
    [0.0, 1.0, 0.35],
    [1.0, 0.0, 0.8],
    [0.35, 0.8, 0.0],
], dtype=float)
interaction = 1.3
""",
            "call": "compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), interaction)",
            "gold_call": "_oracle_compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), interaction)",
        },
        {
            "setup": """import numpy as np
n_up = np.array([[0.8, 0.1j], [-0.2j, 0.2]], dtype=complex)
n_down = np.array([[0.3, -0.05 + 0.02j], [0.07 + 0.01j, 0.7]], dtype=complex)
interaction = 0.0
""",
            "call": "compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), interaction)",
            "gold_call": "_oracle_compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), interaction)",
        },
        {
            "setup": """import numpy as np
n_up = np.array([[0.99 + 0.01j, 1.0e-5 - 2.0e-5j], [0.03 + 0.04j, 0.02 - 0.01j]], dtype=complex)
n_down = np.array([[0.04 - 0.03j, -0.02 + 0.01j], [3.0e-5 + 1.0e-5j, 0.96 + 0.02j]], dtype=complex)
interaction = -2.4
""",
            "call": "compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), interaction)",
            "gold_call": "_oracle_compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), interaction)",
        },
        {
            "setup": """import numpy as np
n_up = np.eye(2, dtype=complex)
n_down = np.eye(3, dtype=complex)
def run_model():
    try:
        compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_opposite_spin_diffusion(n_up.copy(), n_down.copy(), 1.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
