"""
Build the table of contracted atomic orbitals for a diatomic molecule. SPECIFICATION: symbols names the two atoms. basis_data maps an element symbol to a list of shells; each shell is a tuple whose first entry is the angular momentum, 0 for s and 1 for p, whose second entry is a list of exactly three Gaussian exponents and whose third entry is a list of exactly three contraction coefficients. Orbitals are generated by walking the two atoms in the order given and, within each atom, its shells in the order given; an s shell contributes one orbital with cartesian powers (0, 0, 0) and a p shell contributes three, with powers (1, 0, 0), (0, 1, 0) and (0, 0, 1) in that order. For an orbital with powers (lx, ly, lz) and total power L, each coefficient is first multiplied by the primitive normalisation, which is two times the exponent over pi, raised to the power three quarters, times four times the exponent raised to the power L over two, divided by the square root of the product of the double factorials of 2*lx-1, 2*ly-1 and 2*lz-1, where the double factorial of -1 is one. The whole contraction is then divided by the square root of its own self-overlap, which is the sum over both primitives of the product of the two scaled coefficients times pi over the exponent sum raised to the power three halves, times that same product of double factorials, divided by twice the exponent sum raised to the power L. The result is a real array with one row per orbital and ten columns, in this order: the index of the atom carrying the orbital, which is 0 or 1; the three cartesian powers; the three exponents; and the three normalised contraction coefficients.

Every quantity in this problem is a matrix in a basis of contracted Gaussians, so the basis has to be laid out before anything else can be computed, and the layout itself is part of the answer: one of the operations available later keeps only the lower triangle of a matrix, which means that relabelling the orbitals changes the result. Normalising the contraction rather than the individual primitives is what makes the diagonal of the overlap matrix exactly one, and a contraction that is normalised as though its primitives were orthogonal is the classic way to get every downstream energy slightly and silently wrong.

Returns
-------
numpy.ndarray of shape (n, 10) and real dtype.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def basis_table(symbols: "list", basis_data: "dict") -> "np.ndarray":
    """Build the table of contracted atomic orbitals for a diatomic molecule. SPECIFICATION: symbols names the two atoms. basis_data maps an element symbol to a list of shells; each shell is a tuple whose first entry is the angular momentum, 0 for s and 1 for p, whose second entry is a list of exactly three Gaussian exponents and whose third entry is a list of exactly three contraction coefficients. Orbitals are generated by walking the two atoms in the order given and, within each atom, its shells in the order given; an s shell contributes one orbital with cartesian powers (0, 0, 0) and a p shell contributes three, with powers (1, 0, 0), (0, 1, 0) and (0, 0, 1) in that order. For an orbital with powers (lx, ly, lz) and total power L, each coefficient is first multiplied by the primitive normalisation, which is two times the exponent over pi, raised to the power three quarters, times four times the exponent raised to the power L over two, divided by the square root of the product of the double factorials of 2*lx-1, 2*ly-1 and 2*lz-1, where the double factorial of -1 is one. The whole contraction is then divided by the square root of its own self-overlap, which is the sum over both primitives of the product of the two scaled coefficients times pi over the exponent sum raised to the power three halves, times that same product of double factorials, divided by twice the exponent sum raised to the power L. The result is a real array with one row per orbital and ten columns, in this order: the index of the atom carrying the orbital, which is 0 or 1; the three cartesian powers; the three exponents; and the three normalised contraction coefficients.

    Parameters
    ----------
    symbols : list of str, length 2
        The two element symbols, in the order the orbitals are laid out.
    basis_data : dict
        Maps an element symbol to its list of shells. Each shell is a tuple
        (l, exponents, coefficients): l is 0 for an s shell and 1 for a p shell,
        and exponents and coefficients are each a list of exactly three floats.

    Returns
    -------
    numpy.ndarray of shape (n, 10) and real dtype.

    Raises
    ------
    ValueError: if symbols does not name exactly two atoms, if basis_data has no entry for one of them, or if any shell does not hold exactly three primitives.
    """
    return [[0.0]]  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
from scipy.linalg import eigh
from scipy.special import gammainc, gamma

BOHR_PER_ANGSTROM = 1.0/0.52917721092
HARTREE2KCAL = 627.5094740631


def _dfact(n):
    return 1.0 if n <= 0 else float(np.prod(np.arange(n, 0, -2)))


def _oracle_basis_table(symbols: "list", basis_data: "dict") -> "np.ndarray":
    if len(symbols) != 2:
        raise ValueError("symbols must name exactly two atoms")
    for s in symbols:
        if s not in basis_data:
            raise ValueError(f"no basis entry for {s}")
    rows = []
    for ia, sym in enumerate(symbols):
        for l, e, c in basis_data[sym]:
            e = np.asarray(e, dtype=float)
            c = np.asarray(c, dtype=float)
            if e.size != 3 or c.size != 3:
                raise ValueError("every shell must hold exactly three primitives")
            comps = [(0, 0, 0)] if int(l) == 0 else [(1, 0, 0), (0, 1, 0), (0, 0, 1)]
            for lv in comps:
                dd = _dfact(2*lv[0]-1)*_dfact(2*lv[1]-1)*_dfact(2*lv[2]-1)
                L = sum(lv)
                cn = c*np.power(2*e/np.pi, 0.75)*np.power(4*e, L/2.0)/np.sqrt(dd)
                p = e[:, None] + e[None, :]
                s = float(np.sum(cn[:, None]*cn[None, :]*np.power(np.pi/p, 1.5)*dd
                                 / np.power(2*p, L)))
                if not np.isfinite(s) or s <= 0.0:
                    raise ValueError("shell has no positive self-overlap")
                rows.append(np.concatenate([[float(ia)], np.array(lv, dtype=float),
                                            e, cn/np.sqrt(s)]))
    return np.array(rows)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
      {"setup": "import numpy as np\nBD={'Li':[(0,[16.119575,2.9362007,0.7946505],[0.15432897,0.53532814,0.44463454]),(0,[0.6362897,0.1478601,0.0480887],[-0.09996723,0.39951283,0.70011547]),(1,[0.6362897,0.1478601,0.0480887],[0.15591627,0.60768372,0.39195739])],'F':[(0,[166.67913,30.360812,8.2168207],[0.15432897,0.53532814,0.44463454]),(0,[6.4648032,1.5022812,0.4885885],[-0.09996723,0.39951283,0.70011547]),(1,[6.4648032,1.5022812,0.4885885],[0.15591627,0.60768372,0.39195739])]}\nfrom copy import deepcopy as _dc\nBD_G=_dc(BD)",
       "call": "basis_table(['Li','F'],BD)",
       "gold_call": "_oracle_basis_table(['Li','F'],BD_G)"},  # light pair
      {"setup": "import numpy as np\nBD2={'Na':[(0,[250.77243,45.678511,12.362388],[0.1543289673,0.5353281423,0.4446345422]),(0,[12.040193,2.7978819,0.909958],[-0.09996722919,0.3995128261,0.7001154689]),(0,[1.4787406,0.4125649,0.1614751],[-0.219620369,0.2255954336,0.900398426]),(1,[12.040193,2.7978819,0.909958],[0.155916275,0.6076837186,0.3919573931]),(1,[1.4787406,0.4125649,0.1614751],[0.01058760429,0.5951670053,0.462001012])],'Cl':[(0,[601.3456136,109.5358542,29.64467686],[0.1543289673,0.5353281423,0.4446345422]),(0,[38.96041889,9.053563477,2.944499834],[-0.09996722919,0.3995128261,0.7001154689]),(0,[2.129386495,0.5940934274,0.232524141],[-0.219620369,0.2255954336,0.900398426]),(1,[38.96041889,9.053563477,2.944499834],[0.155916275,0.6076837186,0.3919573931]),(1,[2.129386495,0.5940934274,0.232524141],[0.01058760429,0.5951670053,0.462001012])]}\nfrom copy import deepcopy as _dc\nBD2_G=_dc(BD2)",
       "call": "basis_table(['Na','Cl'],BD2)",
       "gold_call": "_oracle_basis_table(['Na','Cl'],BD2_G)"},  # both atoms with three shells of s
      {"setup": "import numpy as np\nBD={'Li':[(0,[16.119575,2.9362007,0.7946505],[0.15432897,0.53532814,0.44463454]),(0,[0.6362897,0.1478601,0.0480887],[-0.09996723,0.39951283,0.70011547]),(1,[0.6362897,0.1478601,0.0480887],[0.15591627,0.60768372,0.39195739])],'F':[(0,[166.67913,30.360812,8.2168207],[0.15432897,0.53532814,0.44463454]),(0,[6.4648032,1.5022812,0.4885885],[-0.09996723,0.39951283,0.70011547]),(1,[6.4648032,1.5022812,0.4885885],[0.15591627,0.60768372,0.39195739])]}\nfrom copy import deepcopy as _dc\nBD_G=_dc(BD)",
       "call": "basis_table(['F','F'],BD)",
       "gold_call": "_oracle_basis_table(['F','F'],BD_G)"},  # the same element twice
        {"setup": "import numpy as np\nBD={'Li':[(0,[16.119575,2.9362007,0.7946505],[0.15432897,0.53532814,0.44463454]),(0,[0.6362897,0.1478601,0.0480887],[-0.09996723,0.39951283,0.70011547]),(1,[0.6362897,0.1478601,0.0480887],[0.15591627,0.60768372,0.39195739])],'F':[(0,[166.67913,30.360812,8.2168207],[0.15432897,0.53532814,0.44463454]),(0,[6.4648032,1.5022812,0.4885885],[-0.09996723,0.39951283,0.70011547]),(1,[6.4648032,1.5022812,0.4885885],[0.15591627,0.60768372,0.39195739])]}\nfrom copy import deepcopy as _dc\nBD_G=_dc(BD)\ndef _c():\n    try:\n        basis_table(['Li'],BD)\n        return 0\n    except ValueError:\n        return 1\n    except Exception:\n        return 2\ndef _g():\n    try:\n        _oracle_basis_table(['Li'],BD_G)\n        return 0\n    except ValueError:\n        return 1\n    except Exception:\n        return 2",
         "call": "_c()",
         "gold_call": "_g()"},   # invalid input
    ]
