"""
Compute the generalized Hastings correction generated by state-dependent switching between harmonic and free bridge proposals.

The proposal family is state-dependent: the forward kernel is selected from the current bead and the reverse kernel from the trial bead. Derive the generalized correction from detailed balance for harmonic Trotter splitting by comparing each selected kernel with the harmonic reference kernel at the same evaluated point. The closed harmonic domain includes its boundary. Evaluate only the combined Gaussian likelihood ratios needed by the correction, in log space, so the factor remains finite whenever the exact ratio is finite even if individual densities or individual standardized quadratic terms exceed binary64 range. This cancellation requirement applies for both equal and unequal proposal variances; the stable paired form must be derived rather than obtained by separately forming the two large quadratic terms.

Returns
-------
float, the positive generalized Hastings factor as a native Python float
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import math

from numbers import Real

import numpy as np


def _finite_float(name: str, value: float) -> float:
    if isinstance(value, (bool, np.bool_)) or not isinstance(value, Real):
        raise ValueError(f"{name} must be a finite real scalar")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{name} must be finite")
    return result


def _log_normal_pdf(value: float, mean: float, variance: float) -> float:
    standardized = (value - mean) / math.sqrt(variance)
    return -0.5 * (
        math.log(2.0 * math.pi)
        + math.log(variance)
        + standardized * standardized
    )


def compute_hastings_factor(
    old: float,
    trial: float,
    minimum: float,
    domain_radius: float,
    harmonic_mean: float,
    harmonic_variance: float,
    free_mean: float,
    free_variance: float,
) -> float:
    """Compute the generalized state-dependent Hastings factor.

    Parameters
    ----------
    old, trial : float
        Current and proposed bead positions.
    minimum : float
        Center of the closed harmonic domain.
    domain_radius : float
        Nonnegative radius of the harmonic domain.
    harmonic_mean, harmonic_variance : float
        Mean and positive variance of the harmonic bridge.
    free_mean, free_variance : float
        Mean and positive variance of the free bridge.

    Returns
    -------
    factor : float
        Positive finite generalized Hastings factor as a native Python
        float. Evaluate the required Gaussian likelihood ratios directly
        in a cancellation-safe log form. The result must remain finite
        when individual densities or individual standardized quadratic
        terms are not representable, including the unequal-variance case,
        provided the exact combined log-ratio is finite.

    Raises
    ------
    ValueError
        If any scalar input is not a finite real value; if
        ``domain_radius`` is negative; if either proposal variance is not
        strictly positive; or if the resulting factor is non-finite or
        non-positive.
    """
    return float("nan")

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_compute_hastings_factor(
    old: float,
    trial: float,
    minimum: float,
    domain_radius: float,
    harmonic_mean: float,
    harmonic_variance: float,
    free_mean: float,
    free_variance: float,
) -> float:
    """Reference implementation with stable paired Gaussian log ratios."""
    import math
    import numbers

    import numpy as np

    values = {
        "old": old,
        "trial": trial,
        "minimum": minimum,
        "domain_radius": domain_radius,
        "harmonic_mean": harmonic_mean,
        "harmonic_variance": harmonic_variance,
        "free_mean": free_mean,
        "free_variance": free_variance,
    }
    converted: dict[str, float] = {}
    for name, value in values.items():
        if isinstance(value, (bool, np.bool_)) or not isinstance(value, numbers.Real):
            raise ValueError(f"{name} must be a finite real scalar")
        value_f = float(value)
        if not math.isfinite(value_f):
            raise ValueError(f"{name} must be finite")
        converted[name] = value_f

    old_f = converted["old"]
    trial_f = converted["trial"]
    minimum_f = converted["minimum"]
    radius_f = converted["domain_radius"]
    harmonic_mean_f = converted["harmonic_mean"]
    harmonic_variance_f = converted["harmonic_variance"]
    free_mean_f = converted["free_mean"]
    free_variance_f = converted["free_variance"]
    if radius_f < 0.0:
        raise ValueError("domain_radius must be >= 0")
    if harmonic_variance_f <= 0.0 or free_variance_f <= 0.0:
        raise ValueError("proposal variances must be > 0")

    old_inside = abs(old_f - minimum_f) <= radius_f
    trial_inside = abs(trial_f - minimum_f) <= radius_f
    forward_mean = harmonic_mean_f if old_inside else free_mean_f
    forward_variance = harmonic_variance_f if old_inside else free_variance_f
    reverse_mean = harmonic_mean_f if trial_inside else free_mean_f
    reverse_variance = harmonic_variance_f if trial_inside else free_variance_f

    def raw_log_normal(value: float, mean: float, variance: float) -> float:
        return -0.5 * math.log(2.0 * math.pi * variance) - (
            value - mean
        ) ** 2 / (2.0 * variance)

    def stable_log_ratio(
        value: float,
        numerator_mean: float,
        numerator_variance: float,
        denominator_mean: float,
        denominator_variance: float,
    ) -> float:
        """Return log N_num(value) - log N_den(value) without separate squares."""
        if (
            numerator_mean == denominator_mean
            and numerator_variance == denominator_variance
        ):
            return 0.0

        if numerator_variance == denominator_variance:
            # Difference of squares, ordered so the small scale is applied first.
            first = (numerator_mean - denominator_mean) / (
                2.0 * numerator_variance
            )
            second = 2.0 * value - numerator_mean - denominator_mean
            return first * second

        sqrt_num = math.sqrt(numerator_variance)
        sqrt_den = math.sqrt(denominator_variance)
        z_num = (value - numerator_mean) / sqrt_num
        z_den = (value - denominator_mean) / sqrt_den
        if not math.isfinite(z_num) or not math.isfinite(z_den):
            raise ValueError("paired standardized displacements must be finite")

        # Factor the difference of squares before either square is formed.
        quadratic_difference = (z_num - z_den) * (z_num + z_den)
        log_variance_ratio = math.log(denominator_variance) - math.log(
            numerator_variance
        )
        return 0.5 * log_variance_ratio - 0.5 * quadratic_difference

    # Preserve the previous binary64 route in ordinary regimes. If an
    # individual squared displacement overflows, switch to paired ratios.
    try:
        log_reverse_old = raw_log_normal(old_f, reverse_mean, reverse_variance)
        log_harmonic_old = raw_log_normal(
            old_f, harmonic_mean_f, harmonic_variance_f
        )
        log_forward_trial = raw_log_normal(
            trial_f, forward_mean, forward_variance
        )
        log_harmonic_trial = raw_log_normal(
            trial_f, harmonic_mean_f, harmonic_variance_f
        )
        log_factor = (
            log_reverse_old
            - log_harmonic_old
            - log_forward_trial
            + log_harmonic_trial
        )
        if not math.isfinite(log_factor):
            raise ArithmeticError("non-finite separately evaluated log ratio")
    except (ArithmeticError, OverflowError):
        log_factor = stable_log_ratio(
            old_f,
            reverse_mean,
            reverse_variance,
            harmonic_mean_f,
            harmonic_variance_f,
        ) + stable_log_ratio(
            trial_f,
            harmonic_mean_f,
            harmonic_variance_f,
            forward_mean,
            forward_variance,
        )

    try:
        factor = math.exp(log_factor)
    except OverflowError as exc:
        raise ValueError("Hastings factor must be finite") from exc
    if not math.isfinite(factor) or factor <= 0.0:
        raise ValueError("Hastings factor must be finite and > 0")
    return float(factor)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return crossing, cancellation, underflow, invalid, and paired-ratio cases."""
    return [
        {
            "setup": """old = 0.26\ntrial = 0.2948678088618854\nminimum = -0.15\ndomain_radius = 0.44\nharmonic_mean = 0.07447545834845315\nharmonic_variance = 0.09912813911190939\nfree_mean = 0.125\nfree_variance = 0.11307692307692305""",
            "call": "compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
            "gold_call": "_oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
        },
        {
            "setup": """old = 0.03\ntrial = 0.187003474188357\nminimum = -0.15\ndomain_radius = 0.44\nharmonic_mean = 0.029580366678762515\nharmonic_variance = 0.09912813911190939\nfree_mean = 0.07\nfree_variance = 0.11307692307692305""",
            "call": "compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
            "gold_call": "_oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
        },
        {
            "setup": """old = -0.6\ntrial = 0.28489603528975127\nminimum = -0.15\ndomain_radius = 0.44\nharmonic_mean = -0.09694216439036563\nharmonic_variance = 0.09912813911190939\nfree_mean = -0.085\nfree_variance = 0.11307692307692305""",
            "call": "compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
            "gold_call": "_oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
        },
        {
            "setup": """old = 0.0\ntrial = 1.0\nminimum = 0.0\ndomain_radius = 0.5\nharmonic_mean = 0.0\nharmonic_variance = 1.0e-6\nfree_mean = 0.001\nfree_variance = 1.0e-6""",
            "call": "compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
            "gold_call": "_oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
        },
        {
            "setup": """old = 0.0\ntrial = 0.1\nminimum = 0.0\ndomain_radius = 1.0\nharmonic_mean = 0.0\nharmonic_variance = 0.0\nfree_mean = 0.0\nfree_variance = 1.0\ndef run_model():\n    try:\n        compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)\n        return 0\n    except ValueError:\n        return 1\n    except Exception:\n        return 2\ndef run_gold():\n    try:\n        _oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)\n        return 0\n    except ValueError:\n        return 1\n    except Exception:\n        return 2""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        {
            "setup": """old = 1.0e160\ntrial = 1.0000000000000002e160\nminimum = 0.0\ndomain_radius = 1.0e160\nharmonic_mean = 0.0\nharmonic_variance = 1.0e300\nfree_mean = 1.0e140\nfree_variance = 1.0e300""",
            "call": "compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
            "gold_call": "_oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
        },
        {
            "setup": """old = 1.0e160\ntrial = 1.1e160\nminimum = 0.0\ndomain_radius = 1.0e160\nharmonic_mean = 0.0\nharmonic_variance = 1.0\nfree_mean = -1.0e160\nfree_variance = 4.0""",
            "call": "compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
            "gold_call": "_oracle_compute_hastings_factor(old, trial, minimum, domain_radius, harmonic_mean, harmonic_variance, free_mean, free_variance)",
        },
    ]
