"""
Build the restricted-pairing, unrestricted-spin orbital coefficient matrices of a seniority eigenstate configuration interaction wave function from antisymmetric rotation parameters.

In seniority-based wave functions every spatial level $p$ is paired with itself across spin, and the orbitals are optimized variationally. The spin-up and spin-down orbital coefficients are generated by exponentials of real antisymmetric matrices, $C^{\mathrm{up}}=e^{X}$ and $C^{\mathrm{dn}}=e^{X}e^{Y}$, where $X$ is an $M\times M$ generator shared by both spins and $Y$ is nonzero only in the block of the $k$ singly occupied (spin) levels. The pairing levels therefore keep identical spatial orbitals for both spins, while the spin levels may break spin symmetry, which is needed because a spin-restricted treatment of the singly occupied levels misses the energy lowering that comes from kinetic hopping.

Returns
-------
np.ndarray of shape (2, M, M): [C_up, C_dn] = [expm(X), expm(X) expm(Y)]
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def unrestricted_orbitals(x_params: "np.ndarray", y_params: "np.ndarray", n_levels: int, n_spin_levels: int) -> "np.ndarray":
    '''Return the spin-up and spin-down orbital coefficient matrices.
 
    Let M = n_levels and k = n_spin_levels. The antisymmetric generator X (M x M) has
    strict upper triangle filled row by row from x_params, in the order of
    numpy.triu_indices(M, 1), and X = A - A^T where A holds those entries. The generator
    Y (M x M) is zero except for its last k rows and columns, whose k x k block is built
    from y_params in the same way (order of numpy.triu_indices(k, 1)). Then
 
        C_up   = expm(X),
        C_down = expm(X) @ expm(Y),
 
    where column p of each matrix is the p-th orbital expanded in the M basis functions.
    Levels 0..M-k-1 are the pairing levels and levels M-k..M-1 the spin levels.
 
    Parameters
    ----------
    x_params : np.ndarray
        1-D array of M(M-1)/2 real rotation parameters.
    y_params : np.ndarray
        1-D array of k(k-1)/2 real rotation parameters (empty when k < 2).
    n_levels : int
        Number of spatial levels M >= 1.
    n_spin_levels : int
        Number of spin levels k with 0 <= k <= M.
 
    Returns
    -------
    orbitals : np.ndarray
        Array of shape (2, M, M): orbitals[0] = C_up and orbitals[1] = C_down.
 
    Raises
    ------
    ValueError
        If M < 1, k is outside [0, M], or a parameter array has the wrong length.
    '''
    return orbitals

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
from scipy.linalg import expm
 
def _antisymmetric(values: "np.ndarray", size: int) -> "np.ndarray":
    values = np.asarray(values)
    generator = np.zeros((size, size), dtype=np.result_type(values, float))
    generator[np.triu_indices(size, 1)] = values
    return generator - generator.T
 
def _oracle_unrestricted_orbitals(x_params: "np.ndarray", y_params: "np.ndarray", n_levels: int, n_spin_levels: int) -> "np.ndarray":
    m, k = int(n_levels), int(n_spin_levels)
    if m < 1 or not 0 <= k <= m:
        raise ValueError("need n_levels >= 1 and 0 <= n_spin_levels <= n_levels")
    x = np.asarray(x_params).ravel()
    y = np.asarray(y_params).ravel()
    if x.size != m * (m - 1) // 2 or y.size != k * (k - 1) // 2:
        raise ValueError("rotation parameter arrays have the wrong length")
    gen_x = _antisymmetric(x, m)
    gen_y = np.zeros((m, m), dtype=gen_x.dtype)
    if k > 1:
        gen_y[m - k:, m - k:] = _antisymmetric(y, k)
    c_up = expm(gen_x)
    return np.stack([c_up, c_up @ expm(gen_y)])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # Normal: benchmark size (8 levels, 4 spin levels) with random parameters
        {
            "setup": """import numpy as np
rng = np.random.default_rng(0)
x = rng.normal(size=28)
y = rng.normal(size=6)
""",
            "call": "unrestricted_orbitals(x.copy(), y.copy(), 8, 4)",
            "gold_call": "_oracle_unrestricted_orbitals(x.copy(), y.copy(), 8, 4)",
        },
        # Normal: maximal seniority (all 6 levels are spin levels)
        {
            "setup": """import numpy as np
rng = np.random.default_rng(1)
x = 0.3 * rng.normal(size=15)
y = 0.7 * rng.normal(size=15)
""",
            "call": "unrestricted_orbitals(x.copy(), y.copy(), 6, 6)",
            "gold_call": "_oracle_unrestricted_orbitals(x.copy(), y.copy(), 6, 6)",
        },
        # Boundary: one spin level, so Y is empty and both spins share the orbitals
        {
            "setup": """import numpy as np
x = np.linspace(-0.5, 0.5, 10)
y = np.zeros(0)
""",
            "call": "unrestricted_orbitals(x.copy(), y.copy(), 5, 1)",
            "gold_call": "_oracle_unrestricted_orbitals(x.copy(), y.copy(), 5, 1)",
        },
        # Edge: zero parameters give identity orbitals
        {
            "setup": """import numpy as np
x = np.zeros(6)
y = np.zeros(3)
""",
            "call": "unrestricted_orbitals(x.copy(), y.copy(), 4, 3)",
            "gold_call": "_oracle_unrestricted_orbitals(x.copy(), y.copy(), 4, 3)",
        },
        # Invalid: wrong number of spin-block parameters
        {
            "setup": """import numpy as np
def run_model():
    try:
        unrestricted_orbitals(np.zeros(6), np.zeros(2), 4, 3)
        return 0
    except ValueError:
        return 1
def run_oracle():
    try:
        _oracle_unrestricted_orbitals(np.zeros(6), np.zeros(2), 4, 3)
        return 0
    except ValueError:
        return 1
""",
            "call": "run_model()",
            "gold_call": "run_oracle()",
        },
    ]
