"""
Return the time derivative of the six-component Cartesian phase-space state generated by the energy function of the previous step, in the same component order as the state.

The equations of motion are the canonical ones. Evaluating the required derivatives to full precision matters: the periodic orbits located later are strongly unstable, so a derivative accurate only to a few digits degrades everything downstream.

Returns
-------
ndarray of shape (6,): the time derivative of the state.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def vector_field(state: "np.ndarray", params: dict) -> "np.ndarray":
    """Return the time derivative of the six-component Cartesian phase-space state generated by the energy function of the previous step, in the same component order as the state.

    Parameters
    ----------
    state : np.ndarray
        Six-component phase-space point (x, y, z, px, py, pz).
    params : dict
        Mapping carrying ix, iz, m, de, re, c1, c2, ve, alpha and b.

    Returns
    -------
    derivative : np.ndarray
        ndarray of shape (6,): the time derivative of the state.

    Raises
    ------
    ValueError
        if the state does not have six components.
    """
    return derivative

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
from scipy.integrate import solve_ivp


def _oracle_vector_field(state: "np.ndarray", params: dict) -> "np.ndarray":
    s = np.asarray(state, float)
    if s.shape != (6,):
        raise ValueError("state must have exactly six components")
    out = np.empty(6); h = 1e-30
    for i in range(6):
        sc = s.astype(complex); sc[i] += 1j * h
        d = _oracle_hamiltonian(sc, params).imag / h
        if i < 3:
            out[i + 3] = -d
        else:
            out[i - 3] = d
    return out

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return the list of test-case specifications for this step."""
    return [
        {"tol": 1e-06, "setup": "import numpy as np",
         "call": "vector_field(np.array([0.0,0.0,3.65072544,0.59303049,0.0,0.0]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.0))",
         "gold_call": "_oracle_vector_field(np.array([0.0,0.0,3.65072544,0.59303049,0.0,0.0]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.0))"},   # normal
        {"tol": 1e-06, "setup": "import numpy as np",
         "call": "vector_field(np.array([0.8,0.3,3.2,0.2,-0.1,0.05]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.0))",
         "gold_call": "_oracle_vector_field(np.array([0.8,0.3,3.2,0.2,-0.1,0.05]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.0))"},   # normal
        {"tol": 1e-06, "setup": "import numpy as np",
         "call": "vector_field(np.array([0.8,0.3,3.2,0.2,-0.1,0.05]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.30))",
         "gold_call": "_oracle_vector_field(np.array([0.8,0.3,3.2,0.2,-0.1,0.05]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.30))"},   # boundary
        {"tol": 1e-06, "setup": "import numpy as np",
         "call": "vector_field(np.array([1e-4,5e-5,3.4,0.05,-0.02,0.1]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.30))",
         "gold_call": "_oracle_vector_field(np.array([1e-4,5e-5,3.4,0.05,-0.02,0.1]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.30))"},   # edge
        {"setup": "import numpy as np\ndef _c(fn):\n    try:\n        fn(np.array([0.0,0.0,3.0]), dict(ix=2.373409, iz=4.746818, m=0.9445, de=47.0, re=1.1, c1=7.37, c2=1.61, ve=55.0, alpha=1.0, b=0.0))\n    except ValueError:\n        return 1\n    except Exception:\n        return 0\n    return 0",
         "call": "_c(vector_field)", "gold_call": "_c(_oracle_vector_field)"},   # exception contract
    ]
