"""
Enumerate the plane-wave triples of the free-electron states at the X point of the diamond structure that lie on a requested dimensionless energy shell, sorted lexicographically.

Silicon crystallises in the diamond structure, whose Bravais lattice is face-centred cubic with
a two-atom basis. The conduction-band physics of interest here lives at the X point of the
Brillouin zone, kX = (2*pi/a)(0, 0, 1). Working in units where the cubic lattice constant a is
2*pi, so that kX = (0, 0, 1), a Bloch state at X has the form psi = exp(i z) u(r) with u periodic
on the lattice, and the periodic factors are spanned by plane waves exp(-i n . r) whose index
triples n are reciprocal-lattice vectors of the FCC lattice.

The reciprocal lattice of an FCC direct lattice is body-centred cubic; in these units its vectors
are generated by the rows of (2*pi/a) times the matrix with -1 on the diagonal and +1 off it,
which places a simple parity restriction on the admissible integer triples n. Combining the
Bloch factor with the periodic part gives a plane wave exp(-i p . r) with p obtained from n by
subtracting the X-point wave vector along z, and a dimensionless free-electron energy equal to
p . p.

This step enumerates the plane-wave triples p that lie on a requested energy shell. The shell
that carries the silicon conduction band is the one this task uses later; the routine must work
for any requested shell so that the degeneracy pattern can be inspected. Shells that admit no
triple at all are legitimate and must return an empty result rather than raising.

Returns
-------
np.ndarray of length 3*M: the M lexicographically sorted triples p, flattened row-major
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def plane_wave_shell_at_X(eps_shell: int, n_max: int) -> np.ndarray:
    '''Plane-wave triples of the free-electron states at the X point of the diamond structure.

    Parameters
    ----------
    eps_shell : int
        Dimensionless free-electron energy p . p of the requested shell; positive integer.
    n_max : int
        Search range for each component of the reciprocal-lattice index triple n, which is
        scanned over -n_max .. n_max; positive integer.

    Returns
    -------
    result : np.ndarray
        Real array of length 3*M holding the M admissible triples p flattened row-major, the
        rows first sorted in ascending lexicographic order. M may be zero.

    Raises
    ------
    ValueError
        If eps_shell < 1 or n_max < 1.
    '''
    return result  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
import itertools


def _oracle_plane_wave_shell_at_X(eps_shell: int, n_max: int) -> np.ndarray:
    if int(eps_shell) < 1:
        raise ValueError("eps_shell must be a positive integer")
    if int(n_max) < 1:
        raise ValueError("n_max must be a positive integer")
    out = []
    for n1, n2, n3 in itertools.product(range(-int(n_max), int(n_max) + 1), repeat=3):
        if (n1 % 2 != n2 % 2) or (n2 % 2 != n3 % 2):
            continue
        p = (n1, n2, n3 - 1)
        if p[0] ** 2 + p[1] ** 2 + p[2] ** 2 == int(eps_shell):
            out.append(p)
    return np.array(sorted(out), dtype=float).ravel()

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        {
            "setup": "import numpy as np",
            "call": 'plane_wave_shell_at_X(5, 4)',
            "gold_call": '_oracle_plane_wave_shell_at_X(5, 4)',
        },  # normal, the shell carrying the silicon conduction band
        {
            "setup": "import numpy as np",
            "call": 'plane_wave_shell_at_X(1, 3)',
            "gold_call": '_oracle_plane_wave_shell_at_X(1, 3)',
        },  # boundary, the lowest shell at the X point
        {
            "setup": "import numpy as np",
            "call": 'plane_wave_shell_at_X(2, 3)',
            "gold_call": '_oracle_plane_wave_shell_at_X(2, 3)',
        },  # boundary, an all-odd index shell exercising the parity rule
        {
            "setup": "import numpy as np",
            "call": 'np.array([float(plane_wave_shell_at_X(e, 4).size) for e in (3, 4, 6)])',
            "gold_call": 'np.array([float(_oracle_plane_wave_shell_at_X(e, 4).size) for e in (3, 4, 6)])',
        },  # edge, forbidden shells are empty while the next allowed one is not
        {
            "setup": "import numpy as np",
            "call": 'plane_wave_shell_at_X(9, 5)',
            "gold_call": '_oracle_plane_wave_shell_at_X(9, 5)',
        },  # normal, a higher shell with a different degeneracy
        {
            "setup": 'import numpy as np\ndef _raises(fn):\n    try:\n        fn()\n    except ValueError:\n        return 1.0\n    return 0.0\n',
            "call": 'np.array([_raises(lambda: plane_wave_shell_at_X(0, 4))])',
            "gold_call": 'np.array([_raises(lambda: _oracle_plane_wave_shell_at_X(0, 4))])',
        },  # contract, invalid input must raise ValueError
    ]
