"""
Find, for every subset and each sign of the threshold, the exponential tilt that moves the mean of the subset statistic onto that threshold.

Estimating a tail probability by simulating from the null is hopeless once the probability falls far below the reciprocal of the affordable number of replicates. The remedy is to simulate from a different law under which the rare event is common and to correct each replicate by its likelihood ratio. The classical choice of that law is the exponentially tilted family generated by the statistic itself, in which the null probability of a configuration is multiplied by the exponential of a tilt times the statistic and renormalised by the cumulant generating function. The tilt is the one free parameter, and the variance of the resulting estimator depends on it sharply.




The near optimal choice is the one that centres the tilted law on the boundary of the rare event, that is, the tilt at which the mean of the statistic equals the observed threshold. Under that measure the event of interest has probability roughly one half, so nearly every replicate is informative, and the likelihood ratio is nearly constant across the replicates that matter, which is what collapses the variance. Since the derivative of the cumulant generating function is the tilted mean and is strictly increasing, the equation that defines this tilt has exactly one solution and can be solved reliably. Combining a maintained bracket with Newton steps is the safe way to do it: the second derivative supplies the Newton step, the bracket catches the iterates that a nearly flat derivative would otherwise throw far away, and bisection takes over when a step leaves the bracket.




Two features of the all-subset problem force this to be done more than once. First, the estimator mixes over the subsets, since no single subset drives the maximum, so a tilt has to be found for each subset separately using that subset's own coefficients. Second, the scan is two-sided: the maximum is taken over absolute values, so the rare event has two branches and the tilted law must be able to reach either. Because the coefficients of a subset are not symmetric functions of the subjects and the genotype distribution itself is skewed under a low allele frequency, the cumulant generating function is not an even function, and the tilt that reaches the negative branch is not the negative of the tilt that reaches the positive one. Two distinct tilts per subset are therefore required, and using one and negating it biases the estimator.




The equation is solvable only for thresholds inside the range that the statistic can actually attain, which for a bounded lattice statistic is a finite interval determined by the coefficients. A threshold at or beyond that limit means the tilted mean can never reach it, and the correct response is to reject the request rather than to let the bracket search run away.

Returns
-------
np.ndarray of shape (n_subsets, 2), float: the positive-branch and negative-branch exponential tilts of every subset.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np

def solve_tilting_parameters(weights: np.ndarray, maf: float, threshold: float) -> np.ndarray:
    """Return the two exponential tilts of every subset statistic.

    Column 0 holds the tilt at which the tilted mean of the subset statistic
    equals plus threshold and column 1 the tilt at which it equals minus
    threshold. Each root is found by a bracketed Newton iteration started from
    the bracket obtained by doubling the interval [-1, 1] outward, and is
    accepted once the tilted mean is within 1e-12 of its target or the bracket
    has collapsed to a relative width of 1e-14.

    Parameters
    ----------
    weights : np.ndarray
        Table of per-subject coefficients of shape (n_subsets, n_subjects).
    maf : float
        Minor allele frequency, 0 < maf <= 0.5.
    threshold : float
        Observed value of the all-subset maximum, threshold > 0.

    Returns
    -------
    tilts : np.ndarray
        Array of shape (n_subsets, 2) holding the positive-branch and
        negative-branch tilts of every subset.
    """
    return tilts  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np

def _oracle_solve_tilting_parameters(weights: np.ndarray, maf: float, threshold: float) -> np.ndarray:
    # Local imports keep the oracle self-contained when the harness
    # executes it in isolation.
    import numpy as np

    table = np.asarray(weights, dtype=float)
    if table.ndim != 2 or table.shape[0] < 1 or table.shape[1] < 1:
        raise ValueError("weights must be a non-empty 2D array")
    if not np.all(np.isfinite(table)):
        raise ValueError("weights must be finite")
    if not (isinstance(maf, (int, float)) and np.isfinite(maf)
            and 0.0 < float(maf) <= 0.5):
        raise ValueError("maf must be a finite number in the half-open interval (0, 0.5]")
    if not (isinstance(threshold, (int, float)) and np.isfinite(threshold)
            and float(threshold) > 0.0):
        raise ValueError("threshold must be a finite number > 0")

    frequency = float(maf)
    centred = np.array([0.0, 1.0, 2.0]) - 2.0 * frequency
    log_prior = np.log(np.array([(1.0 - frequency) ** 2,
                                 2.0 * frequency * (1.0 - frequency),
                                 frequency ** 2]))

    def _derivatives(row, tilt):
        exponents = tilt * np.outer(row, centred) + log_prior[None, :]
        scaled = np.exp(exponents - np.max(exponents, axis=1)[:, None])
        tilted = scaled / scaled.sum(axis=1)[:, None]
        mean = tilted @ centred
        variance = tilted @ (centred * centred) - mean * mean
        return float(np.sum(row * mean)), float(np.sum(row * row * variance))

    def _solve(row, target):
        low, high = -1.0, 1.0
        while _derivatives(row, low)[0] > target:
            if low < -1.0e8:
                raise ValueError("threshold lies outside the range the subset statistic can attain")
            low *= 2.0
        while _derivatives(row, high)[0] < target:
            if high > 1.0e8:
                raise ValueError("threshold lies outside the range the subset statistic can attain")
            high *= 2.0
        tilt = 0.5 * (low + high)
        for _ in range(400):
            first, second = _derivatives(row, tilt)
            residual = first - target
            if residual > 0.0:
                high = tilt
            else:
                low = tilt
            if abs(residual) <= 1e-12 or (high - low) <= 1e-14 * max(1.0, abs(tilt)):
                break
            step = tilt - residual / second if second > 0.0 else 0.5 * (low + high)
            tilt = step if low < step < high else 0.5 * (low + high)
        return tilt

    level = float(threshold)
    tilts = np.empty((table.shape[0], 2), dtype=float)
    for index in range(table.shape[0]):
        tilts[index, 0] = _solve(table[index], +level)
        tilts[index, 1] = _solve(table[index], -level)
    return tilts

# =============================================================================
# TEST CASES
# =============================================================================

import numpy as np

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: rare variant, tail threshold (normal scenario) ---
        {
            "setup": """import numpy as np
rng = np.random.default_rng(31)
weights = rng.standard_normal((15, 120)) / np.sqrt(120 * 2 * 0.02 * 0.98)
maf, threshold = 0.02, 7.0
def digest(value):
    flat = np.asarray(value, dtype=float).ravel()
    w = np.arange(1.0, flat.size + 1.0) / (flat.size + 1.0)
    return float(np.abs(flat) @ w + flat @ w ** 2)
""",
            "call": "digest(solve_tilting_parameters(weights, maf, threshold))",
            "gold_call": "digest(_oracle_solve_tilting_parameters(weights, maf, threshold))",
        },
        # --- Valid: common variant, where the two branches are nearly symmetric ---
        {
            "setup": """import numpy as np
rng = np.random.default_rng(31)
weights = rng.standard_normal((15, 120)) / np.sqrt(120 * 2 * 0.5 * 0.5)
maf, threshold = 0.5, 4.0
def digest(value):
    flat = np.asarray(value, dtype=float).ravel()
    w = np.arange(1.0, flat.size + 1.0) / (flat.size + 1.0)
    return float(np.abs(flat) @ w + flat @ w ** 2)
""",
            "call": "digest(solve_tilting_parameters(weights, maf, threshold))",
            "gold_call": "digest(_oracle_solve_tilting_parameters(weights, maf, threshold))",
        },
        # --- Boundary: threshold just inside the attainable range of the statistic ---
        {
            "setup": """import numpy as np
weights = np.array([[0.5, -0.5, 0.5, -0.5, 0.5]])
maf, threshold = 0.1, 2.0
def digest(value):
    flat = np.asarray(value, dtype=float).ravel()
    w = np.arange(1.0, flat.size + 1.0) / (flat.size + 1.0)
    return float(np.abs(flat) @ w + flat @ w ** 2)
""",
            "call": "digest(solve_tilting_parameters(weights, maf, threshold))",
            "gold_call": "digest(_oracle_solve_tilting_parameters(weights, maf, threshold))",
        },
        # --- Edge: coefficients of opposite sign and very different magnitude ---
        {
            "setup": """import numpy as np
weights = np.array([[3.0, -0.05, 0.4, -2.0, 0.001]])
maf, threshold = 0.05, 1.5
def digest(value):
    flat = np.asarray(value, dtype=float).ravel()
    w = np.arange(1.0, flat.size + 1.0) / (flat.size + 1.0)
    return float(np.abs(flat) @ w + flat @ w ** 2)
""",
            "call": "digest(solve_tilting_parameters(weights, maf, threshold))",
            "gold_call": "digest(_oracle_solve_tilting_parameters(weights, maf, threshold))",
        },
        # --- Invalid: threshold beyond the range the statistic can attain ---
        {
            "setup": """import numpy as np
weights = np.ones((1, 3))
def run_model():
    try:
        solve_tilting_parameters(weights, 0.1, 100.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_solve_tilting_parameters(weights, 0.1, 100.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: negative threshold ---
        {
            "setup": """import numpy as np
weights = np.ones((2, 6))
def run_model():
    try:
        solve_tilting_parameters(weights, 0.2, -3.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_solve_tilting_parameters(weights, 0.2, -3.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
