"""
Step 02 - Phonon propagator of the polaron transformation.

Phonon propagator of the polaron transformation.

A polaron transformation removes the linear dot-lattice coupling of step 01 by displacing
each phonon mode in proportion to the number of excitons present. The displacement of
one exciton is generated by the operators

    B_+ = exp[ + sum_k (g_k / omega_k) (b_k^dag - b_k) ],    B_- = exp[ - sum_k (g_k / omega_k) (b_k^dag - b_k) ],

with real couplings g_k and phonon frequencies omega_k (both in rad/ps). The lattice is in
thermal equilibrium at temperature T, and operators evolve freely under the phonon
Hamiltonian, B(t) = exp(i H_ph t / hbar) B exp(-i H_ph t / hbar). Two quantities follow:
the thermal average <B> = <B_+> = <B_->, and the phonon propagator phi(t), defined through

    < B_+(t) B_-(0) > = <B>^2 exp[ phi(t) ].

The couplings g_k are those of step 01, whose spectral density J(omega) summarises them
(lattice array as defined there). Use hbar = 0.6582119569 meV ps and
k_B = 0.08617333262 meV/K, so that hbar omega / (k_B T) is dimensionless for omega in
rad/ps and T in K. The result must be converged to at least eight significant figures.

Returns
-------
numpy.ndarray of shape (2, len(t)): [Re phi(t), Im phi(t)] of the phonon propagator (dimensionless)
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def phonon_propagator(t: np.ndarray, T: float, lattice: np.ndarray) -> np.ndarray:
    '''Phonon propagator phi(t) of the polaron transformation at temperature T.

    Parameters
    ----------
    t : np.ndarray
        One-dimensional array of times in ps, every entry >= 0.
    T : float
        Lattice temperature in K, > 0.
    lattice : np.ndarray
        Shape (6,): [D_e (eV), D_h (eV), mass density (kg/m^3), c_s (m/s), a_e (nm), a_h (nm)].

    Returns
    -------
    phi : np.ndarray
        Shape (2, len(t)): row 0 is Re phi(t), row 1 is Im phi(t) (dimensionless).

    Raises
    ------
    ValueError
        If t is not a one-dimensional array of finite values >= 0, if T is not finite
        and positive, or if lattice is invalid (as in step 01).
    '''
    return phi

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _omega_nodes(lattice, tmax):
    """Composite 20-point Gauss-Legendre nodes and weights on [0, W] covering the phonon band."""
    De, Dh, density, cs, ae, ah = _check_lattice(lattice)
    wc = 2.0 * cs / (min(ae, ah) * 1.0e3)          # 2 c_s / a in rad/ps
    top = 8.0 * wc
    panels = max(80, int(np.ceil(top * max(tmax, 1.0) / 1.5)))
    x, wt = np.polynomial.legendre.leggauss(20)
    edges = np.linspace(0.0, top, panels + 1)
    half = 0.5 * (edges[1] - edges[0])
    nodes = (edges[:-1, None] + half * (x[None, :] + 1.0)).ravel()
    weights = np.tile(half * wt, panels)
    return nodes, weights


def _check_temperature(T):
    """Return T as a float, raising ValueError unless it is finite and > 0 (kelvin)."""
    if isinstance(T, bool) or not isinstance(T, (int, float, np.integer, np.floating)):
        raise ValueError("T must be a real number")
    T = float(T)
    if not np.isfinite(T) or T <= 0.0:
        raise ValueError("T must be finite and positive")
    return T


def _oracle_phonon_propagator(t: np.ndarray, T: float, lattice: np.ndarray) -> np.ndarray:
    tt = np.asarray(t, dtype=float)
    if tt.ndim != 1 or not np.all(np.isfinite(tt)) or np.any(tt < 0.0):
        raise ValueError("t must be a one-dimensional array of finite values >= 0")
    T = _check_temperature(T)
    hbar, kb = 0.6582119569, 0.08617333262
    w, wt = _omega_nodes(lattice, float(tt.max()) if tt.size else 0.0)
    jw = _oracle_lattice_spectral_density(w, lattice)
    amp = jw / w ** 2 * wt
    coth = 1.0 / np.tanh(hbar * w / (2.0 * kb * T))
    phase = np.outer(tt, w)
    re = np.cos(phase) @ (amp * coth)
    im = -(np.sin(phase) @ amp)
    return np.array([re, im])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Normal: GaAs dot at 20 K, times across the decay of phi ---
        {
            "setup": "import numpy as np\n"
                     "t = np.array([0.0, 0.05, 0.2, 0.5, 1.0, 2.0, 4.0])\n"
                     "lat = np.array([7.0, -3.5, 5370.0, 5110.0, 3.5, 3.5 / 1.15])\n",
            "call": "phonon_propagator(t.copy(), 20.0, lat.copy())",
            "gold_call": "_oracle_phonon_propagator(t.copy(), 20.0, lat.copy())",
            "tol": 1e-8,
        },
        # --- Boundary: very low temperature, single time t = 0 ---
        {
            "setup": "import numpy as np\n"
                     "t = np.array([0.0])\n"
                     "lat = np.array([7.0, -3.5, 5370.0, 5110.0, 3.0, 3.0 / 1.15])\n",
            "call": "phonon_propagator(t.copy(), 0.5, lat.copy())",
            "gold_call": "_oracle_phonon_propagator(t.copy(), 0.5, lat.copy())",
            "tol": 1e-8,
        },
        # --- Edge: hot lattice and a large dot ---
        {
            "setup": "import numpy as np\n"
                     "t = np.array([0.0, 0.3, 0.9, 1.7, 3.3, 6.5, 12.0])\n"
                     "lat = np.array([7.0, -3.5, 5370.0, 5110.0, 5.0, 4.0])\n",
            "call": "phonon_propagator(t.copy(), 70.0, lat.copy())",
            "gold_call": "_oracle_phonon_propagator(t.copy(), 70.0, lat.copy())",
            "tol": 1e-8,
        },
        # --- Invalid: zero temperature ---
        {
            "setup": "import numpy as np\n"
                     "lat = np.array([7.0, -3.5, 5370.0, 5110.0, 3.5, 3.0])\n"
                     "def run_model():\n"
                     "    try:\n"
                     "        phonon_propagator(np.array([0.0, 1.0]), 0.0, lat.copy())\n"
                     "        return 0\n"
                     "    except ValueError:\n"
                     "        return 1\n"
                     "    except Exception:\n"
                     "        return 2\n"
                     "def run_gold():\n"
                     "    try:\n"
                     "        _oracle_phonon_propagator(np.array([0.0, 1.0]), 0.0, lat.copy())\n"
                     "        return 0\n"
                     "    except ValueError:\n"
                     "        return 1\n"
                     "    except Exception:\n"
                     "        return 2\n",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
