"""
Return the displacement and stress contributions that the temperature field alone produces in one layer for one axial mode, before any boundary or interface condition is enforced.

A temperature field that is not an affine function of position is generally incompatible with a stress-free state, so a thermoelastic problem splits naturally into a particular solution that absorbs the thermal term of the Navier equations and a complementary solution that repairs the boundary and interface conditions. The particular solution is generated by a scalar displacement potential whose Laplacian is the temperature difference times the thermal expansion coefficient times the factor that converts a free thermal strain into an equivalent dilatation for a constrained isotropic solid. Because every term of the temperature series is an eigenfunction of the Laplacian with a known eigenvalue, that potential is obtained without solving anything: each term is divided by its own eigenvalue, which is the sum of the squares of the radial and axial parameters and equals the mode decay rate divided by the layer's thermal diffusivity.




The displacements and stresses produced by the potential follow from differentiating it once or twice, so all five differentiated quantities can be written using only the value, the slope and the curvature of the radial eigenfunction. The three normal stresses carry one further term, because the constitutive law subtracts the free thermal dilatation directly, and that term is built from the temperature itself rather than from the potential: it is the only place in this step where the temperature field enters undifferentiated, which is why the temperature evaluated by the previous step is consumed here directly instead of being reconstructed from the modal data. The combination has a consequence worth noting: the axial normal stress of the particular solution is proportional to the squared radial parameter divided by the eigenvalue, so a radially uniform temperature mode contributes no axial stress at all through this route, and everything that appears in the axial direction then comes from the complementary solution alone.




The layer enters twice over, through the thermal expansion coefficient and Poisson's ratio in the potential, and through the shear modulus that converts the potential's strains into stresses. This is precisely the mismatch that drives the whole problem: two adjacent layers see the same temperature at their common interface, but they respond to it with different free expansions and different stiffnesses, and the difference between their particular solutions is the load that the complementary solution has to carry.

Returns
-------
np.ndarray of shape (6,), float: radial displacement (m), axial displacement (m), radial normal stress (Pa), hoop stress (Pa), axial normal stress (Pa) and shear stress (Pa) generated by the temperature field, in SI units.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def compute_thermal_source_terms(decay_rates: np.ndarray,
                                 eigenfunctions: np.ndarray,
                                 coefficients: np.ndarray, eta: float,
                                 temperature_rise: float,
                                 thermal_expansion: float, poisson: float,
                                 shear_modulus: float, layer: int,
                                 radius: float, time: float) -> np.ndarray:
    """Return the thermally generated displacements and stresses in one layer.

    Parameters
    ----------
    decay_rates : np.ndarray
        Array of shape (n_radial,) holding the decay rate in 1/s of every
        radial mode belonging to this axial mode.
    eigenfunctions : np.ndarray
        Array of shape (n_radial, n_layers, 3) holding the squared radial
        parameter and the two radial amplitudes of every layer.
    coefficients : np.ndarray
        Array of shape (n_radial,) holding the expansion amplitude in K of
        every radial mode.
    eta : float
        Axial eigenvalue of the mode in 1/m (eta > 0).
    temperature_rise : float
        Temperature of this layer above ambient in K at this radius and
        instant, contributed by this axial mode alone and stripped of its
        axial cosine factor, as returned by the temperature evaluation step.
    thermal_expansion : float
        Coefficient of thermal expansion of the layer in 1/K.
    poisson : float
        Poisson's ratio of the layer, -1 < poisson < 0.5.
    shear_modulus : float
        Shear modulus of the layer in Pa (shear_modulus > 0).
    layer : int
        Index of the layer, 0-based.
    radius : float
        Radial coordinate in m (radius >= 0).
    time : float
        Time since the start of the transient in s (time >= 0).

    Returns
    -------
    terms : np.ndarray
        Array of shape (6,) holding the radial displacement in m, the axial
        displacement in m, and the radial, hoop, axial and shear stresses in
        Pa that the temperature field alone produces, each stripped of its
        axial cosine or sine factor.

    Raises
    ------
    ValueError
        If any argument violates the constraints stated above; invalid input
        must raise ValueError rather than return a sentinel value.
    """
    return terms  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_compute_thermal_source_terms(decay_rates: np.ndarray,
                                         eigenfunctions: np.ndarray,
                                         coefficients: np.ndarray, eta: float,
                                         temperature_rise: float,
                                         thermal_expansion: float,
                                         poisson: float, shear_modulus: float,
                                         layer: int, radius: float,
                                         time: float) -> np.ndarray:
    # Local imports keep the oracle self-contained when the harness executes
    # it in isolation.
    import numpy as np
    from scipy.special import i0, i1, j0, j1, k0, k1, y0, y1

    decay_rates = np.asarray(decay_rates, dtype=float).ravel()
    eigenfunctions = np.asarray(eigenfunctions, dtype=float)
    coefficients = np.asarray(coefficients, dtype=float).ravel()

    n_radial = decay_rates.size
    if n_radial < 1:
        raise ValueError("decay_rates must hold at least one radial mode")
    if coefficients.size != n_radial:
        raise ValueError("decay_rates and coefficients must agree in length")
    if (eigenfunctions.ndim != 3 or eigenfunctions.shape[0] != n_radial
            or eigenfunctions.shape[2] != 3):
        raise ValueError("eigenfunctions must have shape (n_radial, n_layers, 3)")
    n_layers = eigenfunctions.shape[1]
    if not (isinstance(layer, (int, np.integer)) and not isinstance(layer, bool)
            and 0 <= int(layer) < n_layers):
        raise ValueError("layer must be an integer index of an existing layer")
    if not (isinstance(eta, (int, float, np.floating, np.integer))
            and not isinstance(eta, bool) and np.isfinite(eta) and float(eta) > 0.0):
        raise ValueError("eta must be a finite number > 0")
    if not (isinstance(shear_modulus, (int, float, np.floating, np.integer))
            and not isinstance(shear_modulus, bool) and np.isfinite(shear_modulus)
            and float(shear_modulus) > 0.0):
        raise ValueError("shear_modulus must be a finite number > 0")
    if not (isinstance(poisson, (int, float, np.floating, np.integer))
            and not isinstance(poisson, bool) and np.isfinite(poisson)
            and -1.0 < float(poisson) < 0.5):
        raise ValueError("poisson must be a finite number in (-1, 0.5)")
    if not (isinstance(thermal_expansion, (int, float, np.floating, np.integer))
            and not isinstance(thermal_expansion, bool)
            and np.isfinite(thermal_expansion)):
        raise ValueError("thermal_expansion must be a finite number")
    if not (isinstance(temperature_rise, (int, float, np.floating, np.integer))
            and not isinstance(temperature_rise, bool)
            and np.isfinite(temperature_rise)):
        raise ValueError("temperature_rise must be a finite number")
    for name, value in (("radius", radius), ("time", time)):
        if not (isinstance(value, (int, float, np.floating, np.integer))
                and not isinstance(value, bool)
                and np.isfinite(value) and float(value) >= 0.0):
            raise ValueError(f"{name} must be a finite number >= 0")

    layer = int(layer)
    eta = float(eta)
    radius = float(radius)
    time = float(time)
    shear_modulus = float(shear_modulus)
    poisson = float(poisson)
    temperature_rise = float(temperature_rise)

    def _radial_derivatives(mu, amp_a, amp_b, r):
        """Radial eigenfunction, slope and curvature at a radius."""
        if r == 0.0:
            return amp_a, 0.0, -0.5 * mu * amp_a
        if mu > 0.0:
            b = np.sqrt(mu)
            x = b * r
            value = amp_a * j0(x) + amp_b * y0(x)
            slope = -b * (amp_a * j1(x) + amp_b * y1(x))
        elif mu < 0.0:
            b = np.sqrt(-mu)
            x = b * r
            value = amp_a * i0(x) + amp_b * k0(x)
            slope = b * (amp_a * i1(x) - amp_b * k1(x))
        else:
            value = amp_a + amp_b * np.log(r)
            slope = amp_b / r
        return value, slope, -slope / r - mu * value

    # Free thermal dilatation of a constrained isotropic solid.
    modulus = thermal_expansion * (1.0 + poisson) / (1.0 - poisson)

    sum_value = sum_slope = sum_curvature = sum_slope_over_r = 0.0
    for n in range(n_radial):
        mu, amp_a, amp_b = (float(eigenfunctions[n, layer, 0]),
                            float(eigenfunctions[n, layer, 1]),
                            float(eigenfunctions[n, layer, 2]))
        value, slope, curvature = _radial_derivatives(mu, amp_a, amp_b, radius)
        weight = float(coefficients[n]) * np.exp(-float(decay_rates[n]) * time)
        # Dividing by the Laplacian eigenvalue inverts the potential equation.
        potential = weight / (mu + eta ** 2)
        sum_value += potential * value
        sum_slope += potential * slope
        sum_curvature += potential * curvature
        sum_slope_over_r += potential * (curvature if radius == 0.0 else slope / radius)

    # The undifferentiated thermal dilatation, supplied by the temperature step.
    dilatation = modulus * temperature_rise

    two_g = 2.0 * shear_modulus
    return np.array([
        -modulus * sum_slope,
        modulus * eta * sum_value,
        two_g * (-modulus * sum_curvature - dilatation),
        two_g * (-modulus * sum_slope_over_r - dilatation),
        two_g * (modulus * eta ** 2 * sum_value - dilatation),
        two_g * modulus * eta * sum_slope,
    ])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: copper core of the benchmark via (normal scenario) ---
        {
            "setup": """import numpy as np
decay_rates = np.array([5953.409648825929, 126964.8635947617])
eigenfunctions = np.array([
    [[-1.0342822695e+07, 1.0000000000e+00, 0.0000000000e+00],
     [ 6.7677263268e+09, 1.0260381408e+00, 1.3245291089e+00],
     [ 1.2975309035e+07, 1.0318116676e+00, 6.4857891790e-03]],
    [[ 1.0332599561e+09, 1.0000000000e+00, 0.0000000000e+00],
     [ 1.4558515135e+11, -1.5704275223e+01, -6.1412001866e+00],
     [ 1.5305520273e+09, -1.5301885862e+00, -8.2738012274e-01]]])
coefficients = np.array([126.22851522849304, 1.0875424964178686])
eta = 7853.981633974483
temperature_rise = 93.78680951538789
thermal_expansion = 17.0e-6
poisson = 0.35
shear_modulus = 110.0e9 / (2.0 * 1.35)
layer = 0
radius = 15.0e-6
time = 5.0e-5
""",
            "call": "compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time)",
            "gold_call": "_oracle_compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time)",
        },
        # --- Valid: silicon substrate at the same interface radius ---
        {
            "setup": """import numpy as np
decay_rates = np.array([5953.409648825929, 126964.8635947617])
eigenfunctions = np.array([
    [[-1.0342822695e+07, 1.0000000000e+00, 0.0000000000e+00],
     [ 6.7677263268e+09, 1.0260381408e+00, 1.3245291089e+00],
     [ 1.2975309035e+07, 1.0318116676e+00, 6.4857891790e-03]],
    [[ 1.0332599561e+09, 1.0000000000e+00, 0.0000000000e+00],
     [ 1.4558515135e+11, -1.5704275223e+01, -6.1412001866e+00],
     [ 1.5305520273e+09, -1.5301885862e+00, -8.2738012274e-01]]])
coefficients = np.array([126.22851522849304, 1.0875424964178686])
eta = 7853.981633974483
temperature_rise = 95.48172241367291
thermal_expansion = 2.6e-6
poisson = 0.28
shear_modulus = 170.0e9 / (2.0 * 1.28)
layer = 2
radius = 16.0e-6
time = 5.0e-5
""",
            "call": "compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time)",
            "gold_call": "_oracle_compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time)",
        },
        # --- Boundary: on the axis, where the slope vanishes ---
        {
            "setup": """import numpy as np
decay_rates = np.array([5953.409648825929])
eigenfunctions = np.array([[[-1.0342822695e+07, 1.0, 0.0]]])
coefficients = np.array([126.22851522849304])
eta = 7853.981633974483
temperature_rise = 93.73047671819296
thermal_expansion = 17.0e-6
poisson = 0.35
shear_modulus = 110.0e9 / (2.0 * 1.35)
layer = 0
radius = 0.0
time = 5.0e-5
""",
            "call": "compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time)",
            "gold_call": "_oracle_compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time)",
        },
        # --- Edge: a radially uniform mode, whose axial stress contribution vanishes ---
        {
            "setup": """import numpy as np
decay_rates = np.array([1.0e4])
eigenfunctions = np.array([[[0.0, 1.0, 0.0]]])
coefficients = np.array([100.0])
eta = 7853.981633974483
temperature_rise = 100.0
thermal_expansion = 2.6e-6
poisson = 0.28
shear_modulus = 170.0e9 / (2.0 * 1.28)
layer = 0
radius = 12.0e-6
time = 0.0
stress_scale = shear_modulus * abs(thermal_expansion) * abs(temperature_rise)
zero_scale = 1.0e-2 * stress_scale
comparison_scale = np.array([zero_scale, zero_scale, stress_scale,
                             stress_scale, zero_scale, zero_scale])
""",
            "call": "compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time) / comparison_scale",
            "gold_call": "_oracle_compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, eta, temperature_rise, thermal_expansion, poisson, shear_modulus, layer, radius, time) / comparison_scale",
        },
        # --- Invalid: Poisson's ratio outside the admissible interval ---
        {
            "setup": """import numpy as np
decay_rates = np.array([5953.4])
eigenfunctions = np.array([[[-1.0e7, 1.0, 0.0]]])
coefficients = np.array([126.0])
def run_model():
    try:
        compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, 7853.98, 90.0, 17.0e-6, 0.5, 4.0e10, 0, 1.0e-6, 0.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, 7853.98, 90.0, 17.0e-6, 0.5, 4.0e10, 0, 1.0e-6, 0.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: coefficients array of the wrong length ---
        {
            "setup": """import numpy as np
decay_rates = np.array([5953.4, 1.2e5])
eigenfunctions = np.array([[[-1.0e7, 1.0, 0.0]], [[1.0e9, 1.0, 0.0]]])
coefficients = np.array([126.0])
def run_model():
    try:
        compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, 7853.98, 90.0, 17.0e-6, 0.35, 4.0e10, 0, 1.0e-6, 0.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_compute_thermal_source_terms(decay_rates, eigenfunctions, coefficients, 7853.98, 90.0, 17.0e-6, 0.35, 4.0e10, 0, 1.0e-6, 0.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
