"""
Assemble the linear system whose solution is the set of complementary-solution amplitudes that restore interface continuity and a traction-free outer surface for one axial mode.

The complementary part of an axisymmetric thermoelastic field is generated by a single biharmonic scalar function, and for a field whose axial dependence is a fixed harmonic the general regular biharmonic solution in a cylinder is spanned by exactly four radial shapes for each layer: the modified Bessel functions I0(ηr) and K0(ηr), and the first-order modified Bessel functions multiplied by the scaled radius, ηr·I1(ηr) and ηr·K1(ηr), which is what raises a harmonic function to a biharmonic one. In each layer the biharmonic function is L = [E·I0(ηr) + F·K0(ηr) + P·ηr·I1(ηr) + Q·ηr·K1(ηr)]·sin(ηz), the complementary displacements are u_r = −∂²L/∂r∂z and u_z = 2(1 − ν)∇²L − ∂²L/∂z², and the complementary stresses are σ_rr = 2G·∂/∂z(ν∇²L − ∂²L/∂r²), σ_θθ = 2G·∂/∂z(ν∇²L − (1/r)·∂L/∂r), σ_zz = 2G·∂/∂z((2 − ν)∇²L − ∂²L/∂z²) and σ_rz = 2G·∂/∂r((1 − ν)∇²L − ∂²L/∂z²). The displacements and stresses that follow from that function involve only its radial derivatives and its Laplacian, and the Laplacian of L is 2η²[P·I0(ηr) − Q·K0(ηr)]·sin(ηz), so it involves only the amplitudes of the two radius-multiplied shapes, which is the algebraic reason the four amplitudes are not redundant.




On the axis the two singular shapes must be discarded, so a stack of layers carries four amplitudes each except the innermost, which carries two. The count is exactly matched by the conditions: every interface between two solid layers that are perfectly bonded supplies four, continuity of both displacement components and of the two tractions acting on a cylindrical surface, and the free outer surface supplies two more. Note which stresses are continuous and which are not: the traction components are, but the hoop and axial normal stresses are not, and their jumps across an interface are exactly what a mismatch in expansion coefficient and stiffness produces.




The thermal part enters only through the right-hand side. Rows run interface by interface from the axis outwards; each interface contributes, in this order, continuity of the radial displacement, the axial displacement, the radial normal stress and the shear stress, each written as the inner layer's complementary coefficients minus the outer layer's, with the outer layer's thermally generated term minus the inner layer's as the right-hand side. The last two rows are the radial normal stress and the shear stress on the outer surface, with minus the thermally generated term as the right-hand side. Columns run layer by layer from the axis outwards in the amplitude order E, F, P, Q, the innermost layer carrying only E and P. Displacement rows are in metres and stress rows in pascals, with the axial cosine or sine factor removed; because both layers see the same temperature there, that difference is a pure material mismatch. The system must be assembled and solved once per axial mode and once per instant, since the thermal right-hand side carries the decaying exponentials while the matrix depends only on the geometry, the elastic constants and the axial eigenvalue.

Returns
-------
np.ndarray of shape (4*n_layers-2, 4*n_layers-1), float: the coefficient matrix of the complementary amplitudes with the right-hand side appended as the final column, in SI units.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def assemble_love_system(radii: np.ndarray, poisson: np.ndarray,
                         shear_moduli: np.ndarray, eta: float,
                         thermal_terms: np.ndarray) -> np.ndarray:
    """Assemble the augmented linear system for the complementary amplitudes.

    Parameters
    ----------
    radii : np.ndarray
        Outer radius of each layer in m, shape (n_layers,), strictly
        increasing and positive.
    poisson : np.ndarray
        Poisson's ratio of each layer, shape (n_layers,), each in (-1, 0.5).
    shear_moduli : np.ndarray
        Shear modulus of each layer in Pa, shape (n_layers,), all positive.
    eta : float
        Axial eigenvalue of the mode in 1/m (eta > 0).
    thermal_terms : np.ndarray
        Array of shape (n_layers, 2, 6) holding, for every layer, the six
        thermally generated displacement and stress contributions evaluated
        at that layer's inner radius (index 0) and outer radius (index 1).

    Returns
    -------
    system : np.ndarray
        Array of shape (4 * n_layers - 2, 4 * n_layers - 1) holding the
        coefficient matrix with the right-hand side appended as its last
        column.

    Raises
    ------
    ValueError
        If any argument violates the constraints stated above; invalid input
        must raise ValueError rather than return a sentinel value.
    """
    return system  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_assemble_love_system(radii: np.ndarray, poisson: np.ndarray,
                                 shear_moduli: np.ndarray, eta: float,
                                 thermal_terms: np.ndarray) -> np.ndarray:
    # Local imports keep the oracle self-contained when the harness executes
    # it in isolation.
    import numpy as np
    from scipy.special import i0, i1, k0, k1

    radii = np.asarray(radii, dtype=float).ravel()
    poisson = np.asarray(poisson, dtype=float).ravel()
    shear_moduli = np.asarray(shear_moduli, dtype=float).ravel()
    thermal_terms = np.asarray(thermal_terms, dtype=float)

    n_layers = radii.size
    if n_layers < 1:
        raise ValueError("radii must hold at least one layer")
    if poisson.size != n_layers or shear_moduli.size != n_layers:
        raise ValueError("radii, poisson and shear_moduli must agree in length")
    if not np.all(np.isfinite(radii)) or radii[0] <= 0.0 or np.any(np.diff(radii) <= 0.0):
        raise ValueError("radii must be finite, positive and strictly increasing")
    if not np.all(np.isfinite(poisson)) or np.any(poisson <= -1.0) or np.any(poisson >= 0.5):
        raise ValueError("every Poisson's ratio must be finite and lie in (-1, 0.5)")
    if not np.all(np.isfinite(shear_moduli)) or np.any(shear_moduli <= 0.0):
        raise ValueError("shear_moduli must be finite and positive")
    if thermal_terms.shape != (n_layers, 2, 6):
        raise ValueError("thermal_terms must have shape (n_layers, 2, 6)")
    if not (isinstance(eta, (int, float, np.floating, np.integer))
            and not isinstance(eta, bool) and np.isfinite(eta) and float(eta) > 0.0):
        raise ValueError("eta must be a finite number > 0")

    eta = float(eta)

    def _shapes(radius, on_axis):
        """Rows of the biharmonic shapes and their derivatives at a radius."""
        x = eta * radius
        bess_i0, bess_i1, bess_k0, bess_k1 = i0(x), i1(x), k0(x), k1(x)
        shape = np.array([bess_i0, bess_k0, x * bess_i1, x * bess_k1])
        slope = eta * np.array([bess_i1, -bess_k1, x * bess_i0, -x * bess_k0])
        curvature = eta ** 2 * np.array([bess_i0 - bess_i1 / x,
                                         bess_k0 + bess_k1 / x,
                                         bess_i0 + x * bess_i1,
                                         -bess_k0 + x * bess_k1])
        laplacian = 2.0 * eta ** 2 * np.array([0.0, 0.0, bess_i0, -bess_k0])
        laplacian_slope = 2.0 * eta ** 3 * np.array([0.0, 0.0, bess_i1, bess_k1])
        rows = (shape, slope, curvature, laplacian, laplacian_slope)
        if on_axis:
            return tuple(row[[0, 2]] for row in rows)
        return rows

    widths = [2] + [4] * (n_layers - 1)
    offsets = np.cumsum([0] + widths)
    ndof = int(offsets[-1])
    system = np.zeros((ndof, ndof + 1))

    row = 0
    for i in range(n_layers - 1):
        radius = radii[i]
        f_a, fp_a, fpp_a, g_a, gp_a = _shapes(radius, i == 0)
        f_b, fp_b, fpp_b, g_b, gp_b = _shapes(radius, False)
        slice_a = slice(offsets[i], offsets[i + 1])
        slice_b = slice(offsets[i + 1], offsets[i + 2])
        term_a = thermal_terms[i, 1]
        term_b = thermal_terms[i + 1, 0]
        two_g_a = 2.0 * shear_moduli[i]
        two_g_b = 2.0 * shear_moduli[i + 1]

        # Continuity of radial displacement.
        system[row, slice_a] = -eta * fp_a
        system[row, slice_b] = eta * fp_b
        system[row, -1] = term_b[0] - term_a[0]
        row += 1
        # Continuity of axial displacement.
        system[row, slice_a] = 2.0 * (1.0 - poisson[i]) * g_a + eta ** 2 * f_a
        system[row, slice_b] = -(2.0 * (1.0 - poisson[i + 1]) * g_b + eta ** 2 * f_b)
        system[row, -1] = term_b[1] - term_a[1]
        row += 1
        # Continuity of radial normal stress.
        system[row, slice_a] = two_g_a * eta * (poisson[i] * g_a - fpp_a)
        system[row, slice_b] = -two_g_b * eta * (poisson[i + 1] * g_b - fpp_b)
        system[row, -1] = term_b[2] - term_a[2]
        row += 1
        # Continuity of shear stress.
        system[row, slice_a] = two_g_a * ((1.0 - poisson[i]) * gp_a + eta ** 2 * fp_a)
        system[row, slice_b] = -two_g_b * ((1.0 - poisson[i + 1]) * gp_b
                                           + eta ** 2 * fp_b)
        system[row, -1] = term_b[5] - term_a[5]
        row += 1

    last = n_layers - 1
    radius = radii[last]
    _f_o, fp_o, fpp_o, g_o, gp_o = _shapes(radius, last == 0)
    slice_o = slice(offsets[last], offsets[last + 1])
    two_g_o = 2.0 * shear_moduli[last]
    term_o = thermal_terms[last, 1]

    # Traction-free outer cylindrical surface.
    system[row, slice_o] = two_g_o * eta * (poisson[last] * g_o - fpp_o)
    system[row, -1] = -term_o[2]
    row += 1
    system[row, slice_o] = two_g_o * ((1.0 - poisson[last]) * gp_o + eta ** 2 * fp_o)
    system[row, -1] = -term_o[5]

    return system

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: benchmark three-layer via (normal scenario) ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 16.0e-6, 25.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
shear_moduli = np.array([110.0e9 / 2.7, 70.0e9 / 2.34, 170.0e9 / 2.56])
eta = 7853.981633974483
rng = np.random.default_rng(11)
thermal_terms = rng.normal(size=(3, 2, 6)) * np.array([1e-9, 1e-9, 1e8, 1e8, 1e8, 1e7])
""",
            "call": "assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
            "gold_call": "_oracle_assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
        },
        # --- Valid: a higher axial mode of the same stack ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 16.0e-6, 25.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
shear_moduli = np.array([110.0e9 / 2.7, 70.0e9 / 2.34, 170.0e9 / 2.56])
eta = 11.0 * np.pi / (2.0 * 200.0e-6)
rng = np.random.default_rng(3)
thermal_terms = rng.normal(size=(3, 2, 6)) * np.array([1e-9, 1e-9, 1e8, 1e8, 1e8, 1e7])
""",
            "call": "assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
            "gold_call": "_oracle_assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
        },
        # --- Boundary: a single layer, which has only the traction-free conditions ---
        {
            "setup": """import numpy as np
radii = np.array([25.0e-6])
poisson = np.array([0.28])
shear_moduli = np.array([170.0e9 / 2.56])
eta = 7853.981633974483
thermal_terms = np.zeros((1, 2, 6))
thermal_terms[0, 1] = np.array([1.0e-9, 2.0e-9, 3.0e8, 4.0e8, 5.0e8, 6.0e7])
""",
            "call": "assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
            "gold_call": "_oracle_assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
        },
        # --- Edge: a vanishing thermal load, which must give a homogeneous system ---
        {
            "setup": """import numpy as np
radii = np.array([2.5e-6, 2.8e-6, 10.0e-6])
poisson = np.array([0.35, 0.17, 0.28])
shear_moduli = np.array([110.0e9 / 2.7, 70.0e9 / 2.34, 170.0e9 / 2.56])
eta = np.pi / (2.0 * 50.0e-6)
thermal_terms = np.zeros((3, 2, 6))
""",
            "call": "assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
            "gold_call": "_oracle_assemble_love_system(radii, poisson, shear_moduli, eta, thermal_terms)",
        },
        # --- Invalid: thermal term array of the wrong shape ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 25.0e-6])
poisson = np.array([0.35, 0.28])
shear_moduli = np.array([4.0e10, 6.6e10])
thermal_terms = np.zeros((2, 6))
def run_model():
    try:
        assemble_love_system(radii, poisson, shear_moduli, 7853.98, thermal_terms)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_assemble_love_system(radii, poisson, shear_moduli, 7853.98, thermal_terms)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: an incompressible Poisson's ratio ---
        {
            "setup": """import numpy as np
radii = np.array([15.0e-6, 25.0e-6])
poisson = np.array([0.35, 0.5])
shear_moduli = np.array([4.0e10, 6.6e10])
thermal_terms = np.zeros((2, 2, 6))
def run_model():
    try:
        assemble_love_system(radii, poisson, shear_moduli, 7853.98, thermal_terms)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_assemble_love_system(radii, poisson, shear_moduli, 7853.98, thermal_terms)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
