"""
Solve the assembled interface system and return, for every layer, the four amplitudes of the biharmonic complementary solution in a fixed order.

The assembled system is small, dense and non-symmetric, with one row per scalar continuity or traction condition and one column per amplitude, and it is solved directly rather than iteratively. Its conditioning is set by the spread of the modified Bessel functions across the stack: the regular pair grows exponentially with the product of the axial eigenvalue and the radius while the singular pair decays, so for a tall via and a wide substrate annulus the entries can span many orders of magnitude even though the physical answer is perfectly well scaled. This is the practical reason the axial series is truncated at a modest number of modes; long before the terms become numerically negligible in magnitude they become numerically inaccessible in a naive basis.




Unpacking the solution vector requires knowing which amplitudes exist in which layer. The innermost layer, which contains the axis, keeps only the two regular shapes because the two singular shapes would produce unbounded displacement and stress at the centre of the metal, and dropping them is what makes the amplitude count match the condition count exactly. Returning a rectangular table in which the two absent amplitudes of the innermost layer are explicit zeros keeps the downstream evaluation of stresses uniform across layers, so that the same expression can be applied to the metal, the liner and the substrate without a special case.




Together with the particular solution generated by the thermal potential, these amplitudes complete the field for one axial mode at one instant. Nothing about them is iterative or approximate: the truncated field satisfies the equilibrium equations exactly, satisfies interface continuity and the traction-free outer surface exactly, and approximates only the initial temperature distribution, which is where the entire error of the method resides.

Returns
-------
np.ndarray of shape (n_layers, 4), float: the four complementary-solution amplitudes of every layer in SI units, with the singular amplitudes of the innermost layer set to zero.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def solve_love_coefficients(system: np.ndarray, n_layers: int) -> np.ndarray:
    """Solve the assembled system and return the amplitudes of every layer.

    Parameters
    ----------
    system : np.ndarray
        Array of shape (4 * n_layers - 2, 4 * n_layers - 1) holding the
        coefficient matrix with the right-hand side as its final column.
    n_layers : int
        Number of material layers in the stack (n_layers >= 1).

    Returns
    -------
    amplitudes : np.ndarray
        Array of shape (n_layers, 4) holding, for every layer, the amplitudes
        of the regular harmonic shape, the singular harmonic shape, the
        regular biharmonic shape and the singular biharmonic shape, in that
        order; the two singular amplitudes of the innermost layer are zero.

    Raises
    ------
    ValueError
        If any argument violates the constraints stated above, or if the
        coefficient matrix is singular; invalid input must raise ValueError
        rather than return a sentinel value.
    """
    return amplitudes  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_solve_love_coefficients(system: np.ndarray,
                                    n_layers: int) -> np.ndarray:
    # Local imports keep the oracle self-contained when the harness executes
    # it in isolation.
    import numpy as np

    if not (isinstance(n_layers, (int, np.integer)) and not isinstance(n_layers, bool)
            and int(n_layers) >= 1):
        raise ValueError("n_layers must be an integer >= 1")

    n_layers = int(n_layers)
    system = np.asarray(system, dtype=float)
    ndof = 4 * n_layers - 2
    if system.shape != (ndof, ndof + 1):
        raise ValueError("system must have shape (4*n_layers-2, 4*n_layers-1)")
    if not np.all(np.isfinite(system)):
        raise ValueError("system must be finite")

    matrix = system[:, :ndof]
    rhs = system[:, ndof]
    try:
        solution = np.linalg.solve(matrix, rhs)
    except np.linalg.LinAlgError as error:
        raise ValueError("the interface system is singular") from error

    # The innermost layer keeps only the two regular shapes.
    widths = [2] + [4] * (n_layers - 1)
    offsets = np.cumsum([0] + widths)
    amplitudes = np.zeros((n_layers, 4))
    for i in range(n_layers):
        block = solution[offsets[i]:offsets[i + 1]]
        if i == 0:
            amplitudes[i, 0] = block[0]
            amplitudes[i, 2] = block[1]
        else:
            amplitudes[i] = block

    return amplitudes

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: three-layer stack with a generic load (normal scenario) ---
        {
            "setup": """import numpy as np
rng = np.random.default_rng(5)
n_layers = 3
ndof = 4 * n_layers - 2
matrix = rng.normal(size=(ndof, ndof)) + 3.0 * np.eye(ndof)
rhs = rng.normal(size=(ndof, 1))
system = np.hstack([matrix, rhs])
""",
            "call": "solve_love_coefficients(system, n_layers)",
            "gold_call": "_oracle_solve_love_coefficients(system, n_layers)",
        },
        # --- Valid: four-layer stack including a barrier ---
        {
            "setup": """import numpy as np
rng = np.random.default_rng(17)
n_layers = 4
ndof = 4 * n_layers - 2
matrix = rng.normal(size=(ndof, ndof)) + 5.0 * np.eye(ndof)
rhs = rng.normal(size=(ndof, 1)) * 1.0e8
system = np.hstack([matrix, rhs])
""",
            "call": "solve_love_coefficients(system, n_layers)",
            "gold_call": "_oracle_solve_love_coefficients(system, n_layers)",
        },
        # --- Boundary: a single layer keeps only two amplitudes ---
        {
            "setup": """import numpy as np
n_layers = 1
system = np.array([[2.0, 1.0, 5.0],
                   [1.0, 3.0, 10.0]])
""",
            "call": "solve_love_coefficients(system, n_layers)",
            "gold_call": "_oracle_solve_love_coefficients(system, n_layers)",
        },
        # --- Edge: a zero right-hand side must give zero amplitudes ---
        {
            "setup": """import numpy as np
rng = np.random.default_rng(23)
n_layers = 3
ndof = 4 * n_layers - 2
matrix = rng.normal(size=(ndof, ndof)) + 4.0 * np.eye(ndof)
system = np.hstack([matrix, np.zeros((ndof, 1))])
""",
            "call": "solve_love_coefficients(system, n_layers)",
            "gold_call": "_oracle_solve_love_coefficients(system, n_layers)",
        },
        # --- Invalid: system shape inconsistent with the layer count ---
        {
            "setup": """import numpy as np
system = np.zeros((10, 11))
def run_model():
    try:
        solve_love_coefficients(system, 2)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_solve_love_coefficients(system, 2)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: a singular coefficient matrix ---
        {
            "setup": """import numpy as np
system = np.zeros((2, 3))
system[0, 0] = 1.0
system[1, 0] = 2.0
system[:, 2] = np.array([1.0, 3.0])
def run_model():
    try:
        solve_love_coefficients(system, 1)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_solve_love_coefficients(system, 1)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
