"""
Assemble the generalized internal residual and exact current-state tangent of one symmetric-laminate Q4BW element.

Use the source numerical integration rule and the nonlinear strain operators from the preceding step.

Include the extensional, bending, transverse-shear, thermal, and von Kármán geometric contributions consistently.

The tangent must be the analytical first derivative of the generalized internal residual with respect to the twenty generalized element variables.

Return the generalized residual, tangent, and current internal potential. Do not estimate the tangent by finite differences.

A nonlinear finite-element residual represents the imbalance generated by the current strain and stress state.

Newton-type solution methods require the consistent derivative of this residual. For von Kármán plate kinematics, this derivative contains both conventional constitutive terms and a geometric contribution produced by the current membrane force state, including thermal pre-stress.

Returns
-------
A tuple (residual, K_tangent, potential), where residual has shape (20,), K_tangent has shape (20,20), and potential is a native Python float.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def assemble_q4bw_tangent(
    a: float,
    b: float,
    A: np.ndarray,
    D: np.ndarray,
    As: np.ndarray,
    NT: np.ndarray,
    MT: np.ndarray,
    q: np.ndarray,
) -> tuple[
    np.ndarray,
    np.ndarray,
    float,
]:
    """Return internal residual, consistent tangent, and internal potential."""

    return (
        np.zeros(20, dtype=float),
        np.zeros((20, 20), dtype=float),
        0.0,
    )

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_assemble_q4bw_tangent(
    a: float,
    b: float,
    A: np.ndarray,
    D: np.ndarray,
    As: np.ndarray,
    NT: np.ndarray,
    MT: np.ndarray,
    q: np.ndarray,
):

    q = np.asarray(
        q,
        dtype=float,
    )

    gp = np.sqrt(
        3.0 / 5.0
    )

    gauss = np.array(
        [-gp, 0.0, gp],
        dtype=float,
    )

    weights = np.array(
        [
            5.0 / 9.0,
            8.0 / 9.0,
            5.0 / 9.0,
        ],
        dtype=float,
    )

    residual = np.zeros(
        20,
        dtype=float,
    )

    K = np.zeros(
        (20, 20),
        dtype=float,
    )

    potential = 0.0

    jacobian = (
        a * b / 4.0
    )

    for i, xi in enumerate(
        gauss
    ):

        for j, eta in enumerate(
            gauss
        ):

            x = (
                0.5 * a * xi
            )

            y = (
                0.5 * b * eta
            )

            weight = (
                weights[i]
                * weights[j]
                * jacobian
            )

            (
                epsilon0,
                kappa,
                gamma,
                Bepsilon,
                Bkappa,
                Bgamma,
            ) = _oracle_q4bw_point_kinematics(
                a,
                b,
                D,
                As,
                q,
                x,
                y,
            )

            N = (
                A @ epsilon0
                - NT
            )

            M = (
                D @ kappa
                - MT
            )

            Q = (
                As @ gamma
            )

            residual += (
                weight
                * (
                    Bepsilon.T @ N
                    + Bkappa.T @ M
                    + Bgamma.T @ Q
                )
            )

            K_local = (
                Bepsilon.T
                @ A
                @ Bepsilon
                +
                Bkappa.T
                @ D
                @ Bkappa
                +
                Bgamma.T
                @ As
                @ Bgamma
            )

            (
                Nw,
                Nwx,
                Nwy,
                Nphiy,
                Nphix,
                Bkappa_b,
                Bgamma_b,
            ) = _oracle_q4bw_bending_shapes(
                a,
                b,
                D,
                As,
                x,
                y,
            )

            K_geo = np.zeros(
                (20, 20),
                dtype=float,
            )

            K_geo[
                :12,
                :12,
            ] = (
                N[0]
                * np.outer(
                    Nwx,
                    Nwx,
                )
                +
                N[1]
                * np.outer(
                    Nwy,
                    Nwy,
                )
                +
                N[2]
                * (
                    np.outer(
                        Nwx,
                        Nwy,
                    )
                    +
                    np.outer(
                        Nwy,
                        Nwx,
                    )
                )
            )

            K += (
                weight
                * (
                    K_local
                    + K_geo
                )
            )

            potential += (
                weight
                * (
                    0.5
                    * epsilon0
                    @ A
                    @ epsilon0
                    +
                    0.5
                    * kappa
                    @ D
                    @ kappa
                    +
                    0.5
                    * gamma
                    @ As
                    @ gamma
                    -
                    epsilon0
                    @ NT
                    -
                    kappa
                    @ MT
                )
            )

    return (
        residual,
        K,
        float(potential),
    )

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {
            "setup": """
a=2.4
b=1.6
A=np.array([
[65281.52476946175,19980.10937164915,0.0],
[19980.10937164915,14616.71670598327,0.0],
[0.0,0.0,21953.51704911001]])
D=np.array([
[3481.6813210379605,1065.6058331546217,1292.1589332648687],
[1065.6058331546217,779.5582243191081,462.9215011685319],
[1292.1589332648687,462.9215011685319,1170.8542426192012]])
As=np.array([[2833.333333333334,0.0],[0.0,2500.0]])
NT=np.array([3.457656015440701,7.220169418829079,0.0])
MT=np.zeros(3)
q=np.array([
.018,.010,-.006,.027,.006,-.004,.041,-.003,.009,.022,-.005,.007,
.0015,-.0008,.0024,-.0011,.0032,.0017,.0011,.0013])
""",
            "call": """
assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "gold_call": """
_oracle_assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "tol": 5e-9,
        },
        {
            "setup": """
a=2.4
b=1.6
A=np.array([[50000.,12000.,0.],[12000.,18000.,0.],[0.,0.,15000.]])
D=np.array([[900.,180.,70.],[180.,500.,30.],[70.,30.,220.]])
As=np.array([[1800.,0.],[0.,1500.]])
NT=np.zeros(3)
MT=np.zeros(3)
q=np.zeros(20)
""",
            "call": """
assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "gold_call": """
_oracle_assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "tol": 5e-9,
        },
        {
            "setup": """
a=1.8
b=1.2
A=np.array([[42000.,9000.,0.],[9000.,16000.,0.],[0.,0.,13000.]])
D=np.array([[620.,100.,45.],[100.,310.,20.],[45.,20.,150.]])
As=np.array([[1400.,40.],[40.,1150.]])
NT=np.array([1.2,2.1,0.2])
MT=np.array([0.0,0.0,0.0])
q=np.array([
.010,.004,-.003,.014,.003,-.002,.022,-.002,.005,.012,-.003,.004,
.0008,-.0004,.0012,-.0006,.0018,.0009,.0007,.0008])
""",
            "call": """
assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "gold_call": """
_oracle_assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "tol": 5e-9,
        },
        {
            "setup": """
a=2.0
b=1.5
A=np.array([[70000.,16000.,0.],[16000.,22000.,0.],[0.,0.,20000.]])
D=np.array([[1100.,210.,-85.],[210.,620.,90.],[-85.,90.,280.]])
As=np.array([[2100.,-80.],[-80.,1700.]])
NT=np.array([2.7,4.4,-0.3])
MT=np.zeros(3)
q=np.array([
.013,.006,-.004,.020,.004,-.003,.031,-.003,.007,.016,-.004,.006,
.0010,-.0005,.0017,-.0008,.0023,.0012,.0009,.0010])
""",
            "call": """
assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "gold_call": """
_oracle_assemble_q4bw_tangent(a,b,A,D,As,NT,MT,q)
""",
            "tol": 5e-9,
        },
    ]
