"""
Construct the deterministic supervised and collocation datasets used to train the benchmark PCKAN surrogate. Cross the four prescribed kappa_1 values, four prescribed theta_1 values, and five benchmark European-put contracts to obtain exactly 80 rows. For each row, construct the six benchmark-scaled PCKAN input coordinates (S0/100, K/100, T, r, kappa_1/4, theta_1/0.12) and generate the supervised target using the frozen Step-01 Heston-limit FVSJ Fourier-cosine European-put pricer.



Return the training inputs, supervised put-price targets, an independent collocation-input copy, and the corresponding physical rows (K, T, kappa_1, theta_1). The ordering is kappa_1 slowest, theta_1 next, and contract fastest. This step performs only deterministic dataset construction. It does not apply tanh, evaluate Chebyshev polynomials, construct or initialize the PCKAN, evaluate the physics residual, train the network, or perform differential-evolution calibration.

The PCKAN calibration framework separates offline surrogate construction from the later online differential-evolution calibration. Before the PCKAN can be trained, supervised option-price observations must therefore be generated over a prescribed parameter domain using the pricing model established in Step 01.



For the deterministic benchmark, the varying model parameters are kappa_1 and theta_1. Their training grids are



    kappa_1 in linspace(0.8, 3.5, 4),



and



    theta_1 in linspace(0.02, 0.10, 4).



Each of the 16 parameter pairs is crossed with the five benchmark European-put contracts



    (K,T) =

    (90,0.25),

    (95,0.50),

    (100,0.75),

    (105,1.00),

    (110,1.50),



giving



    4 * 4 * 5 = 80



training observations.



For every observation, the physical quantities are mapped to the six benchmark-scaled PCKAN coordinates



    x =

    (S0/100,

     K/100,

     T,

     r,

     kappa_1/4,

     theta_1/0.12).



These coordinates are only deterministic input scalings. The paper's tanh transformation is not applied in this step; it belongs to the subsequent PCKAN/Chebyshev computation.



The supervised target associated with each row is the European-put value generated by the frozen Step-01 Heston-limit FVSJ Fourier-cosine pricing construction. Consequently, the training labels remain tied to the paper-based pricing model rather than to a Black-Scholes substitute or an independently implemented pricing approximation.



The benchmark uses the same 80 feature rows as physics collocation locations. The collocation array is nevertheless returned as an independent copy so that later computations can operate on it without aliasing the supervised-input array.



Rows are generated deterministically with kappa_1 varying slowest, theta_1 next, and the five contracts varying fastest. The accompanying physical-row array stores



    (K, T, kappa_1, theta_1)



for each observation.



This step performs dataset construction only. It does not apply tanh, evaluate second-kind Chebyshev polynomials, initialize or train the PCKAN, compute Black-Scholes PDE derivatives or residuals, freeze network parameters, or perform differential-evolution calibration.

Returns
-------
return train_inputs, train_prices, collocation_inputs, physical_rows
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def build_pckan_training_data(
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Build the deterministic 80-row PCKAN training and collocation dataset.

    Returns
    -------
    train_inputs : np.ndarray
        Float64 array of shape (80, 6) containing the benchmark-scaled
        PCKAN inputs before the tanh transformation.

    train_prices : np.ndarray
        Float64 array of shape (80,) containing the Step-01 Heston-limit
        FVSJ Fourier-cosine European-put prices.

    collocation_inputs : np.ndarray
        Float64 array of shape (80, 6), numerically equal to train_inputs
        but stored as an independent copy.

    physical_rows : np.ndarray
        Float64 array of shape (80, 4) with columns
        (K, T, kappa_1, theta_1).

    Notes
    -----
    Rows are ordered with kappa_1 varying slowest, theta_1 next, and
    contract varying fastest. This step does not apply tanh or evaluate
    the PCKAN.
    """
    return (
        np.empty((0, 6), dtype=np.float64),
        np.empty((0,), dtype=np.float64),
        np.empty((0, 6), dtype=np.float64),
        np.empty((0, 4), dtype=np.float64),
    )

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_build_pckan_training_data():
    import numpy as np

    # Reuse the Step-01 oracle implementation inside the Golden solution.
    pricer = _oracle_compute_heston_cos_put_prices

    spot = 100.0
    rate = 0.05
    sigma1 = 0.30
    rho1 = -0.5
    v0 = 0.04
    n_cos = 128
    trunc = 10.0

    kappas = np.linspace(0.8, 3.5, 4, dtype=np.float64)
    thetas = np.linspace(0.02, 0.10, 4, dtype=np.float64)
    contracts = np.array(
        [
            [90.0, 0.25],
            [95.0, 0.50],
            [100.0, 0.75],
            [105.0, 1.00],
            [110.0, 1.50],
        ],
        dtype=np.float64,
    )

    n_rows = int(kappas.size * thetas.size * contracts.shape[0])
    if n_rows != 80:
        raise RuntimeError("benchmark dataset must contain exactly 80 rows")

    train_inputs = np.empty((n_rows, 6), dtype=np.float64)
    train_prices = np.empty(n_rows, dtype=np.float64)
    physical_rows = np.empty((n_rows, 4), dtype=np.float64)

    row = 0
    for kappa in kappas:
        for theta in thetas:
            for strike, maturity in contracts:
                kappa_f = float(kappa)
                theta_f = float(theta)
                strike_f = float(strike)
                maturity_f = float(maturity)

                train_inputs[row, 0] = spot / 100.0
                train_inputs[row, 1] = strike_f / 100.0
                train_inputs[row, 2] = maturity_f
                train_inputs[row, 3] = rate
                train_inputs[row, 4] = kappa_f / 4.0
                train_inputs[row, 5] = theta_f / 0.12

                physical_rows[row, 0] = strike_f
                physical_rows[row, 1] = maturity_f
                physical_rows[row, 2] = kappa_f
                physical_rows[row, 3] = theta_f

                priced = pricer(
                    spot,
                    strike_f,
                    maturity_f,
                    rate,
                    kappa_f,
                    theta_f,
                    sigma1,
                    rho1,
                    v0,
                    n_cos,
                    trunc,
                )
                train_prices[row] = float(
                    np.asarray(priced, dtype=np.float64).reshape(-1)[0]
                )
                row += 1

    collocation_inputs = np.array(
        train_inputs,
        dtype=np.float64,
        copy=True,
    )

    return train_inputs, train_prices, collocation_inputs, physical_rows

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        # CASE 1 — shapes, dtypes, collocation equality, and copy semantics
        {
            "setup": (
                "import numpy as np\n"
                "train_inputs, train_prices, collocation_inputs, "
                "physical_rows = build_pckan_training_data()\n"
                "result = (\n"
                "    train_inputs.shape,\n"
                "    train_prices.shape,\n"
                "    collocation_inputs.shape,\n"
                "    physical_rows.shape,\n"
                "    train_inputs.dtype == np.float64,\n"
                "    train_prices.dtype == np.float64,\n"
                "    collocation_inputs.dtype == np.float64,\n"
                "    physical_rows.dtype == np.float64,\n"
                "    np.array_equal(train_inputs, collocation_inputs),\n"
                "    not np.shares_memory(train_inputs, collocation_inputs),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "((80, 6), (80,), (80, 6), (80, 4), "
                "True, True, True, True, True, True)"
            ),
        },

        # CASE 2 — first row and first supervised COS label
        {
            "setup": (
                "import numpy as np\n"
                "train_inputs, train_prices, collocation_inputs, "
                "physical_rows = build_pckan_training_data()\n"
                "result = (\n"
                "    physical_rows[0].tolist(),\n"
                "    train_inputs[0].tolist(),\n"
                "    float(train_prices[0]),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "([90.0, 0.25, 0.8, 0.02], "
                "[1.0, 0.9, 0.25, 0.05, "
                "0.2, 0.16666666666666669], "
                "0.6860470020764261)"
            ),
        },

        # CASE 3 — required ordering:
        # kappa slowest, theta next, contract fastest
        {
            "setup": (
                "import numpy as np\n"
                "train_inputs, train_prices, collocation_inputs, "
                "physical_rows = build_pckan_training_data()\n"
                "result = (\n"
                "    physical_rows[:5].tolist(),\n"
                "    physical_rows[5].tolist(),\n"
                "    physical_rows[20].tolist(),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "([[90.0, 0.25, 0.8, 0.02], "
                "[95.0, 0.5, 0.8, 0.02], "
                "[100.0, 0.75, 0.8, 0.02], "
                "[105.0, 1.0, 0.8, 0.02], "
                "[110.0, 1.5, 0.8, 0.02]], "
                "[90.0, 0.25, 0.8, 0.04666666666666667], "
                "[90.0, 0.25, 1.7000000000000002, 0.02])"
            ),
        },

        # CASE 4 — exact 4x4 parameter grid and ground truth excluded
        {
            "setup": (
                "import numpy as np\n"
                "train_inputs, train_prices, collocation_inputs, "
                "physical_rows = build_pckan_training_data()\n"
                "kappas = np.unique(physical_rows[:, 2])\n"
                "thetas = np.unique(physical_rows[:, 3])\n"
                "pairs = np.unique(physical_rows[:, 2:4], axis=0)\n"
                "ground_truth_present = bool(np.any(\n"
                "    np.all(\n"
                "        np.isclose(\n"
                "            pairs,\n"
                "            np.array([1.5, 0.04]),\n"
                "            rtol=0.0,\n"
                "            atol=1e-15,\n"
                "        ),\n"
                "        axis=1,\n"
                "    )\n"
                "))\n"
                "result = (\n"
                "    kappas.tolist(),\n"
                "    thetas.tolist(),\n"
                "    ground_truth_present,\n"
                "    int(pairs.shape[0]),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "([0.8, 1.7000000000000002, 2.6, 3.5], "
                "[0.02, 0.04666666666666667, "
                "0.07333333333333333, 0.1], "
                "False, 16)"
            ),
        },

        # CASE 5 — representative first/middle/last labels.
        # Round only for this regression test to avoid sub-ULP
        # platform differences in the COS calculation.
        {
            "setup": (
                "import numpy as np\n"
                "train_inputs, train_prices, collocation_inputs, "
                "physical_rows = build_pckan_training_data()\n"
                "result = (\n"
                "    round(float(train_prices[0]), 14),\n"
                "    round(float(train_prices[40]), 14),\n"
                "    round(float(train_prices[-1]), 14),\n"
                "    physical_rows[40].tolist(),\n"
                "    physical_rows[-1].tolist(),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "(0.68604700207643, "
                "0.58790022730786, "
                "15.4262978631849, "
                "[90.0, 0.25, 2.6, 0.02], "
                "[110.0, 1.5, 3.5, 0.1])"
            ),
        },

        # CASE 6 — raw benchmark scaling and no tanh in Step 02
        {
            "setup": (
                "import numpy as np\n"
                "train_inputs, train_prices, collocation_inputs, "
                "physical_rows = build_pckan_training_data()\n"
                "result = (\n"
                "    float(train_inputs[0, 0]),\n"
                "    float(train_inputs[0, 1]),\n"
                "    float(train_inputs[0, 4]),\n"
                "    float(train_inputs[0, 5]),\n"
                "    bool(train_inputs[0, 0] == 1.0),\n"
                "    bool(np.isclose(\n"
                "        train_inputs[0, 0],\n"
                "        np.tanh(1.0),\n"
                "        rtol=0.0,\n"
                "        atol=1e-15,\n"
                "    )),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "(1.0, 0.9, 0.2, "
                "0.16666666666666669, True, False)"
            ),
        },
    ]
