"""
Deterministic physics-informed training of the benchmark PCKAN

(Zhang et al., Mathematics 2026, 14, 1529).



This step trains the fixed PCKAN architecture defined by the preceding steps using the 80-row supervised Heston-limit FVSJ COS pricing dataset and the corresponding collocation inputs. The model is initialized deterministically with torch.manual_seed(0), with the CKAN coefficient tensor drawn first, the linear readout weights drawn second, and the scalar output bias initialized to zero.



Training uses full-batch Adam for exactly 500 parameter updates with learning rate 1e-3, beta1=0.9, beta2=0.999, and eps=1e-8. No learning-rate decay, minibatching, shuffling, or differential-evolution calibration is performed in this step.



The training objective combines the supervised pricing mean-squared error with the Black-Scholes physics-residual mean-squared error using physics weight 0.1. The physics residual follows the time-to-maturity convention established in Step 04, uses sigma_phys=0.2, and applies the required chain-rule factors for the S0/100 network coordinate. Automatic differentiation remains connected through the first- and second-order derivatives so that the physics term contributes gradients to the PCKAN parameters.



After the 500th Adam update, predictions and all reported loss components are recomputed from the final trained parameters. The function returns the trained CKAN coefficients, readout weights, scalar output bias, final training-set predictions, data MSE, physics MSE, and total physics-informed loss. Differential-evolution calibration is deferred to the subsequent step.

The Physics-Informed Chebyshev Kolmogorov–Arnold Network (PCKAN) combines supervised option-price approximation with a financial physics constraint. In this benchmark, the supervised targets are the Heston-limit FVSJ European-put prices generated by the COS pricing stage; the Black-Scholes equation is used only as a physics regularizer and is not substituted for the FVSJ pricing model.



The PCKAN receives the six benchmark-scaled coordinates



(S0/100, K/100, T, r, kappa_1/4, theta_1/0.12).



Each coordinate is transformed by tanh and expanded through order 3 using second-kind Chebyshev polynomials. The eight hidden CKAN coordinates are obtained by summing the corresponding trainable Chebyshev-edge contributions, and a trainable linear readout produces the scalar option-price prediction.



The supervised component of the objective is the mean squared pricing error



L_data = mean[(V_pred - V_target)^2].



The physics component is constructed from the Black-Scholes PDE residual under the benchmark's time-to-maturity convention,



R = r V - V_T - r S V_S - (1/2) sigma_phys^2 S^2 V_SS,



with sigma_phys = sqrt(v0) = 0.2. Because the network receives S0/100 rather than physical spot directly, differentiation with respect to physical spot requires the chain-rule transformations



V_S = (1/100) V_x0



and



V_SS = (1/10000) V_x0x0.



The physics loss is the mean squared residual,



L_phys = mean[R^2],



and the benchmark training objective is



L_total = L_data + 0.1 L_phys.



The first- and second-order derivatives used in L_phys must remain connected to the PCKAN parameters through automatic differentiation. Detaching the residual before backpropagation would eliminate the intended physics-informed contribution to training.



The benchmark trains all CKAN coefficients, linear readout weights, and the scalar output bias jointly using full-batch Adam for exactly 500 updates. Initialization is deterministic: torch.manual_seed(0) is set immediately before drawing the CKAN coefficient tensor and then the readout weights, while the output bias starts at zero.



After update 500, the model parameters are frozen and the predictions, data MSE, physics MSE, and total loss are recomputed from those final parameters. These frozen parameters form the surrogate subsequently used for differential-evolution calibration; no calibration occurs during this training step.

Returns
-------
return W_hat, W_out, b_out, predictions, data_mse, physics_mse, total_loss
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def train_pckan(
    train_inputs: np.ndarray,
    train_prices: np.ndarray,
    collocation_inputs: np.ndarray,
) -> Tuple[
    np.ndarray,
    np.ndarray,
    float,
    np.ndarray,
    float,
    float,
    float,
]:
    """
    Train the deterministic physics-informed PCKAN for exactly 500
    full-batch Adam updates.

    Parameters
    ----------
    train_inputs : np.ndarray
        Benchmark-scaled supervised inputs with shape (80, 6).
    train_prices : np.ndarray
        Heston-limit FVSJ COS target put prices with shape (80,).
    collocation_inputs : np.ndarray
        Physics collocation inputs with shape (80, 6).

    Returns
    -------
    W_hat : np.ndarray
        Trained CKAN coefficient tensor with shape (8, 6, 4).
    W_out : np.ndarray
        Trained linear readout weights with shape (8,).
    b_out : float
        Trained scalar output bias.
    predictions : np.ndarray
        Final post-update training predictions with shape (80,).
    data_mse : float
        Final supervised pricing mean-squared error.
    physics_mse : float
        Final mean-squared Black-Scholes physics residual.
    total_loss : float
        Final objective equal to data_mse + 0.1 * physics_mse.

    Raises
    ------
    ValueError
        If train_inputs does not have shape (80, 6), train_prices does not
        have shape (80,), collocation_inputs does not have shape (80, 6),
        or any supplied input contains a non-finite value.
    """
    return (
        np.empty((8, 6, 4), dtype=np.float64),
        np.empty((8,), dtype=np.float64),
        0.0,
        np.empty((train_inputs.shape[0],), dtype=np.float64),
        0.0,
        0.0,
        0.0,
    )

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_train_pckan(train_inputs, train_prices, collocation_inputs):
    import numpy as np

    X_tr = np.asarray(train_inputs, dtype=np.float64)
    y_tr = np.asarray(train_prices, dtype=np.float64)
    X_col = np.asarray(collocation_inputs, dtype=np.float64)

    # ---------------------------------------------------------
    # Validation
    # ---------------------------------------------------------
    if X_tr.ndim != 2 or X_tr.shape[1] != 6:
        raise ValueError("train_inputs must have shape (n, 6)")

    if X_col.ndim != 2 or X_col.shape[1] != 6:
        raise ValueError("collocation_inputs must have shape (n, 6)")

    if y_tr.ndim != 1:
        raise ValueError("train_prices must be 1-D")

    if X_tr.shape[0] != y_tr.shape[0]:
        raise ValueError(
            "train_inputs and train_prices length mismatch"
        )

    if X_col.shape[0] != X_tr.shape[0]:
        raise ValueError(
            "collocation_inputs and train_inputs length mismatch"
        )

    if not np.all(np.isfinite(X_tr)):
        raise ValueError("train_inputs must be finite")

    if not np.all(np.isfinite(y_tr)):
        raise ValueError("train_prices must be finite")

    if not np.all(np.isfinite(X_col)):
        raise ValueError("collocation_inputs must be finite")

    # ---------------------------------------------------------
    # Deterministic benchmark initialization
    #
    # Exact serialization of the Step-03 PyTorch float64 seed-0
    # initialization:
    #   torch.manual_seed(0)
    #   W_hat = torch.randn((8, 6, 4), dtype=torch.float64) * 0.01
    #   W_out = torch.randn((8,), dtype=torch.float64) * 0.01
    #   b_out = 0.0
    #
    # These constants make the Step-05 oracle self-contained while
    # preserving exactly the same initialization convention as Step 03.
    # ---------------------------------------------------------
    W_hat = np.array(
        [
            -0.023104118002341766,
            -0.003732508612577643,
            -0.010608166785462862,
            0.009995093547811761,
            -0.008840250045832653,
            -0.012755469302148053,
            -0.00623224579866079,
            -0.008664416019125773,
            -0.012956271403277857,
            0.015236316231063501,
            0.0032366056649837383,
            0.020177260314861084,
            0.011357423400213507,
            -0.01226881339001083,
            0.0007138847120511694,
            0.003380174030507378,
            0.0015351883531544036,
            -0.006332746088675096,
            -0.012609246557194385,
            -0.00726951062065411,
            -0.00019964750907762652,
            0.002102998901016947,
            0.0017718935139366585,
            -0.00830510051008449,
            0.010111892074660187,
            -0.002426793824588577,
            -0.007730112772958181,
            -0.01595181488078307,
            -0.006870036940435463,
            0.014880743158106724,
            -0.004484158047114511,
            -0.008910030351707376,
            -0.0009174174090816388,
            0.005563227724483105,
            -9.446277892507904e-05,
            -0.012176877791068701,
            -0.012654653080284904,
            -0.011195351830271254,
            0.011664857205254855,
            0.009262324572968777,
            0.006539244967350809,
            0.0014821544548810084,
            -0.011461092231976014,
            0.018727763768553417,
            -0.0030991497424174676,
            0.0024018023403782536,
            -0.013487610270963771,
            0.002443990933828689,
            -0.03145296273123133,
            -0.0011373127757597257,
            0.01696202480514395,
            -0.006652034805381666,
            -0.00587222598359879,
            0.02832104167511146,
            0.009039973689601122,
            0.00947836532432321,
            -0.013809366518587675,
            -0.020547510174380234,
            0.0004757655385024031,
            -0.0038556879759337023,
            -0.0027503491919216158,
            0.00886589630091246,
            0.014857416299332184,
            -7.855617400547969e-05,
            -0.011287986397999446,
            -0.0009376858138313218,
            0.00998343579451126,
            -0.0008262167465143246,
            0.0018253194918016991,
            0.009509038124935927,
            -0.017631617835191397,
            0.010107316682629281,
            0.007494883300195011,
            -0.00560555214098722,
            0.0007424681473465156,
            0.019936457271364453,
            0.004498653398445938,
            0.015531453898519594,
            0.0005398594882285299,
            0.014744415042312725,
            -0.007012303945657874,
            0.00326255796287562,
            -0.008738640219900763,
            0.003941269998738486,
            0.008915170821381017,
            0.011731555158319225,
            -0.00394903405651056,
            0.004464225721184322,
            -0.001726536808458421,
            0.009751203451810781,
            0.004164541966117019,
            -0.004986513835421579,
            -0.0047546981991056095,
            0.0028634406331767815,
            -0.013181871188381728,
            0.008887144617352294,
            -0.005918823592164964,
            0.006195092629710962,
            -0.014872950971304264,
            0.013626823808042957,
            0.004188191254194787,
            0.003434148780975708,
            -0.003485998065004807,
            -0.012090699446332277,
            0.0020710026569896174,
            -0.0011727393443191467,
            -0.00017436740784596905,
            -0.0024317130976865137,
            -0.004394223636068548,
            0.02714466016601841,
            -0.014631736798004056,
            0.004357325629861231,
            -0.005312331855486973,
            -0.0013408449243234942,
            0.0136427245242356,
            0.002327705351743837,
            0.011064458833206278,
            0.008527354795918417,
            -0.006301719953003105,
            -0.006019872001874334,
            0.011149190519421119,
            -0.0055598980336551964,
            0.005331687087503058,
            -0.0018787474948239727,
            0.003993685890598303,
            -0.006760874461803967,
            0.01662168703751691,
            -0.0060368393719886625,
            0.000534191942795709,
            0.0001342750276927035,
            -0.015406177939388192,
            -0.004819087554044004,
            0.007623209434576803,
            0.0021679229361763427,
            -0.00478912061625386,
            -0.002578760451372613,
            0.002631423185835337,
            -0.004053288789025133,
            -0.0007271235379509131,
            -0.0013985617336865128,
            0.00785995459350369,
            -0.020568571650881627,
            -0.006711099455038105,
            -0.0040096823326862124,
            0.0009346980467841958,
            -0.0064879924513363985,
            -0.00679095884649028,
            -0.0008377947239717037,
            -0.013083177047571642,
            -0.0141739733683466,
            0.003237499278733888,
            -0.012819324564954783,
            -0.004117908858856197,
            -0.011128682991908617,
            -0.003920249549198018,
            -0.004522967443547727,
            0.010930261889419516,
            -0.001639182226412006,
            -0.0020150312169022844,
            -0.018609565968157826,
            0.008942415239486997,
            -0.019664187911247126,
            0.014864847606394494,
            -0.001982554880893235,
            -0.016795171874434075,
            0.013863200736888246,
            -0.030465827500791125,
            -0.00598281249533576,
            0.0011680004036673396,
            0.00029905566085561,
            0.008536195134028616,
            0.009084886688785414,
            -0.011090488038575444,
            -0.00624538324560581,
            0.00136098548491325,
            -0.004218880327975954,
            -0.0010303497974091277,
            -0.012868901361560705,
            0.014145046448860667,
            0.004472847452382745,
            -0.002069050342565235,
            0.011506583648125866,
            -0.005611667183722734,
            0.00042508018555383173,
            0.008043963540244156,
            0.009072091619347682,
            -0.0021521353161099454,
            0.005114427131934867,
            0.00807731564311178,
            -0.013327491869404214,
            -0.002090149318312048,
            -0.006750742601943351,
        ],
        dtype=np.float64,
    ).reshape(8, 6, 4)
    W_out = np.array(
        [
            -0.0017502054629307568,
            0.0035290023830520153,
            -0.008974748047588913,
            -0.00652325833004202,
            -0.0006868076558889425,
            -0.022581728431474914,
            0.008445572500753966,
            -0.01264403375116388,
        ],
        dtype=np.float64,
    )
    b_out = 0.0

    assert W_hat[0, 0, 0] == -0.023104118002341766
    assert W_hat[7, 5, 3] == -0.006750742601943351
    assert W_out[0] == -0.0017502054629307568
    assert W_out[7] == -0.01264403375116388

    # ---------------------------------------------------------
    # Chebyshev basis
    # ---------------------------------------------------------
    def basis(x):
        z = np.tanh(x)

        u0 = np.ones_like(z)
        u1 = 2.0 * z
        u2 = 4.0 * z * z - 1.0
        u3 = 8.0 * z * z * z - 4.0 * z

        return np.stack(
            (u0, u1, u2, u3),
            axis=-1,
        )

    # ---------------------------------------------------------
    # Basis + first/second x derivatives
    # ---------------------------------------------------------
    def basis_with_derivatives(x):
        z = np.tanh(x)

        zp = 1.0 - z * z
        zpp = -2.0 * z * zp

        u0 = np.ones_like(z)
        u1 = 2.0 * z
        u2 = 4.0 * z * z - 1.0
        u3 = 8.0 * z * z * z - 4.0 * z

        U = np.stack(
            (u0, u1, u2, u3),
            axis=-1,
        )

        # dU / dz
        uz0 = np.zeros_like(z)
        uz1 = np.full_like(z, 2.0)
        uz2 = 8.0 * z
        uz3 = 24.0 * z * z - 4.0

        Uz = np.stack(
            (uz0, uz1, uz2, uz3),
            axis=-1,
        )

        # d2U / dz2
        uzz0 = np.zeros_like(z)
        uzz1 = np.zeros_like(z)
        uzz2 = np.full_like(z, 8.0)
        uzz3 = 48.0 * z

        Uzz = np.stack(
            (uzz0, uzz1, uzz2, uzz3),
            axis=-1,
        )

        dU = Uz * zp[..., None]

        d2U = (
            Uzz * (zp[..., None] ** 2)
            + Uz * zpp[..., None]
        )

        return U, dU, d2U

    # ---------------------------------------------------------
    # Forward
    # ---------------------------------------------------------
    def forward(x):
        U = basis(x)

        h = np.einsum(
            "qpn,bpn->bq",
            W_hat,
            U,
        )

        return (
            np.einsum("bq,q->b", h, W_out)
            + b_out
        )

    # ---------------------------------------------------------
    # Physics quantities and residual
    # ---------------------------------------------------------
    def physics_components(x):
        U, dU, d2U = basis_with_derivatives(x)

        h = np.einsum(
            "qpn,bpn->bq",
            W_hat,
            U,
        )

        V = (
            np.einsum("bq,q->b", h, W_out)
            + b_out
        )

        dV_dx0 = np.einsum(
            "qpn,bpn,q->b",
            W_hat,
            dU,
            W_out,
        )

        # Only feature 0 derivative is required here.
        # Mask all other feature derivatives.
        dU0 = np.zeros_like(dU)
        dU0[:, 0, :] = dU[:, 0, :]

        d2U0 = np.zeros_like(d2U)
        d2U0[:, 0, :] = d2U[:, 0, :]

        dV_dx0 = np.einsum(
            "qpn,bpn,q->b",
            W_hat,
            dU0,
            W_out,
        )

        d2V_dx0 = np.einsum(
            "qpn,bpn,q->b",
            W_hat,
            d2U0,
            W_out,
        )

        dU2 = np.zeros_like(dU)
        dU2[:, 2, :] = dU[:, 2, :]

        dV_dx2 = np.einsum(
            "qpn,bpn,q->b",
            W_hat,
            dU2,
            W_out,
        )

        dV_dS = dV_dx0 / 100.0
        d2V_dS2 = d2V_dx0 / 10000.0
        dV_dT = dV_dx2

        S = 100.0 * x[:, 0]
        r = x[:, 3]

        sigma_phys = 0.2

        residual = (
            r * V
            - dV_dT
            - r * S * dV_dS
            - 0.5
            * (sigma_phys ** 2)
            * (S ** 2)
            * d2V_dS2
        )

        return V, residual

    # ---------------------------------------------------------
    # Residual expressed as basis operator.
    #
    # This lets us calculate exact parameter gradients using
    # NumPy rather than autograd.
    # ---------------------------------------------------------
    def residual_basis(x):
        U, dU, d2U = basis_with_derivatives(x)

        r = x[:, 3]
        S = 100.0 * x[:, 0]

        A = r[:, None, None] * U

        # - dV/dT
        A[:, 2, :] -= dU[:, 2, :]

        # - r*S*dV/dS
        A[:, 0, :] -= (
            r[:, None]
            * S[:, None]
            * dU[:, 0, :]
            / 100.0
        )

        # - 0.5*sigma^2*S^2*d2V/dS2
        A[:, 0, :] -= (
            0.5
            * (0.2 ** 2)
            * (S[:, None] ** 2)
            * d2U[:, 0, :]
            / 10000.0
        )

        return U, A, r

    # ---------------------------------------------------------
    # Adam state
    # ---------------------------------------------------------
    m_Wh = np.zeros_like(W_hat)
    v_Wh = np.zeros_like(W_hat)

    m_Wo = np.zeros_like(W_out)
    v_Wo = np.zeros_like(W_out)

    m_b = np.float64(0.0)
    v_b = np.float64(0.0)

    lr = 1e-3
    beta1 = 0.9
    beta2 = 0.999
    eps = 1e-8

    n_train = X_tr.shape[0]
    n_col = X_col.shape[0]

    # ---------------------------------------------------------
    # 500 Adam iterations
    # ---------------------------------------------------------
    for step in range(1, 501):

        # =========================
        # DATA LOSS
        # =========================
        U_tr = basis(X_tr)

        h_tr = np.einsum(
            "qpn,bpn->bq",
            W_hat,
            U_tr,
        )

        preds = (
            np.einsum(
                "bq,q->b",
                h_tr,
                W_out,
            )
            + b_out
        )

        err = preds - y_tr

        coeff_data = (
            2.0 * err / float(n_train)
        )

        grad_Wh_data = np.einsum(
            "b,q,bpn->qpn",
            coeff_data,
            W_out,
            U_tr,
        )

        grad_Wo_data = np.einsum(
            "b,bq->q",
            coeff_data,
            h_tr,
        )

        grad_b_data = np.sum(coeff_data)

        # =========================
        # PHYSICS LOSS
        # =========================
        U_col, A, r_col = residual_basis(X_col)

        h_col = np.einsum(
            "qpn,bpn->bq",
            W_hat,
            U_col,
        )

        V_col = (
            np.einsum(
                "bq,q->b",
                h_col,
                W_out,
            )
            + b_out
        )

        h_res = np.einsum(
            "qpn,bpn->bq",
            W_hat,
            A,
        )

        residual = (
            np.einsum(
                "bq,q->b",
                h_res,
                W_out,
            )
            + r_col * b_out
        )

        coeff_phys = (
            2.0 * residual / float(n_col)
        )

        grad_Wh_phys = np.einsum(
            "b,q,bpn->qpn",
            coeff_phys,
            W_out,
            A,
        )

        grad_Wo_phys = np.einsum(
            "b,bq->q",
            coeff_phys,
            h_res,
        )

        grad_b_phys = np.sum(
            coeff_phys * r_col
        )

        # =========================
        # TOTAL GRADIENT
        # =========================
        grad_Wh = (
            grad_Wh_data
            + 0.1 * grad_Wh_phys
        )

        grad_Wo = (
            grad_Wo_data
            + 0.1 * grad_Wo_phys
        )

        grad_b = (
            grad_b_data
            + 0.1 * grad_b_phys
        )

        # =========================
        # ADAM — W_hat
        # =========================
        m_Wh = (
            beta1 * m_Wh
            + (1.0 - beta1) * grad_Wh
        )

        v_Wh = (
            beta2 * v_Wh
            + (1.0 - beta2)
            * (grad_Wh * grad_Wh)
        )

        m_Wh_hat = (
            m_Wh / (1.0 - beta1 ** step)
        )

        v_Wh_hat = (
            v_Wh / (1.0 - beta2 ** step)
        )

        W_hat -= (
            lr
            * m_Wh_hat
            / (np.sqrt(v_Wh_hat) + eps)
        )

        # =========================
        # ADAM — W_out
        # =========================
        m_Wo = (
            beta1 * m_Wo
            + (1.0 - beta1) * grad_Wo
        )

        v_Wo = (
            beta2 * v_Wo
            + (1.0 - beta2)
            * (grad_Wo * grad_Wo)
        )

        m_Wo_hat = (
            m_Wo / (1.0 - beta1 ** step)
        )

        v_Wo_hat = (
            v_Wo / (1.0 - beta2 ** step)
        )

        W_out -= (
            lr
            * m_Wo_hat
            / (np.sqrt(v_Wo_hat) + eps)
        )

        # =========================
        # ADAM — bias
        # =========================
        m_b = (
            beta1 * m_b
            + (1.0 - beta1) * grad_b
        )

        v_b = (
            beta2 * v_b
            + (1.0 - beta2)
            * (grad_b * grad_b)
        )

        m_b_hat = (
            m_b / (1.0 - beta1 ** step)
        )

        v_b_hat = (
            v_b / (1.0 - beta2 ** step)
        )

        b_out -= (
            lr
            * m_b_hat
            / (np.sqrt(v_b_hat) + eps)
        )

    # ---------------------------------------------------------
    # FINAL POST-UPDATE VALUES
    # ---------------------------------------------------------
    predictions = forward(X_tr)

    data_mse_f = np.mean(
        (predictions - y_tr) ** 2
    )

    _, residuals_f = physics_components(X_col)

    physics_mse_f = np.mean(
        residuals_f ** 2
    )

    total_loss_f = (
        data_mse_f
        + 0.1 * physics_mse_f
    )

    return (
        W_hat.astype(np.float64, copy=True),
        W_out.astype(np.float64, copy=True),
        float(b_out),
        predictions.astype(np.float64, copy=True),
        float(data_mse_f),
        float(physics_mse_f),
        float(total_loss_f),
    )

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        # -----------------------------------------------------
        # CASE 1
        # Full benchmark:
        # shapes, dtypes, finite outputs, scalar return types
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "Wh, Wo, b, preds, dm, pm, tl = train_pckan(ti, tp, ci)\n"
                "result = (\n"
                "    Wh.shape,\n"
                "    Wo.shape,\n"
                "    preds.shape,\n"
                "    Wh.dtype == np.float64,\n"
                "    Wo.dtype == np.float64,\n"
                "    preds.dtype == np.float64,\n"
                "    isinstance(b, float),\n"
                "    isinstance(dm, float),\n"
                "    isinstance(pm, float),\n"
                "    isinstance(tl, float),\n"
                "    bool(np.all(np.isfinite(Wh))),\n"
                "    bool(np.all(np.isfinite(Wo))),\n"
                "    bool(np.all(np.isfinite(preds))),\n"
                "    bool(np.isfinite(b)),\n"
                "    bool(np.isfinite(dm)),\n"
                "    bool(np.isfinite(pm)),\n"
                "    bool(np.isfinite(tl)),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "((8, 6, 4), (8,), (80,), "
                "True, True, True, "
                "True, True, True, True, "
                "True, True, True, True, True, True, True)"
            ),
        },

        # -----------------------------------------------------
        # CASE 2
        # Training changes parameters and is deterministic.
        #
        # No torch RNG reconstruction.
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "a = train_pckan(ti, tp, ci)\n"
                "b = train_pckan(ti, tp, ci)\n"
                "Wh, Wo, bias, preds, dm, pm, tl = a\n"
                "Wh2, Wo2, bias2, preds2, dm2, pm2, tl2 = b\n"
                "result = (\n"
                "    bool(np.any(np.abs(Wh) > 0.02)),\n"
                "    bool(np.any(np.abs(Wo) > 0.02)),\n"
                "    bool(bias != 0.0),\n"
                "    bool(np.array_equal(Wh, Wh2)),\n"
                "    bool(np.array_equal(Wo, Wo2)),\n"
                "    bool(np.array_equal(preds, preds2)),\n"
                "    bool(bias == bias2),\n"
                "    bool(dm == dm2),\n"
                "    bool(pm == pm2),\n"
                "    bool(tl == tl2),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "(True, True, True, True, True, "
                "True, True, True, True, True)"
            ),
        },

        # -----------------------------------------------------
        # CASE 3
        # Exact reported loss identity
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "Wh, Wo, b, preds, dm, pm, tl = train_pckan(ti, tp, ci)\n"
                "result = (\n"
                "    bool(np.isclose(\n"
                "        tl,\n"
                "        dm + 0.1 * pm,\n"
                "        rtol=0.0,\n"
                "        atol=1e-12,\n"
                "    )),\n"
                "    bool(dm >= 0.0),\n"
                "    bool(pm >= 0.0),\n"
                "    bool(tl >= 0.0),\n"
                ")"
            ),
            "call": "result",
            "gold_call": "(True, True, True, True)",
        },

        # -----------------------------------------------------
        # CASE 4
        # Recompute predictions and data MSE using NumPy only.
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "Wh, Wo, b, preds, dm, pm, tl = train_pckan(ti, tp, ci)\n"
                "\n"
                "z = np.tanh(ti)\n"
                "u0 = np.ones_like(z)\n"
                "u1 = 2.0 * z\n"
                "u2 = 4.0 * z * z - 1.0\n"
                "u3 = 8.0 * z * z * z - 4.0 * z\n"
                "U = np.stack((u0, u1, u2, u3), axis=-1)\n"
                "\n"
                "h = np.einsum('qpn,bpn->bq', Wh, U)\n"
                "yp = np.einsum('bq,q->b', h, Wo) + b\n"
                "dm_chk = float(np.mean((yp - tp) ** 2))\n"
                "\n"
                "result = (\n"
                "    bool(np.allclose(\n"
                "        preds, yp, rtol=0.0, atol=1e-12\n"
                "    )),\n"
                "    bool(np.isclose(\n"
                "        dm, dm_chk, rtol=0.0, atol=1e-12\n"
                "    )),\n"
                "    bool(np.isclose(\n"
                "        tl, dm + 0.1 * pm,\n"
                "        rtol=0.0, atol=1e-12\n"
                "    )),\n"
                ")"
            ),
            "call": "result",
            "gold_call": "(True, True, True)",
        },

        # -----------------------------------------------------
        # CASE 5
        # NumPy-only independent physics residual recomputation
        # from the returned trained parameters.
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "Wh, Wo, b, preds, dm, pm, tl = train_pckan(ti, tp, ci)\n"
                "\n"
                "x = np.asarray(ci, dtype=np.float64)\n"
                "z = np.tanh(x)\n"
                "zp = 1.0 - z * z\n"
                "zpp = -2.0 * z * zp\n"
                "\n"
                "u0 = np.ones_like(z)\n"
                "u1 = 2.0 * z\n"
                "u2 = 4.0 * z * z - 1.0\n"
                "u3 = 8.0 * z * z * z - 4.0 * z\n"
                "U = np.stack((u0, u1, u2, u3), axis=-1)\n"
                "\n"
                "uz0 = np.zeros_like(z)\n"
                "uz1 = np.full_like(z, 2.0)\n"
                "uz2 = 8.0 * z\n"
                "uz3 = 24.0 * z * z - 4.0\n"
                "Uz = np.stack((uz0, uz1, uz2, uz3), axis=-1)\n"
                "\n"
                "uzz0 = np.zeros_like(z)\n"
                "uzz1 = np.zeros_like(z)\n"
                "uzz2 = np.full_like(z, 8.0)\n"
                "uzz3 = 48.0 * z\n"
                "Uzz = np.stack((uzz0, uzz1, uzz2, uzz3), axis=-1)\n"
                "\n"
                "dU = Uz * zp[..., None]\n"
                "d2U = Uzz * (zp[..., None] ** 2) + Uz * zpp[..., None]\n"
                "\n"
                "h = np.einsum('qpn,bpn->bq', Wh, U)\n"
                "V = np.einsum('bq,q->b', h, Wo) + b\n"
                "\n"
                "dU0 = np.zeros_like(dU)\n"
                "dU0[:, 0, :] = dU[:, 0, :]\n"
                "d2U0 = np.zeros_like(d2U)\n"
                "d2U0[:, 0, :] = d2U[:, 0, :]\n"
                "dU2 = np.zeros_like(dU)\n"
                "dU2[:, 2, :] = dU[:, 2, :]\n"
                "\n"
                "Vx0 = np.einsum('qpn,bpn,q->b', Wh, dU0, Wo)\n"
                "Vx0x0 = np.einsum('qpn,bpn,q->b', Wh, d2U0, Wo)\n"
                "Vx2 = np.einsum('qpn,bpn,q->b', Wh, dU2, Wo)\n"
                "\n"
                "Vs = Vx0 / 100.0\n"
                "Vss = Vx0x0 / 10000.0\n"
                "Vt = Vx2\n"
                "\n"
                "S = 100.0 * x[:, 0]\n"
                "r = x[:, 3]\n"
                "\n"
                "R = (\n"
                "    r * V\n"
                "    - Vt\n"
                "    - r * S * Vs\n"
                "    - 0.5 * (0.2 ** 2) * (S ** 2) * Vss\n"
                ")\n"
                "\n"
                "pm_chk = float(np.mean(R ** 2))\n"
                "\n"
                "result = (\n"
                "    bool(np.all(np.isfinite(R))),\n"
                "    bool(pm > 0.0),\n"
                "    bool(np.isclose(\n"
                "        pm, pm_chk,\n"
                "        rtol=0.0, atol=1e-12\n"
                "    )),\n"
                "    bool(np.isclose(\n"
                "        tl, dm + 0.1 * pm_chk,\n"
                "        rtol=0.0, atol=1e-12\n"
                "    )),\n"
                ")"
            ),
            "call": "result",
            "gold_call": "(True, True, True, True)",
        },

        # -----------------------------------------------------
        # CASE 6
        # Determinism independent of external NumPy RNG state.
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "\n"
                "np.random.seed(123)\n"
                "_ = np.random.randn(100)\n"
                "a = train_pckan(ti, tp, ci)\n"
                "\n"
                "np.random.seed(999)\n"
                "_ = np.random.randn(50)\n"
                "b = train_pckan(ti, tp, ci)\n"
                "\n"
                "result = (\n"
                "    bool(np.array_equal(a[0], b[0])),\n"
                "    bool(np.array_equal(a[1], b[1])),\n"
                "    bool(a[2] == b[2]),\n"
                "    bool(np.array_equal(a[3], b[3])),\n"
                "    bool(a[4] == b[4]),\n"
                "    bool(a[5] == b[5]),\n"
                "    bool(a[6] == b[6]),\n"
                ")"
            ),
            "call": "result",
            "gold_call": (
                "(True, True, True, True, "
                "True, True, True)"
            ),
        },

        # -----------------------------------------------------
        # CASE 7
        # Invalid inputs must raise ValueError.
        # No torch import occurs before validation.
        # -----------------------------------------------------
        {
            "setup": (
                "import numpy as np\n"
                "ti, tp, ci, pr = build_pckan_training_data()\n"
                "statuses = []\n"
                "\n"
                "cases = [\n"
                "    dict(\n"
                "        train_inputs=ti[:, :5],\n"
                "        train_prices=tp,\n"
                "        collocation_inputs=ci,\n"
                "    ),\n"
                "    dict(\n"
                "        train_inputs=ti,\n"
                "        train_prices=tp[:-1],\n"
                "        collocation_inputs=ci,\n"
                "    ),\n"
                "    dict(\n"
                "        train_inputs=ti,\n"
                "        train_prices=tp,\n"
                "        collocation_inputs=ci[:-1],\n"
                "    ),\n"
                "    dict(\n"
                "        train_inputs=np.array(ti, copy=True),\n"
                "        train_prices=tp,\n"
                "        collocation_inputs=ci,\n"
                "    ),\n"
                "]\n"
                "\n"
                "cases[3]['train_inputs'][0, 0] = np.nan\n"
                "\n"
                "for kwargs in cases:\n"
                "    try:\n"
                "        train_pckan(**kwargs)\n"
                "        statuses.append(0)\n"
                "    except ValueError:\n"
                "        statuses.append(1)\n"
                "    except Exception:\n"
                "        statuses.append(2)\n"
            ),
            "call": "tuple(statuses)",
            "gold_call": "(1, 1, 1, 1)",
        },
    ]
