"""
Return the values of the B-spline basis of degree p and regularity r on the uniform mesh of nmesh unit elements covering [0, nmesh], at the given evaluation points. The basis is generated by the Cox-de Boor recursion on the open knot vector in which the two end knots 0 and nmesh appear p + 1 times and each interior integer knot appears p - r times, so that the splines are C^r across the interior knots; no other normalisation is applied. The basis functions are indexed from 0 in knot order and there are nmesh (p - r) + r + 1 of them (the number of knots, nmesh (p - r) + r + p + 2, minus p + 1). Points that coincide with an interior knot belong to the element on their right; the right end point belongs to the last element. Reject an invalid degree or regularity, nmesh < 1, and points outside [0, nmesh].

Isogeometric time discretisations use B-splines whose smoothness across the mesh is chosen independently of the polynomial degree: repeating an interior knot p - r times drops the continuity there to C^r. The Cox-de Boor recursion builds these functions from the knot vector alone, and every later matrix of the chain is an exact integral of products of these piecewise polynomials, so the basis has to be reproduced exactly, not approximately.

Returns
-------
A (nfun, npts) float64 array of basis values, functions along the first axis in knot order.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

# =============================================================================

def spline_basis_values(p, r, nmesh, tvals):
    """Return the values of the B-spline basis of degree p and regularity r on the uniform mesh
    of nmesh unit elements covering [0, nmesh], at the given evaluation points.

    Args:
        p (int): polynomial degree of the spline space, at least 1.
        r (int): regularity of the spline space, an integer with 0 <= r <= p - 1.
        nmesh (int): number of uniform mesh elements of unit width on [0, nmesh], at
            least 1.
        tvals (array_like of float): one-dimensional evaluation points in [0, nmesh].

    Returns:
        numpy.ndarray of shape (nfun, len(tvals)) with the values of every basis
        function at every point, where nfun = nmesh (p - r) + r + 1 (the open knot
        vector has nmesh (p - r) + r + p + 2 entries).

    Raises:
        ValueError: if p < 1 or r is outside 0 <= r <= p - 1.
        ValueError: if nmesh < 1 or a point lies outside [0, nmesh] or is not finite.
    """
    return None

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
from fractions import Fraction

def _check_pr(p, r):
    p = int(p)
    r = int(r)
    if p < 1 or r < 0 or r > p - 1:
        raise ValueError('degree p must be >= 1 and regularity r must satisfy 0 <= r <= p - 1')
    return (p, r)

def _padd(a, b):
    n = max(len(a), len(b))
    return [(a[i] if i < len(a) else Fraction(0)) + (b[i] if i < len(b) else Fraction(0)) for i in range(n)]

def _pmul(a, b):
    out = [Fraction(0)] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        if x == 0:
            continue
        for j, y in enumerate(b):
            out[i + j] += x * y
    return out

def _peval(a, x):
    s = Fraction(0)
    for c in reversed(a):
        s = s * x + c
    return s

def _knots(p, r, nmesh):
    return [Fraction(0)] * (p + 1) + sum(([Fraction(e)] * (p - r) for e in range(1, nmesh)), []) + [Fraction(nmesh)] * (p + 1)

def _bsplines(p, r, nmesh):
    ks = _knots(p, r, nmesh)
    cur = []
    for j in range(len(ks) - 1):
        d = {}
        if ks[j] < ks[j + 1]:
            for e in range(int(ks[j]), int(ks[j + 1])):
                d[e] = [Fraction(1)]
        cur.append(d)
    for k in range(1, p + 1):
        nxt = []
        for j in range(len(ks) - k - 1):
            d = {}
            den1 = ks[j + k] - ks[j]
            den2 = ks[j + k + 1] - ks[j + 1]
            if den1 != 0:
                for e, poly in cur[j].items():
                    d[e] = _padd(d.get(e, [Fraction(0)]), _pmul([-ks[j] / den1, Fraction(1) / den1], poly))
            if den2 != 0:
                for e, poly in cur[j + 1].items():
                    d[e] = _padd(d.get(e, [Fraction(0)]), _pmul([ks[j + k + 1] / den2, Fraction(-1) / den2], poly))
            nxt.append({e: v for e, v in d.items() if any((x != 0 for x in v))})
        cur = nxt
    return cur

def _oracle_spline_basis_values(p, r, nmesh, tvals):
    p, r = _check_pr(p, r)
    nmesh = int(nmesh)
    if nmesh < 1:
        raise ValueError('nmesh must be a positive integer')
    tv = np.atleast_1d(np.asarray(tvals, dtype=float))
    if tv.ndim != 1 or np.any(tv < 0.0) or np.any(tv > nmesh) or (not np.all(np.isfinite(tv))):
        raise ValueError('evaluation points must lie in [0, nmesh]')
    phi = _bsplines(p, r, nmesh)
    out = np.zeros((len(phi), len(tv)))
    for i, f in enumerate(phi):
        for jj, x in enumerate(tv):
            e = min(int(np.floor(x)), nmesh - 1)
            if e in f:
                out[i, jj] = float(_peval(f[e], Fraction(float(x))))
    return out

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {'setup': 'import numpy as np\np, r, nmesh = 2, 0, 4\ntvals = np.array([0.0, 0.25, 1.0, 1.5, 2.75, 4.0])\n',
         'call': 'spline_basis_values(p, r, nmesh, tvals)',
         'gold_call': '_oracle_spline_basis_values(p, r, nmesh, tvals)'},
        {'setup': 'import numpy as np\np, r, nmesh = 3, 1, 4\ntvals = np.linspace(0.0, 4.0, 9)\n',
         'call': 'spline_basis_values(p, r, nmesh, tvals)',
         'gold_call': '_oracle_spline_basis_values(p, r, nmesh, tvals)'},
        {'setup': 'import numpy as np\np, r, nmesh = 4, 2, 5\ntvals = np.array([0.5, 1.0, 2.2, 3.9, 5.0])\n',
         'call': 'spline_basis_values(p, r, nmesh, tvals)',
         'gold_call': '_oracle_spline_basis_values(p, r, nmesh, tvals)'},
        {'setup': 'import numpy as np\np, r, nmesh = 5, 3, 4\ntvals = np.array([0.1, 1.3, 2.0, 3.7])\n',
         'call': 'spline_basis_values(p, r, nmesh, tvals)',
         'gold_call': '_oracle_spline_basis_values(p, r, nmesh, tvals)'},
    ]
