"""
Return the coefficients, highest power first, of the scalar polynomial det S_rho(t), where S_rho is the matrix polynomial symbol of the block Toeplitz matrices K = -B + rho M built from the interior blocks of the previous step. With the block at offset d written A_{-d}, the Laurent symbol is A_rho(t) = sum over d of (-B_d + rho M_d) t^{-d}; S_rho(t) = t^k A_rho(t) with k the largest positive offset present, so that S_rho is a genuine matrix polynomial, and its determinant is taken exactly. Reject invalid p, r or a negative rho.

The infinite block Toeplitz operator generated by the symbol is Fredholm exactly when the determinant of the symbol has no zeros on the unit circle, and the growth of the condition numbers of the finite sections is decided by where the zeros of this determinant lie relative to the unit circle, zeros at the origin included. The determinant is a polynomial with rational coefficients when rho is rational, and its coefficient list, not a floating approximation of its roots, is the object every later step rests on.

Returns
-------
A (deg + 1,) float64 array of polynomial coefficients, highest power first.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def symbol_determinant(p, r, rho):
    """Return the coefficients, highest power first, of the scalar polynomial det S_rho(t),
    where S_rho is the matrix polynomial symbol of the block Toeplitz matrices K = -B + rho
    M built from the interior blocks of the previous step.

    Args:
        p (int): polynomial degree of the spline space, at least 1.
        r (int): regularity of the spline space, an integer with 0 <= r <= p - 1.
        rho (float or Fraction): non-negative mesh-scaled parameter rho = mu h^2 of the
            wave scheme.

    Returns:
        numpy.ndarray of shape (deg + 1,) with the coefficients of det S_rho(t), highest
        power first.

    Raises:
        ValueError: if p < 1 or r is outside 0 <= r <= p - 1.
        ValueError: if rho is negative.
    """
    return None

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
from fractions import Fraction

def _check_pr(p, r):
    p = int(p)
    r = int(r)
    if p < 1 or r < 0 or r > p - 1:
        raise ValueError('degree p must be >= 1 and regularity r must satisfy 0 <= r <= p - 1')
    return (p, r)

def _check_rho(rho):
    if isinstance(rho, Fraction):
        rq = rho
    else:
        rq = Fraction(rho).limit_denominator(10 ** 12) if isinstance(rho, float) else Fraction(rho)
    if rq < 0:
        raise ValueError('rho must be non-negative')
    return rq

def _padd(a, b):
    n = max(len(a), len(b))
    return [(a[i] if i < len(a) else Fraction(0)) + (b[i] if i < len(b) else Fraction(0)) for i in range(n)]

def _pmul(a, b):
    out = [Fraction(0)] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        if x == 0:
            continue
        for j, y in enumerate(b):
            out[i + j] += x * y
    return out

def _pderiv(a):
    return [a[i] * i for i in range(1, len(a))] or [Fraction(0)]

def _pint(a, lo, hi):
    s = Fraction(0)
    for i, c in enumerate(a):
        s += c * (Fraction(hi) ** (i + 1) - Fraction(lo) ** (i + 1)) / (i + 1)
    return s

def _ptrim(a):
    a = list(a)
    while len(a) > 1 and a[-1] == 0:
        a.pop()
    return a

def _knots(p, r, nmesh):
    return [Fraction(0)] * (p + 1) + sum(([Fraction(e)] * (p - r) for e in range(1, nmesh)), []) + [Fraction(nmesh)] * (p + 1)

def _bsplines(p, r, nmesh):
    ks = _knots(p, r, nmesh)
    cur = []
    for j in range(len(ks) - 1):
        d = {}
        if ks[j] < ks[j + 1]:
            for e in range(int(ks[j]), int(ks[j + 1])):
                d[e] = [Fraction(1)]
        cur.append(d)
    for k in range(1, p + 1):
        nxt = []
        for j in range(len(ks) - k - 1):
            d = {}
            den1 = ks[j + k] - ks[j]
            den2 = ks[j + k + 1] - ks[j + 1]
            if den1 != 0:
                for e, poly in cur[j].items():
                    d[e] = _padd(d.get(e, [Fraction(0)]), _pmul([-ks[j] / den1, Fraction(1) / den1], poly))
            if den2 != 0:
                for e, poly in cur[j + 1].items():
                    d[e] = _padd(d.get(e, [Fraction(0)]), _pmul([ks[j + k + 1] / den2, Fraction(-1) / den2], poly))
            nxt.append({e: v for e, v in d.items() if any((x != 0 for x in v))})
        cur = nxt
    return cur

def _galerkin_exact(p, r, nmesh):
    phi = _bsplines(p, r, nmesh)
    n = nmesh * (p - r) + r

    def _inner(f, g, d1, d2):
        s = Fraction(0)
        for e in set(f) & set(g):
            a = f[e]
            b = g[e]
            for _ in range(d1):
                a = _pderiv(a)
            for _ in range(d2):
                b = _pderiv(b)
            s += _pint(_pmul(a, b), e, e + 1)
        return s
    M = [[_inner(phi[j], phi[l - 1], 0, 0) for j in range(1, n + 1)] for l in range(1, n + 1)]
    B = [[_inner(phi[j], phi[l - 1], 1, 1) for j in range(1, n + 1)] for l in range(1, n + 1)]
    return (M, B, n)

def _interior_blocks_exact(p, r):
    N = p - r
    nmesh = 2 * p + 4
    M, B, n = _galerkin_exact(p, r, nmesh)
    mid = nmesh // 2
    out = {}
    for d in range(-p, p + 1):
        bj = mid + d
        if 0 <= bj < n // N:
            Mb = [[M[N * mid + a][N * bj + b] for b in range(N)] for a in range(N)]
            Bb = [[B[N * mid + a][N * bj + b] for b in range(N)] for a in range(N)]
            if any((x != 0 for row in Mb for x in row)) or any((x != 0 for row in Bb for x in row)):
                out[d] = (Mb, Bb)
    return out

def _symbol_polys(p, r, rho):
    blocks = _interior_blocks_exact(p, r)
    N = p - r
    k = max([d for d in blocks if d > 0] + [0])
    deg = k + max((-d for d in blocks))
    S = [[[Fraction(0)] * (deg + 1) for _ in range(N)] for _ in range(N)]
    for d, (Mb, Bb) in blocks.items():
        power = k - d
        for a in range(N):
            for b in range(N):
                S[a][b][power] += -Bb[a][b] + rho * Mb[a][b]
    return (S, k)

def _pdet(S):
    n = len(S)
    if n == 1:
        return S[0][0]
    tot = [Fraction(0)]
    for j in range(n):
        minor = [[S[i][c] for c in range(n) if c != j] for i in range(1, n)]
        term = _pmul(S[0][j], _pdet(minor))
        if j % 2:
            term = [-x for x in term]
        tot = _padd(tot, term)
    return tot

def _det_symbol_exact(p, r, rho):
    S, k = _symbol_polys(p, r, rho)
    return _ptrim(_pdet(S))

def _oracle_symbol_determinant(p, r, rho):
    if float(rho) < 0.0:
        raise ValueError('rho must be non-negative')
    p, r = _check_pr(p, r)
    rq = _check_rho(rho)
    c = _det_symbol_exact(p, r, rq)
    return np.array([float(x) for x in c[::-1]])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {'setup': 'import numpy as np\np, r, rho = 2, 0, 5.0\n',
         'call': 'symbol_determinant(p, r, rho)',
         'gold_call': '_oracle_symbol_determinant(p, r, rho)'},
        {'setup': 'import numpy as np\np, r, rho = 3, 0, 20.0\n',
         'call': 'symbol_determinant(p, r, rho)',
         'gold_call': '_oracle_symbol_determinant(p, r, rho)'},
        {'setup': 'import numpy as np\np, r, rho = 3, 1, 9.9\n',
         'call': 'symbol_determinant(p, r, rho)',
         'gold_call': '_oracle_symbol_determinant(p, r, rho)'},
        {'setup': 'import numpy as np\np, r, rho = 4, 2, 60.0\n',
         'call': 'symbol_determinant(p, r, rho)',
         'gold_call': '_oracle_symbol_determinant(p, r, rho)'},
    ]
