"""
Return the leading nblocks x nblocks block section of the infinite block Toeplitz matrix generated by the symbol of the wave scheme, that is the matrix whose block at block position (i, j) is -B_d + rho M_d with d = j - i taken from the interior blocks of step 3, and zero where that offset is absent; this is the pure block Toeplitz matrix whose finite sections the source analyses, without the boundary perturbations of the actual Petrov-Galerkin matrix. Reject invalid p, r, a negative rho or nblocks < 1.

The source studies the actual system matrices through their pure block Toeplitz extensions, because the corner perturbations and the extra rows of the r > 0 cases do not change the conditioning behaviour; the finite section is the natural object for Toeplitz theory, and its entries are rational numbers whenever rho is.

Returns
-------
A (N nblocks, N nblocks) float64 array.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def block_toeplitz_section(p, r, rho, nblocks):
    """Return the leading nblocks x nblocks block section of the infinite block Toeplitz matrix
    generated by the symbol of the wave scheme, that is the matrix whose block at block
    position (i, j) is -B_d + rho M_d with d = j - i taken from the interior blocks of step
    3, and zero where that offset is absent; this is the pure block Toeplitz matrix whose
    finite sections the source analyses, without the boundary perturbations of the actual
    Petrov-Galerkin matrix.

    Args:
        p (int): polynomial degree of the spline space, at least 1.
        r (int): regularity of the spline space, an integer with 0 <= r <= p - 1.
        rho (float or Fraction): non-negative parameter of the wave scheme.
        nblocks (int): number of block rows and block columns, at least 1.

    Returns:
        numpy.ndarray of shape (N nblocks, N nblocks), N = p - r, the finite section of
        the block Toeplitz operator.

    Raises:
        ValueError: if p < 1 or r is outside 0 <= r <= p - 1.
        ValueError: if rho is negative or nblocks < 1.
    """
    return None

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np
from fractions import Fraction

def _check_pr(p, r):
    p = int(p)
    r = int(r)
    if p < 1 or r < 0 or r > p - 1:
        raise ValueError('degree p must be >= 1 and regularity r must satisfy 0 <= r <= p - 1')
    return (p, r)

def _check_rho(rho):
    if isinstance(rho, Fraction):
        rq = rho
    else:
        rq = Fraction(rho).limit_denominator(10 ** 12) if isinstance(rho, float) else Fraction(rho)
    if rq < 0:
        raise ValueError('rho must be non-negative')
    return rq

def _check_nb(nblocks):
    nb = int(nblocks)
    if nb < 1:
        raise ValueError('nblocks must be a positive integer')
    return nb

def _padd(a, b):
    n = max(len(a), len(b))
    return [(a[i] if i < len(a) else Fraction(0)) + (b[i] if i < len(b) else Fraction(0)) for i in range(n)]

def _pmul(a, b):
    out = [Fraction(0)] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        if x == 0:
            continue
        for j, y in enumerate(b):
            out[i + j] += x * y
    return out

def _pderiv(a):
    return [a[i] * i for i in range(1, len(a))] or [Fraction(0)]

def _pint(a, lo, hi):
    s = Fraction(0)
    for i, c in enumerate(a):
        s += c * (Fraction(hi) ** (i + 1) - Fraction(lo) ** (i + 1)) / (i + 1)
    return s

def _knots(p, r, nmesh):
    return [Fraction(0)] * (p + 1) + sum(([Fraction(e)] * (p - r) for e in range(1, nmesh)), []) + [Fraction(nmesh)] * (p + 1)

def _bsplines(p, r, nmesh):
    ks = _knots(p, r, nmesh)
    cur = []
    for j in range(len(ks) - 1):
        d = {}
        if ks[j] < ks[j + 1]:
            for e in range(int(ks[j]), int(ks[j + 1])):
                d[e] = [Fraction(1)]
        cur.append(d)
    for k in range(1, p + 1):
        nxt = []
        for j in range(len(ks) - k - 1):
            d = {}
            den1 = ks[j + k] - ks[j]
            den2 = ks[j + k + 1] - ks[j + 1]
            if den1 != 0:
                for e, poly in cur[j].items():
                    d[e] = _padd(d.get(e, [Fraction(0)]), _pmul([-ks[j] / den1, Fraction(1) / den1], poly))
            if den2 != 0:
                for e, poly in cur[j + 1].items():
                    d[e] = _padd(d.get(e, [Fraction(0)]), _pmul([ks[j + k + 1] / den2, Fraction(-1) / den2], poly))
            nxt.append({e: v for e, v in d.items() if any((x != 0 for x in v))})
        cur = nxt
    return cur

def _galerkin_exact(p, r, nmesh):
    phi = _bsplines(p, r, nmesh)
    n = nmesh * (p - r) + r

    def _inner(f, g, d1, d2):
        s = Fraction(0)
        for e in set(f) & set(g):
            a = f[e]
            b = g[e]
            for _ in range(d1):
                a = _pderiv(a)
            for _ in range(d2):
                b = _pderiv(b)
            s += _pint(_pmul(a, b), e, e + 1)
        return s
    M = [[_inner(phi[j], phi[l - 1], 0, 0) for j in range(1, n + 1)] for l in range(1, n + 1)]
    B = [[_inner(phi[j], phi[l - 1], 1, 1) for j in range(1, n + 1)] for l in range(1, n + 1)]
    return (M, B, n)

def _interior_blocks_exact(p, r):
    N = p - r
    nmesh = 2 * p + 4
    M, B, n = _galerkin_exact(p, r, nmesh)
    mid = nmesh // 2
    out = {}
    for d in range(-p, p + 1):
        bj = mid + d
        if 0 <= bj < n // N:
            Mb = [[M[N * mid + a][N * bj + b] for b in range(N)] for a in range(N)]
            Bb = [[B[N * mid + a][N * bj + b] for b in range(N)] for a in range(N)]
            if any((x != 0 for row in Mb for x in row)) or any((x != 0 for row in Bb for x in row)):
                out[d] = (Mb, Bb)
    return out

def _section_exact(p, r, rho, nb):
    blocks = _interior_blocks_exact(p, r)
    N = p - r
    T = [[Fraction(0)] * (N * nb) for _ in range(N * nb)]
    for bi in range(nb):
        for d, (Mb, Bb) in blocks.items():
            bj = bi + d
            if 0 <= bj < nb:
                for a in range(N):
                    for b in range(N):
                        T[N * bi + a][N * bj + b] = -Bb[a][b] + rho * Mb[a][b]
    return T

def _oracle_block_toeplitz_section(p, r, rho, nblocks):
    if float(rho) < 0.0 or int(nblocks) < 1:
        raise ValueError('rho must be non-negative and nblocks positive')
    p, r = _check_pr(p, r)
    rq = _check_rho(rho)
    nb = _check_nb(nblocks)
    T = _section_exact(p, r, rq, nb)
    return np.array([[float(x) for x in row] for row in T])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {'setup': 'import numpy as np\np, r, rho, nblocks = 4, 2, 60.0, 4\n',
         'call': 'block_toeplitz_section(p, r, rho, nblocks)',
         'gold_call': '_oracle_block_toeplitz_section(p, r, rho, nblocks)'},
        {'setup': 'import numpy as np\np, r, rho, nblocks = 2, 0, 11.0, 5\n',
         'call': 'block_toeplitz_section(p, r, rho, nblocks)',
         'gold_call': '_oracle_block_toeplitz_section(p, r, rho, nblocks)'},
        {'setup': 'import numpy as np\np, r, rho, nblocks = 3, 1, 9.9, 3\n',
         'call': 'block_toeplitz_section(p, r, rho, nblocks)',
         'gold_call': '_oracle_block_toeplitz_section(p, r, rho, nblocks)'},
        {'setup': 'import numpy as np\np, r, rho, nblocks = 3, 0, 50.0, 3\n',
         'call': 'block_toeplitz_section(p, r, rho, nblocks)',
         'gold_call': '_oracle_block_toeplitz_section(p, r, rho, nblocks)'},
    ]
