"""
Carry out the analysis an experimentalist performs. Form the ordinate that the constant-cross-section model predicts to be a straight line against the reciprocal temperature in units of inverse kilokelvin, sample it at equally spaced reciprocal temperatures across the given window by linear interpolation of that ordinate on the supplied grid, and fit a straight line by least squares. Return the apparent thermodynamic level that the slope implies, the apparent capture cross section that the intercept implies once the temperature-independent prefactor built from the thermal velocity and the band density of states is divided out, and the root-mean-square residual of the fit. Interpolate the ordinate itself rather than the rate, so that a genuinely constant cross section is recovered exactly.

The constant-cross-section model is still the most widely used reading of a transient spectroscopy measurement: it assigns the slope of the line to the level and the intercept to the cross section. Applying it to rates that were generated by a cross section which is in fact strongly temperature dependent is precisely the error the source sets out to quantify, and the size of the error depends on which part of the temperature range was measured.

Returns
-------
A (3,) float64 array holding [apparent thermodynamic level in eV, apparent capture cross section in square Angstrom, root-mean-square fit residual].
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

import numpy as np


def arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy):
    """Carry out the analysis an experimentalist performs. A (3,) float64 array holding
    [apparent thermodynamic level in eV, apparent capture cross section in square Angstrom,
    root-mean-square fit residual]."""
    return np.zeros(3)

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


K_B     = 8.617333262e-5

H_PLANCK = 4.135667696e-15

M_E     = 5.6095886e-32

def _oracle_arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy):
    rate = np.asarray(rate, dtype=float).ravel()
    t_grid = np.asarray(t_grid, dtype=float).ravel()
    n_fit = int(n_fit); mstar = float(mstar); degeneracy = float(degeneracy)
    lo, hi = float(window[0]), float(window[1])
    if n_fit < 3 or not hi > lo:
        raise ValueError("n_fit must be at least three and the window must be ordered")
    if rate.size != t_grid.size:
        raise ValueError("rate and t_grid must have the same length")
    if mstar <= 0.0 or degeneracy <= 0.0:
        raise ValueError("mstar and degeneracy must be positive")
    inv = np.linspace(lo, hi, n_fit)
    grid_inv = 1000.0/t_grid
    y_grid = 2.0*np.log(t_grid) - np.log(rate)
    order = np.argsort(grid_inv)
    y = np.interp(inv, grid_inv[order], y_grid[order])
    a = np.polyfit(inv, y, 1)
    m_eff = mstar*M_E
    gamma = (np.sqrt(3.0*K_B/m_eff)
             * 2.0*(2.0*np.pi*m_eff*K_B/(H_PLANCK*H_PLANCK))**1.5/degeneracy)
    return np.array([a[0]*K_B*1000.0, np.exp(-a[1])/gamma,
                     float(np.std(y - np.polyval(a, inv)))])

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {'setup': 'import numpy as np\nt_grid = np.linspace(60.0, 620.0, 1121)\nrate = _oracle_emission_rate(np.full(t_grid.size, 10.0), t_grid, 0.62, 0.29, 2.0)\nwindow = (2.0, 3.5)\nn_fit = 29\nmstar = 0.29\ndegeneracy = 2.0\n',
         'call': 'arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy)',
         'gold_call': '_oracle_arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy)'},
        {'setup': 'import numpy as np\ndef _fx_coordinate_matrix_elements(delta_q, hw, n_phonon, u_lo, u_hi, n_quad):\n    _hbar2 = 4.18005956e-3\n    ell = np.sqrt(_hbar2 / hw)\n    def _fx_basis(lo, hi):\n        u = np.linspace(lo, hi, n_quad)\n        out = np.empty((n_phonon + 2, n_quad))\n        out[0] = u\n        out[1] = np.pi ** -0.25 * np.exp(-0.5 * u * u)\n        if n_phonon >= 1:\n            out[2] = np.sqrt(2.0) * u * out[1]\n        for k in range(2, n_phonon + 1):\n            out[k + 1] = np.sqrt(2.0 / k) * u * out[k] - np.sqrt((k - 1.0) / k) * out[k - 1]\n        return out\n    tab = _fx_basis(u_lo, u_hi)\n    u_grid, phi = tab[0], tab[1:]\n    du = u_grid[1] - u_grid[0]\n    shift = delta_q / ell\n    phi_f = _fx_basis(u_lo - shift, u_hi - shift)[1:]\n    return ((phi * u_grid * du) @ phi_f.T) * ell\nq = _fx_coordinate_matrix_elements(4.90, 0.038, 220, -35.0, 60.0, 47501)\nt_grid = np.linspace(60.0, 620.0, 1121)\nsig = _oracle_nmp_cross_section(q, 0.038, 1.02, t_grid, 0.012, 5.0, 300.0, 10.0)\nrate = _oracle_emission_rate(sig, t_grid, 0.62, 0.29, 2.0)\nwindow = (6.0, 10.0)\nn_fit = 29\nmstar = 0.29\ndegeneracy = 2.0\n',
         'call': 'arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy)',
         'gold_call': '_oracle_arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy)'},
        {'setup': 'import numpy as np\ndef _fx_coordinate_matrix_elements(delta_q, hw, n_phonon, u_lo, u_hi, n_quad):\n    _hbar2 = 4.18005956e-3\n    ell = np.sqrt(_hbar2 / hw)\n    def _fx_basis(lo, hi):\n        u = np.linspace(lo, hi, n_quad)\n        out = np.empty((n_phonon + 2, n_quad))\n        out[0] = u\n        out[1] = np.pi ** -0.25 * np.exp(-0.5 * u * u)\n        if n_phonon >= 1:\n            out[2] = np.sqrt(2.0) * u * out[1]\n        for k in range(2, n_phonon + 1):\n            out[k + 1] = np.sqrt(2.0 / k) * u * out[k] - np.sqrt((k - 1.0) / k) * out[k - 1]\n        return out\n    tab = _fx_basis(u_lo, u_hi)\n    u_grid, phi = tab[0], tab[1:]\n    du = u_grid[1] - u_grid[0]\n    shift = delta_q / ell\n    phi_f = _fx_basis(u_lo - shift, u_hi - shift)[1:]\n    return ((phi * u_grid * du) @ phi_f.T) * ell\nq = _fx_coordinate_matrix_elements(1.20, 0.038, 220, -35.0, 60.0, 47501)\nt_grid = np.linspace(60.0, 620.0, 1121)\nsig = _oracle_nmp_cross_section(q, 0.038, 1.02, t_grid, 0.012, 5.0, 300.0, 10.0)\nrate = _oracle_emission_rate(sig, t_grid, 0.62, 0.29, 2.0)\nwindow = (2.0, 3.5)\nn_fit = 41\nmstar = 0.29\ndegeneracy = 2.0\n',
         'call': 'arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy)',
         'gold_call': '_oracle_arrhenius_signature(rate, t_grid, window, n_fit, mstar, degeneracy)'},
    ]
