"""
Compute the magnitude of the out-of-sample phenotype prediction error for each training individual using the observed phenotype and the prediction produced by the model trained with that individual's fold held out.

The prediction-interval framework estimates uncertainty from genuinely out-of-sample prediction errors generated by cross-validation. For each training individual, the relevant nonconformity score is the absolute difference between the observed phenotype and the prediction obtained from the model that excluded that individual's fold. Absolute residuals quantify prediction-error magnitude without assuming a parametric error distribution.

Returns
-------
A one-dimensional float array of length N containing |observed[i] - heldout_predictions[i]| for each training individual.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def compute_cv_residuals(
    observed: np.ndarray,
    heldout_predictions: np.ndarray
) -> np.ndarray:
    """
    Compute absolute held-out residuals for the training individuals.

    Parameters
    ----------
    observed : np.ndarray
        One-dimensional array of observed training phenotypes.
    heldout_predictions : np.ndarray
        One-dimensional array of out-of-sample predictions from the model
        that held out each individual's fold. Must have the same length as
        observed.

    Returns
    -------
    residuals : np.ndarray
        One-dimensional float array containing the absolute prediction
        residual for each training individual.
    """
    return

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_compute_cv_residuals(
    observed: np.ndarray,
    heldout_predictions: np.ndarray
) -> np.ndarray:
    import numpy as np

    observed = np.asarray(observed, dtype=float)
    heldout_predictions = np.asarray(heldout_predictions, dtype=float)

    if observed.ndim != 1 or heldout_predictions.ndim != 1:
        raise ValueError("Inputs must be one-dimensional.")
    if observed.size != heldout_predictions.size:
        raise ValueError("Inputs must have the same length.")
    if observed.size == 0:
        raise ValueError("Inputs must be non-empty.")

    return np.abs(observed - heldout_predictions)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {
            "setup": """
import numpy as np

observed = np.array([1.0, -1.0, 0.5])
predicted = np.array([0.0, -2.0, 0.5])
""",
            "call": "compute_cv_residuals(observed, predicted)",
            "gold_call": "_oracle_compute_cv_residuals(observed, predicted)",
        },
        {
            "setup": """
import numpy as np

observed = np.array([0.0, 0.0, 0.0, 0.0])
predicted = np.array([0.2, -0.4, 1.0, -1.5])
""",
            "call": "compute_cv_residuals(observed, predicted)",
            "gold_call": "_oracle_compute_cv_residuals(observed, predicted)",
        },
        {
            "setup": """
import numpy as np

observed = np.array([-3.5, 2.2, 7.1])
predicted = np.array([-1.0, 4.7, 6.0])
""",
            "call": "compute_cv_residuals(observed, predicted)",
            "gold_call": "_oracle_compute_cv_residuals(observed, predicted)",
        },
    ]
