"""
Compute the macroscopic interaction factor for each double-mutant pair by comparing its kinetic observable obtained from the additive microscopic model with the conventional multiplicative null prediction constructed from the two single-mutant fold changes.

The conventional macroscopic null assumes that the effects of two mutations combine multiplicatively in a kinetic parameter. If f_i and f_j are the wild-type-normalized effects of two single mutants, the null prediction for the double mutant is the wild-type value multiplied by f_i f_j. The interaction factor is the ratio between the kinetic parameter generated by the additive microscopic double-mutant state and this macroscopic null prediction. An interaction factor of one corresponds to macroscopic additivity on the fold-change scale, whereas deviations from one represent apparent non-specific epistasis produced by the kinetic mapping.

Returns
-------
np.ndarray, a one-dimensional floating-point array containing one positive macroscopic interaction factor for each requested double-mutant pair.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def compute_pair_interactions(
    single_folds: "np.ndarray",
    anchor_observable: float,
    double_observables: "np.ndarray",
    pair_indices: "np.ndarray",
    anchor_index: int,
    observable_index: int,
) -> "np.ndarray":
    """
    Compute the source-defined interaction quantity for each supplied
    mutation pair.

    Parameters
    ----------
    single_folds : np.ndarray
        Wild-type-normalized single-mutant observables.

    anchor_observable : float
        Reference-state value of the observable being evaluated.

    double_observables : np.ndarray
        Observable values for the requested double mutants.

    pair_indices : np.ndarray
        Integer mutation-pair indices.

    anchor_index : int
        Row index of the reference mutation in ``single_folds``.

    observable_index : int
        Column identifying the kinetic observable to evaluate.

    Returns
    -------
    np.ndarray
        One positive interaction factor for every supplied mutation pair.

    Raises
    ------
    ValueError
        If the fold-change matrix, reference value, double-mutant
        observables, pair indices, reference index, or observable index
        is invalid.
    """
    return interactions

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_compute_pair_interactions(
    single_folds: "np.ndarray",
    anchor_observable: float,
    double_observables: "np.ndarray",
    pair_indices: "np.ndarray",
    anchor_index: int,
    observable_index: int,
) -> "np.ndarray":
    f = np.asarray(single_folds, dtype=float)
    dob = np.asarray(double_observables, dtype=float)
    p = np.asarray(pair_indices)
    if f.ndim != 2 or f.shape[1] != 4 or f.shape[0] < 2 or not np.all(np.isfinite(f)) or np.any(f <= 0):
        raise ValueError("invalid folds")
    if dob.ndim != 2 or dob.shape[1] != 4 or dob.shape[0] != p.shape[0] or not np.all(np.isfinite(dob)) or np.any(dob <= 0):
        raise ValueError("invalid doubles")
    if p.ndim != 2 or p.shape[1] != 2 or not np.issubdtype(p.dtype, np.integer) or np.any(p < 0) or np.any(p >= f.shape[0]):
        raise ValueError("invalid pairs")
    if isinstance(anchor_index, (bool, np.bool_)) or not isinstance(anchor_index, (int, np.integer)) or anchor_index < 0 or anchor_index >= f.shape[0]:
        raise ValueError("invalid anchor")
    if isinstance(observable_index, (bool, np.bool_)) or not isinstance(observable_index, (int, np.integer)) or observable_index < 0 or observable_index >= 4:
        raise ValueError("invalid observable index")
    a = int(observable_index)
    wt_fold = f[int(anchor_index), a]
    if not np.isfinite(anchor_observable) or anchor_observable <= 0:
        raise ValueError("anchor_observable must be finite and positive")
    null = anchor_observable * (f[p[:, 0], a] * f[p[:, 1], a]) / wt_fold
    out = dob[:, a] / null
    if not np.all(np.isfinite(out)) or np.any(out <= 0):
        raise ValueError("invalid interactions")
    return out.astype(float, copy=False)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    return [
        {"setup": "import numpy as np\nf=np.array([[1.,1.,1.,1.],[2.,3.,4.,5.],[.5,2.,8.,2.]],float)\nd=np.array([[1.,2.,10.,3.],[2.,1.,4.,2.]],float)\np=np.array([[1,2],[0,1]],int)\n", "call": "compute_pair_interactions(f,1.0,d,p,0,2)", "gold_call": "_oracle_compute_pair_interactions(f,1.0,d,p,0,2)"},
        {"setup": "import numpy as np\nf=np.ones((2,4)); d=np.ones((1,4)); p=np.array([[0,1]],int)\n", "call": "compute_pair_interactions(f,1.0,d,p,0,2)", "gold_call": "_oracle_compute_pair_interactions(f,1.0,d,p,0,2)"},
        {"setup": "import numpy as np\nf=np.array([[1e-10]*4,[1e10]*4],float); d=np.array([[1.,1.,1.,1.]],float); p=np.array([[0,1]],int)\n", "call": "compute_pair_interactions(f,1.0,d,p,0,2)", "gold_call": "_oracle_compute_pair_interactions(f,1.0,d,p,0,2)"},
        {"setup": "import numpy as np\nf=np.ones((2,4)); d=np.ones((1,4)); p=np.array([[0,1]],int)\ndef run_model():\n    try: compute_pair_interactions(f,1.0,d,p,0,4); return 0\n    except ValueError: return 1\n    except Exception: return 2\ndef run_gold():\n    try: _oracle_compute_pair_interactions(f,1.0,d,p,0,4); return 0\n    except ValueError: return 1\n    except Exception: return 2\n", "call": "run_model()", "gold_call": "run_gold()"},
    ]
