"""
Compute the rate of change of the Runge-Lenz vector generated by the secular part of the leading-order error Hamiltonian of a BAB Wisdom-Holman map, at a given state.

A second-order Wisdom-Holman map in democratic heliocentric coordinates splits the two-body Hamiltonian into two parts. The first is A = T1 + V_sun, with T1 = |P|^2/(2 m1) and V_sun = -G m0 m1/|Q|. The second is B = T0 = |P|^2/(2 m0), the star's kinetic energy; for two bodies in the barycentric frame only the companion's P enters it. The BAB composition takes a half step of B, a full step of A and another half step of B, with step size h. It exactly follows a modified Hamiltonian that differs from the true one at order h^2.

For the apsidal motion, the only part of that O(h^2) difference that acts secularly is H_B = (h^2/24) {{V_sun, T0}, T0}. The Poisson bracket of two phase-space functions is {K, F} = sum over components of (dK/dQ . dF/dP - dK/dP . dF/dQ), and under H_B any phase-space function F changes at the rate {F, H_B}.

The quantity to return is dR/dt = {R, H_B} for the Runge-Lenz vector R of Step 4, evaluated at the given (Q, P). Both H_B and its action on R must be worked out; neither is given here in explicit form.

Returns
-------
np.ndarray of shape (3,), float: dR/dt = {R, H_B} at the given state.
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def error_hamiltonian_rl_rate(Q: np.ndarray, P: np.ndarray, m0: float, m1: float,
                              h: float) -> np.ndarray:
    """Rate of change of the Runge-Lenz vector under the secular error Hamiltonian H_B.

    Parameters
    ----------
    Q : np.ndarray
        Shape (3,), companion position relative to the star (au); finite, nonzero.
    P : np.ndarray
        Shape (3,), barycentric momentum of the companion (Msun au / yr); finite.
    m0 : float
        Mass of the star (Msun), a finite number > 0.
    m1 : float
        Mass of the companion (Msun), a finite number > 0.
    h : float
        Map step size (yr), a finite number > 0.

    Returns
    -------
    Rdot : np.ndarray
        Shape (3,), dR/dt = {R, H_B} (units of R per year).

    Raises
    ------
    ValueError
        If Q or P does not have shape (3,) or contains a non-finite value; if
        Q is the zero vector; or if m0, m1 or h is not a finite number > 0.
    """
    return Rdot  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

def _oracle_error_hamiltonian_rl_rate(Q: np.ndarray, P: np.ndarray, m0: float, m1: float,
                                      h: float) -> np.ndarray:
    import numpy as np

    Q = np.asarray(Q, dtype=float)
    P = np.asarray(P, dtype=float)
    if Q.shape != (3,) or P.shape != (3,):
        raise ValueError("Q and P must both have shape (3,)")
    if not (np.all(np.isfinite(Q)) and np.all(np.isfinite(P))):
        raise ValueError("Q and P must be finite")
    for name, val in (("m0", m0), ("m1", m1), ("h", h)):
        if not (isinstance(val, (int, float, np.floating)) and np.isfinite(val) and float(val) > 0.0):
            raise ValueError(f"{name} must be a finite number > 0")
    q = np.sqrt(Q @ Q)
    if q == 0.0:
        raise ValueError("Q must be nonzero")
    G = 4.0 * np.pi ** 2
    m0, m1, h = float(m0), float(m1), float(h)
    eps = m1 / m0
    c0 = G * m0 ** 2 * m1 ** 2 / (m0 + m1)
    L = np.cross(Q, P)
    PQ = P @ Q
    P2 = P @ P
    pref = G * h ** 2 * eps / 24.0
    # {R, H_B} with H_B = (h^2/24) {{V_sun, T0}, T0} = pref * (P^2/Q^3 - 3 (P.Q)^2 / Q^5)
    return pref * (np.cross(Q, L) * (3.0 * P2 / q ** 5 - 15.0 * PQ ** 2 / q ** 7)
                   + np.cross(P, L) * (6.0 * PQ / q ** 5)
                   + 2.0 * c0 * PQ * Q / q ** 6
                   - 2.0 * c0 * P / q ** 4)

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    return [
        # --- Valid: the benchmark orbit at pericentre with the benchmark step (14 minutes) ---
        {
            "setup": """import numpy as np
def digest(x):
    # log-magnitude plus unit direction, so the result is compared at relative precision
    x = np.asarray(x, dtype=float).ravel()
    n = float(np.sqrt(x @ x))
    if not np.isfinite(n) or n == 0.0:
        return (0.0,) * (x.size + 1)
    return tuple([float(np.log(n))] + [float(c) for c in x / n])
m0, m1, a, e = 1.0, 0.07, 0.06, 0.5
M = m0 + m1
mu = m0*m1/M
h = 14/(60*24*365.25)
Q = np.array([a*(1-e), 0.0, 0.0])
P = mu*np.array([0.0, np.sqrt(4*np.pi**2*M*(1+e)/(a*(1-e))), 0.0])
""",
            "call": "digest(error_hamiltonian_rl_rate(Q.copy(), P.copy(), m0, m1, h))",
            "gold_call": "digest(_oracle_error_hamiltonian_rl_rate(Q.copy(), P.copy(), m0, m1, h))",
        },
        # --- Valid: a generic state away from the apsides (P.Q nonzero), where every term of the bracket contributes ---
        {
            "setup": """import numpy as np
def digest(x):
    # log-magnitude plus unit direction, so the result is compared at relative precision
    x = np.asarray(x, dtype=float).ravel()
    n = float(np.sqrt(x @ x))
    if not np.isfinite(n) or n == 0.0:
        return (0.0,) * (x.size + 1)
    return tuple([float(np.log(n))] + [float(c) for c in x / n])
Q = np.array([0.045, 0.031, 0.0])
P = np.array([-1.35, 1.05, 0.0])
""",
            "call": "digest(error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.0, 0.07, 3e-5))",
            "gold_call": "digest(_oracle_error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.0, 0.07, 3e-5))",
        },
        # --- Edge: a fully three-dimensional state with comparable masses and a coarse step ---
        {
            "setup": """import numpy as np
def digest(x):
    # log-magnitude plus unit direction, so the result is compared at relative precision
    x = np.asarray(x, dtype=float).ravel()
    n = float(np.sqrt(x @ x))
    if not np.isfinite(n) or n == 0.0:
        return (0.0,) * (x.size + 1)
    return tuple([float(np.log(n))] + [float(c) for c in x / n])
Q = np.array([0.8, -0.5, 0.3])
P = np.array([-0.9, 1.7, 0.4])
""",
            "call": "digest(error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.3, 0.4, 0.02))",
            "gold_call": "digest(_oracle_error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.3, 0.4, 0.02))",
        },
        # --- Invalid: non-positive step size ---
        {
            "setup": """import numpy as np
Q = np.array([1.0, 0.0, 0.0])
P = np.array([0.0, 0.1, 0.0])
def run_model():
    try:
        error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.0, 0.1, 0.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.0, 0.1, 0.0)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
        # --- Invalid: P with the wrong shape ---
        {
            "setup": """import numpy as np
Q = np.array([1.0, 0.0, 0.0])
P = np.array([0.0, 0.1])
def run_model():
    try:
        error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.0, 0.1, 0.01)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold():
    try:
        _oracle_error_hamiltonian_rl_rate(Q.copy(), P.copy(), 1.0, 0.1, 0.01)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
""",
            "call": "run_model()",
            "gold_call": "run_gold()",
        },
    ]
