"""
Compute the first-order residual modes of substructure k and scale each column to unit Euclidean length.

Kp and Mp are the partitioned matrices, counts holds the four block sizes, and k selects the substructure. Phi is the retained-mode array produced for the same substructure by the retained-mode step; the retained eigenvalues are recovered from it rather than passed separately.

The residual modes are formed from the flexibility of the modes that were not retained, acting on the inertia transmitted to the interior by acceleration of the interface. That flexibility is obtained without ever computing the discarded eigenpairs.

Columns whose Euclidean norm is zero are left at zero rather than scaled. This occurs for every interface degree of freedom belonging to a dividing surface that substructure k does not touch, and scaling is not defined for them.

The function returns a float array shaped like the constraint-mode output, zero outside the interior rows of substructure k.

Raises ValueError if counts does not have four entries; if counts does not sum to the number of equations in Kp; if k is not 0, 1 or 2; if Phi is not two dimensional with one row per equation of the system; or if any recovered eigenvalue is not strictly positive.

Truncating the fixed-interface modes discards their contribution to the response, and that contribution is not zero. At zero frequency it is purely static and is already accounted for by the constraint modes, but as the frequency rises the discarded modes respond to the inertia loading generated by interface acceleration, and the omission becomes an error that grows with mode number.

The flexibility associated with the discarded modes can be isolated without computing them. The complete set of modes spans the interior, so the full static flexibility of the interior decomposes into the part carried by the retained modes and the part carried by the rest; subtracting the first from the total leaves the second. This is what makes the correction affordable, since the discarded set is by construction far larger than the retained set.

Applying that residual flexibility to the interface inertia loading produces one additional vector per interface degree of freedom, which can be appended to the basis. The appended columns are not modes of anything and their natural scaling can differ by orders of magnitude across the interface, which worsens the conditioning of the matrices formed from the enlarged basis. Rescaling each column to unit length repairs the conditioning. It is applied within each substructure, so the blocks of one assembled column are divided by different norms and the span of the augmented basis changes with it; the reduced eigenvalues therefore do shift, and the rescaling is prescribed for conditioning rather than because it leaves them untouched.

Returns
-------
np.ndarray of shape (n, nb), dtype float
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def residual_modes(Kp: 'np.ndarray', Mp: 'np.ndarray', counts: 'np.ndarray', k: int,
                   Phi: 'np.ndarray') -> 'np.ndarray':
    '''First-order residual modes of one substructure.

    Parameters
    ----------
    Kp, Mp : np.ndarray
        (n, n) partitioned stiffness and mass matrices.
    counts : np.ndarray
        (4,) integer block sizes of the partitioned ordering.
    k : int
        Substructure index, 0, 1 or 2.
    Phi : np.ndarray
        (n, nd) retained-mode array for the same substructure.

    Returns
    -------
    np.ndarray
        (n, nb) float array, zero outside the interior rows of substructure k.
    '''
    return residual_modes_array  # placeholder

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np

def _oracle_residual_modes(Kp: 'np.ndarray', Mp: 'np.ndarray', counts: 'np.ndarray', k: int,
                           Phi: 'np.ndarray') -> 'np.ndarray':
    import numpy as np
    counts = np.asarray(counts, dtype=int)
    if counts.size != 4:
        raise ValueError("counts must have four entries")
    if int(counts.sum()) != Kp.shape[0]:
        raise ValueError("counts do not sum to the system size")
    if k not in (0, 1, 2):
        raise ValueError("k must be 0, 1 or 2")
    Phi = np.asarray(Phi, dtype=float)
    if Phi.ndim != 2 or Phi.shape[0] != Kp.shape[0]:
        raise ValueError("Phi must have one row per equation of the system")
    o = np.concatenate([[0], np.cumsum(counts)])
    ii = slice(o[k], o[k+1])
    bb = slice(o[3], o[4])
    Kss = Kp[ii, ii]; Mss = Mp[ii, ii]; Ksb = Kp[ii, bb]; Msb = Mp[ii, bb]
    P = Phi[ii, :]
    lam = np.diag(P.T @ Kss @ P)
    if np.any(lam <= 0):
        raise ValueError("non-positive retained eigenvalue recovered from Phi")
    Psi = -np.linalg.solve(Kss, Ksb)
    Mc = Mss @ Psi + Msb
    F1 = np.linalg.inv(Kss) - P @ np.diag(1.0/lam) @ P.T
    R = F1 @ Mc
    nrm = np.linalg.norm(R, axis=0)
    good = nrm > 0
    R[:, good] = R[:, good]/nrm[good]
    out = np.zeros((Kp.shape[0], counts[3]))
    out[ii, :] = R
    return out

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    valid = """import numpy as np
def cand(k, nd):
    counts = np.array([24, 24, 48, 48])
    S = assemble_partitioned_system(6, 3, 1, 1.0, 0.6, 0.01, 210e9, 0.3, 7850.0)
    Kp, Mp = S[0], S[1]
    Phi = fixed_interface_modes(Kp, Mp, counts, k, nd)
    return residual_modes(Kp, Mp, counts, k, Phi)
def gold(k, nd):
    counts = np.array([24, 24, 48, 48])
    S = _oracle_assemble_partitioned_system(6, 3, 1, 1.0, 0.6, 0.01, 210e9, 0.3, 7850.0)
    Kp, Mp = S[0], S[1]
    Phi = _oracle_fixed_interface_modes(Kp, Mp, counts, k, nd)
    return _oracle_residual_modes(Kp, Mp, counts, k, Phi)
"""
    invalid = """import numpy as np
def run_model(rows, ncols):
    counts = np.array([24, 24, 48, 48])
    S = assemble_partitioned_system(6, 3, 1, 1.0, 0.6, 0.01, 210e9, 0.3, 7850.0)
    Phi = np.zeros((rows, ncols))
    try:
        residual_modes(S[0], S[1], counts, 0, Phi)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
def run_gold(rows, ncols):
    counts = np.array([24, 24, 48, 48])
    S = _oracle_assemble_partitioned_system(6, 3, 1, 1.0, 0.6, 0.01, 210e9, 0.3, 7850.0)
    Phi = np.zeros((rows, ncols))
    try:
        _oracle_residual_modes(S[0], S[1], counts, 0, Phi)
        return 0
    except ValueError:
        return 1
    except Exception:
        return 2
"""
    return [
        # --- normal: first substructure ---
        {
            "setup": valid,
            "call": "cand(0, 3)",
            "gold_call": "gold(0, 3)",
            "tol": 1e-7,
        },
        # --- boundary: middle substructure, no vanishing columns ---
        {
            "setup": valid,
            "call": "cand(1, 3)",
            "gold_call": "gold(1, 3)",
            "tol": 1e-7,
        },
        # --- edge: third substructure with a single retained mode ---
        {
            "setup": valid,
            "call": "cand(2, 1)",
            "gold_call": "gold(2, 1)",
            "tol": 1e-7,
        },
        # --- invalid: retained modes of the wrong height ---
        {
            "setup": invalid,
            "call": "run_model(10, 3)",
            "gold_call": "run_gold(10, 3)",
        },
        # --- invalid: null retained modes give a non-positive eigenvalue ---
        {
            "setup": invalid,
            "call": "run_model(144, 2)",
            "gold_call": "run_gold(144, 2)",
        },
    ]
