"""
Build the exponential-family state generated by a Hermitian reference logarithm and a vector of

real weights attached to the constraint observables, and return it together with the logarithm

of its normalisation.

Each weight enters the exponent with a minus sign: with L the reference logarithm, M_i the

constraint observables and w_i the weights, the state is

exp(L - sum_i w_i M_i) / tr exp(L - sum_i w_i M_i), and the returned normalisation is

log tr exp(L - sum_i w_i M_i).

The reference is supplied as the Hermitian logarithm of a positive-definite operator, and the

constraint observables are supplied as a stack whose ordering fixes the ordering of the weight

vector. The returned state is Hermitian, positive definite and normalised to unit trace. The

returned normalisation is a natural logarithm, so it is in nats.

Large weights can occur, so the exponential must be formed in a

way that does not overflow: only differences of the reference spectrum enter the state, and the

returned logarithm of the normalisation is recovered from the largest spectral value together

with the logarithm of the remaining sum.

Returns
-------
return state, log_partition
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def gibbs_state(log_reference: "np.ndarray", constraint_ops: "np.ndarray", weights: "np.ndarray") -> "tuple[np.ndarray, float]":
    '''Return the exponential-family state and the logarithm of its normalisation.

    Parameters
    ----------
    log_reference : np.ndarray
        Hermitian array of shape (d, d) holding the logarithm of the positive-definite
        reference operator. Hermiticity is required within 1e-9.
    constraint_ops : np.ndarray
        Complex array of shape (n, d, d) with n at least 0, holding Hermitian constraint
        observables. Hermiticity is required within 1e-9.
    weights : np.ndarray
        Real array of shape (n, ) with finite entries, holding one weight per observable in
        the order of constraint_ops.

    Returns
    -------
    state : np.ndarray
        Complex Hermitian positive-definite array of shape (d, d) with unit trace.
    log_partition : float
        Natural logarithm of the normalisation of the unnormalised exponential, in nats.

    Raises
    ------
    ValueError
        If log_reference is not a two-dimensional square array with at least one row and
        finite entries, if it is not Hermitian within 1e-9, if constraint_ops is not a
        three-dimensional array of finite (d, d) blocks matching log_reference, if any block
        is not Hermitian within 1e-9, or if weights is not a real finite array of shape (n, ).
    '''
    return state, log_partition

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _validate_exponential_family(log_reference: "np.ndarray", constraint_ops: "np.ndarray",
                                 weights: "np.ndarray") -> "tuple[np.ndarray, np.ndarray, np.ndarray]":
    """Return validated copies of the reference logarithm, observable stack and weights."""
    reference = np.asarray(log_reference, dtype=complex)
    if reference.ndim != 2 or reference.shape[0] != reference.shape[1] or reference.shape[0] < 1:
        raise ValueError("log_reference must be a square 2D array with at least one row")
    if not np.all(np.isfinite(reference)):
        raise ValueError("log_reference must have finite entries")
    if not np.allclose(reference, reference.conj().T, rtol=0.0, atol=1e-9):
        raise ValueError("log_reference must be Hermitian within 1e-9")
    dim = reference.shape[0]

    operators = np.asarray(constraint_ops, dtype=complex)
    if operators.ndim != 3 or operators.shape[1:] != (dim, dim):
        raise ValueError("constraint_ops must have shape (n, d, d) matching log_reference")
    if operators.size and not np.all(np.isfinite(operators)):
        raise ValueError("constraint_ops must have finite entries")
    for index in range(operators.shape[0]):
        block = operators[index]
        if not np.allclose(block, block.conj().T, rtol=0.0, atol=1e-9):
            raise ValueError("every constraint observable must be Hermitian within 1e-9")

    multipliers = np.asarray(weights)
    if np.iscomplexobj(multipliers):
        raise ValueError("weights must be real")
    multipliers = multipliers.astype(float)
    if multipliers.shape != (operators.shape[0], ):
        raise ValueError("weights must have shape (n, ) matching constraint_ops")
    if multipliers.size and not np.all(np.isfinite(multipliers)):
        raise ValueError("weights must have finite entries")

    return 0.5 * (reference + reference.conj().T), operators, multipliers


def _effective_hamiltonian(log_reference: "np.ndarray", constraint_ops: "np.ndarray",
                           weights: "np.ndarray") -> "np.ndarray":
    """Return the Hermitian generator of the exponential family."""
    shift = np.tensordot(weights, constraint_ops, axes=(0, 0)) if weights.size else 0.0
    generator = log_reference - shift
    return 0.5 * (generator + generator.conj().T)


def _oracle_gibbs_state(log_reference: "np.ndarray", constraint_ops: "np.ndarray", weights: "np.ndarray") -> "tuple[np.ndarray, float]":
    reference, operators, multipliers = _validate_exponential_family(
        log_reference, constraint_ops, weights)
    generator = _effective_hamiltonian(reference, operators, multipliers)
    spectrum, vectors = np.linalg.eigh(generator)
    peak = float(spectrum[-1])
    shifted = np.exp(spectrum - peak)
    total = float(shifted.sum())
    populations = shifted / total
    state = (vectors * populations) @ vectors.conj().T
    state = 0.5 * (state + state.conj().T)
    return state, peak + float(np.log(total))

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    header = "import numpy as np\n"

    instance = header + """
def local_instance(d_local, p_z, p_x):
    omega = np.exp(2j * np.pi / d_local)
    fourier = omega ** np.outer(np.arange(d_local), np.arange(d_local)) / np.sqrt(d_local)
    stack, values = [], []
    for basis_a, basis_b, table in ((np.eye(d_local, dtype=complex), np.eye(d_local, dtype=complex), p_z),
                                    (fourier, fourier.conj(), p_x)):
        for a in range(d_local):
            for b in range(d_local):
                if a == d_local - 1 and b == d_local - 1:
                    continue
                va = basis_a[:, a].reshape(-1, 1)
                vb = basis_b[:, b].reshape(-1, 1)
                stack.append(np.kron(va @ va.conj().T, vb @ vb.conj().T))
                values.append(table[a][b])
    return np.array(stack, dtype=complex), np.array(values, dtype=float)

p_z = [[0.297, 0.021, 0.014],
       [0.018, 0.284, 0.026],
       [0.011, 0.023, 0.306]]
p_x = [[0.281, 0.029, 0.019],
       [0.024, 0.292, 0.031],
       [0.017, 0.026, 0.281]]
operators, moments = local_instance(3, p_z, p_x)
log_reference = np.log(1.0 / 9.0) * np.eye(9, dtype=complex)
"""

    structure_probe = """
def structure_probe(fn, log_reference, operators, weights):
    state, log_partition = fn(log_reference, operators, weights)
    spectrum = np.linalg.eigvalsh(state)
    return np.array([float(np.trace(state).real), float(spectrum[0]), float(spectrum[-1]),
                     float(np.abs(state - state.conj().T).max()), float(log_partition)])
"""

    invalid = """
def probe(fn, args):
    try:
        fn(*args)
        return 0
    except ValueError:
        return 1
"""

    return [
        # --- Normal: maximally mixed reference with moderate weights on the qutrit instance ---
        {
            "setup": instance + """
weights = np.linspace(-1.5, 2.0, 16)
""",
            "call": "gibbs_state(log_reference.copy(), operators.copy(), weights.copy())",
            "gold_call": "_oracle_gibbs_state(log_reference, operators, weights)",
        },
        # --- Normal: structural invariants of the returned state and normalisation ---
        {
            "setup": instance + structure_probe + """
rng = np.random.default_rng(31)
weights = rng.normal(size=16) * 3.0
""",
            "call": "structure_probe(gibbs_state, log_reference.copy(), operators.copy(), weights.copy())",
            "gold_call": "structure_probe(_oracle_gibbs_state, log_reference, operators, weights)",
        },
        # --- Boundary: all weights zero, so the reference itself is reproduced ---
        {
            "setup": instance + """
weights = np.zeros(16)
""",
            "call": "gibbs_state(log_reference.copy(), operators.copy(), weights.copy())",
            "gold_call": "_oracle_gibbs_state(log_reference, operators, weights)",
        },
        # --- Boundary: empty observable stack, so only the reference enters ---
        {
            "setup": header + """
rng = np.random.default_rng(8)
root = rng.normal(size=(4, 4)) + 1j * rng.normal(size=(4, 4))
positive = root @ root.conj().T + 0.4 * np.eye(4)
spectrum, vectors = np.linalg.eigh(positive)
log_reference = (vectors * np.log(spectrum)) @ vectors.conj().T
operators = np.zeros((0, 4, 4), dtype=complex)
weights = np.zeros(0)
""",
            "call": "gibbs_state(log_reference.copy(), operators.copy(), weights.copy())",
            "gold_call": "_oracle_gibbs_state(log_reference, operators, weights)",
        },
        # --- Edge: large weights that overflow a direct exponential of the generator ---
        {
            "setup": instance + """
weights = np.zeros(16)
weights[0] = -420.0
weights[8] = 380.0
""",
            "call": "gibbs_state(log_reference.copy(), operators.copy(), weights.copy())",
            "gold_call": "_oracle_gibbs_state(log_reference, operators, weights)",
        },
        # --- Edge: strongly non-uniform reference with degenerate spectral blocks ---
        {
            "setup": header + """
diagonal = np.array([0.0, 0.0, -5.0, -5.0, -5.0, -12.0], dtype=float)
log_reference = np.diag(diagonal).astype(complex)
operators = np.zeros((2, 6, 6), dtype=complex)
operators[0, 0, 0] = 1.0
operators[0, 1, 1] = 1.0
operators[1, 2, 3] = 0.5
operators[1, 3, 2] = 0.5
weights = np.array([1.25, -0.75])
""",
            "call": "gibbs_state(log_reference.copy(), operators.copy(), weights.copy())",
            "gold_call": "_oracle_gibbs_state(log_reference, operators, weights)",
        },
        # --- Invalid: non-Hermitian constraint observable ---
        {
            "setup": header + invalid + """
log_reference = np.zeros((2, 2), dtype=complex)
operators = np.zeros((1, 2, 2), dtype=complex)
operators[0, 0, 1] = 1.0
weights = np.array([0.5])
""",
            "call": "probe(gibbs_state, (log_reference.copy(), operators.copy(), weights.copy()))",
            "gold_call": "probe(_oracle_gibbs_state, (log_reference, operators, weights))",
        },
        # --- Invalid: weight vector length inconsistent with the observable stack ---
        {
            "setup": header + invalid + """
log_reference = np.zeros((2, 2), dtype=complex)
operators = np.zeros((2, 2, 2), dtype=complex)
operators[0, 0, 0] = 1.0
operators[1, 1, 1] = 1.0
weights = np.array([0.5])
""",
            "call": "probe(gibbs_state, (log_reference.copy(), operators.copy(), weights.copy()))",
            "gold_call": "probe(_oracle_gibbs_state, (log_reference, operators, weights))",
        },
    ]
