"""
Advance the pipeline by one outer iteration: from the current bipartite state, produce the next

candidate state and the real weight vector that generates it. The exponential family of Steps 06 to 09 is generated by the reference logarithm of Step 04 evaluated at the current state.

The current state acts on the ordered bipartite space of Alice and Bob, with the basis label of

the pair (a, b) equal to a * d_local + b, and Alice's raw key is the symbol her detector reports.

The detector is supplied through its detector operators, indexed by that symbol in increasing

order. The constraint observables and the observed moment vector share one ordering, which is

also the ordering of the returned weight vector.



The returned state is Hermitian, positive definite, of unit trace, and it reproduces the observed

moments to within the accuracy the inner search reaches, so it is admissible data for the next

iteration whatever the current state was. The inner search starts from the all-zero weight

vector, stops once every entry of its objective gradient is below tol in magnitude, and takes at

most max_iter steps.

Returns
-------
return next_state, weights
"""

# =============================================================================
# FUNCTION SIGNATURE (shown to the LLM)
# =============================================================================

def outer_iteration(rho: "np.ndarray", constraint_ops: "np.ndarray", moments: "np.ndarray", detector_ops: "np.ndarray", tol: float, max_iter: int) -> "tuple[np.ndarray, np.ndarray]":
    '''Return the next candidate state and the weight vector that generates it.

    Parameters
    ----------
    rho : np.ndarray
        Hermitian positive-definite array of shape (d, d) with unit trace, acting on the
        ordered bipartite space, with smallest eigenvalue above 1e-12.
    constraint_ops : np.ndarray
        Complex array of shape (n, d, d) with n at least 0, holding Hermitian constraint
        observables matching the dimension of rho.
    moments : np.ndarray
        Real array of shape (n, ) with finite entries, holding the observed value of each
        observable in the order of constraint_ops.
    detector_ops : np.ndarray
        Complex array of shape (m, d, d) with m at least 1, holding the detector operators
        indexed by Alice's key symbol. Every operator the detector conditions from rho must
        have smallest eigenvalue above 1e-12.
    tol : float
        Positive stopping threshold used by the inner search.
    max_iter : int
        Nonnegative step budget for the inner search.

    Returns
    -------
    next_state : np.ndarray
        Complex Hermitian positive-definite array of shape (d, d) with unit trace.
    weights : np.ndarray
        Real array of shape (n, ) holding the weight vector that generates next_state.

    Raises
    ------
    ValueError
        If rho fails the requirements above, if constraint_ops is not a three-dimensional array
        of finite Hermitian blocks matching rho, if moments is not a real finite array of shape
        (n, ), if detector_ops fails the requirements above, if tol is not a positive finite
        real scalar, or if max_iter is not a nonnegative integer.
    '''
    return next_state, weights

# =============================================================================
# GOLD SOLUTION
# =============================================================================

import numpy as np


def _oracle_outer_iteration(rho: "np.ndarray", constraint_ops: "np.ndarray", moments: "np.ndarray", detector_ops: "np.ndarray", tol: float, max_iter: int) -> "tuple[np.ndarray, np.ndarray]":
    state = _validate_density_operator(rho)
    if float(np.linalg.eigvalsh(state)[0]) <= 1e-12:
        raise ValueError("rho must have smallest eigenvalue above 1e-12")

    reference = _oracle_moving_reference_logarithm(state, detector_ops)
    count = np.shape(constraint_ops)[0] if np.ndim(constraint_ops) == 3 else 0
    _, operators, _ = _validate_exponential_family(reference, constraint_ops, np.zeros(count))
    start = np.zeros(operators.shape[0], dtype=float)

    weights, _ = _oracle_solve_multipliers(reference, operators, moments, start, tol, max_iter)
    next_state, _ = _oracle_gibbs_state(reference, operators, weights)
    return next_state, weights

# =============================================================================
# TEST CASES
# =============================================================================

def test_cases():
    """Return list of test case specifications."""
    header = "import numpy as np\n"
    shared = """
def local_instance(d_local, p_z, p_x):
    omega = np.exp(2j * np.pi / d_local)
    fourier = omega ** np.outer(np.arange(d_local), np.arange(d_local)) / np.sqrt(d_local)
    stack, values = [], []
    for basis_a, basis_b, table in ((np.eye(d_local, dtype=complex), np.eye(d_local, dtype=complex), p_z),
                                    (fourier, fourier.conj(), p_x)):
        for a in range(d_local):
            for b in range(d_local):
                if a == d_local - 1 and b == d_local - 1:
                    continue
                va = basis_a[:, a].reshape(-1, 1)
                vb = basis_b[:, b].reshape(-1, 1)
                stack.append(np.kron(va @ va.conj().T, vb @ vb.conj().T))
                values.append(table[a][b])
    return np.array(stack, dtype=complex), np.array(values, dtype=float)

def local_detector(d_local, d_bob, epsilon):
    out = []
    for a in range(d_local):
        element = (epsilon / d_local) * np.eye(d_local, dtype=complex)
        element[a, a] += 1.0 - epsilon
        w, V = np.linalg.eigh(element)
        root = (V * np.sqrt(np.clip(w, 0.0, None))) @ V.conj().T
        out.append(np.kron(root, np.eye(d_bob, dtype=complex)))
    return np.array(out, dtype=complex)

p_z = [[0.297, 0.021, 0.014],
       [0.018, 0.284, 0.026],
       [0.011, 0.023, 0.306]]
p_x = [[0.281, 0.029, 0.019],
       [0.024, 0.292, 0.031],
       [0.017, 0.026, 0.281]]
"""
    instance = header + shared + """
operators, moments = local_instance(3, p_z, p_x)
detector_ops = local_detector(3, 3, 0.04)
rho = np.eye(9, dtype=complex) / 9.0
"""
    feasibility_probe = """
def feasibility_probe(fn, rho, operators, moments, detector_ops, tol, max_iter):
    next_state, weights = fn(rho, operators, moments, detector_ops, tol, max_iter)
    achieved = np.einsum('iab,ba->i', operators, next_state).real
    spectrum = np.linalg.eigvalsh(next_state)
    return np.array([float(np.abs(achieved - moments).max()),
                     float(np.trace(next_state).real), float(spectrum[0]),
                     float(np.abs(next_state - next_state.conj().T).max())])
"""
    invalid = """
def probe(fn, args):
    try:
        fn(*args)
        return 0
    except ValueError:
        return 1
"""
    return [
        # --- Normal: first iteration of the benchmark pipeline from the maximally mixed state ---
        {
            "setup": instance,
            "call": "outer_iteration(rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 100)",
            "gold_call": "_oracle_outer_iteration(rho, operators, moments, detector_ops, 1e-12, 100)",
            "tol": 1e-7,
        },
        # --- Normal: the returned state matches the observed moments and stays positive ---
        {
            "setup": instance + feasibility_probe,
            "call": "feasibility_probe(outer_iteration, rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 100)",
            "gold_call": "feasibility_probe(_oracle_outer_iteration, rho, operators, moments, detector_ops, 1e-12, 100)",
            "tol": 1e-8,
        },
        # --- Normal: a Gibbs-like linearisation state such as later iterations supply ---
        {
            "setup": instance + """
weights = np.linspace(-1.2, 2.4, 16)
generator = -np.tensordot(weights, operators, axes=(0, 0))
generator = 0.5 * (generator + generator.conj().T)
spectrum, vectors = np.linalg.eigh(generator)
populations = np.exp(spectrum - spectrum.max())
populations = populations / populations.sum()
rho = (vectors * populations) @ vectors.conj().T
rho = 0.5 * (rho + rho.conj().T)
""",
            "call": "outer_iteration(rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 100)",
            "gold_call": "_oracle_outer_iteration(rho, operators, moments, detector_ops, 1e-12, 100)",
            "tol": 1e-7,
        },
        # --- Boundary: fully randomising detector, where the reference carries no key structure ---
        {
            "setup": instance + """
detector_ops = local_detector(3, 3, 1.0)
""",
            "call": "outer_iteration(rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 200)",
            "gold_call": "_oracle_outer_iteration(rho, operators, moments, detector_ops, 1e-12, 200)",
            "tol": 1e-7,
        },
        # --- Boundary: empty observable stack, where the reference itself is returned ---
        {
            "setup": header + shared + """
rng = np.random.default_rng(13)
root = rng.normal(size=(4, 4)) + 1j * rng.normal(size=(4, 4))
rho = root @ root.conj().T + 0.6 * np.eye(4)
rho = rho / np.trace(rho).real
operators = np.zeros((0, 4, 4), dtype=complex)
moments = np.zeros(0)
detector_ops = local_detector(2, 2, 0.07)
""",
            "call": "outer_iteration(rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 50)",
            "gold_call": "_oracle_outer_iteration(rho, operators, moments, detector_ops, 1e-12, 50)",
        },
        # --- Edge: qubit-qubit instance with a single strongly correlated observable ---
        {
            "setup": header + shared + """
rho = np.eye(4, dtype=complex) / 4.0
vec = np.array([1.0, 0.0, 0.0, 1.0], dtype=complex) / np.sqrt(2.0)
operators = np.zeros((1, 4, 4), dtype=complex)
operators[0] = np.outer(vec, vec.conj())
moments = np.array([0.94])
detector_ops = local_detector(2, 2, 0.02)
""",
            "call": "outer_iteration(rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-13, 200)",
            "gold_call": "_oracle_outer_iteration(rho, operators, moments, detector_ops, 1e-13, 200)",
            "tol": 1e-8,
        },
        # --- Edge: starting state close to the boundary of positivity ---
        {
            "setup": instance + """
vec = np.zeros(9, dtype=complex)
for k in range(3):
    vec[3 * k + k] = 1.0 / np.sqrt(3.0)
rho = 0.99 * np.outer(vec, vec.conj()) + 0.01 * np.eye(9, dtype=complex) / 9.0
""",
            "call": "outer_iteration(rho.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 200)",
            "gold_call": "_oracle_outer_iteration(rho, operators, moments, detector_ops, 1e-12, 200)",
            "tol": 1e-7,
        },
        # --- Invalid: singular starting state ---
        {
            "setup": instance + invalid + """
vec = np.zeros(9, dtype=complex)
for k in range(3):
    vec[3 * k + k] = 1.0 / np.sqrt(3.0)
singular = np.outer(vec, vec.conj())
""",
            "call": "probe(outer_iteration, (singular.copy(), operators.copy(), moments.copy(), detector_ops.copy(), 1e-12, 100))",
            "gold_call": "probe(_oracle_outer_iteration, (singular, operators, moments, detector_ops, 1e-12, 100))",
        },
        # --- Invalid: projective detector, whose conditioned blocks are rank deficient ---
        {
            "setup": instance + invalid + """
projective = local_detector(3, 3, 0.0)
""",
            "call": "probe(outer_iteration, (rho.copy(), operators.copy(), moments.copy(), projective.copy(), 1e-12, 100))",
            "gold_call": "probe(_oracle_outer_iteration, (rho, operators, moments, projective, 1e-12, 100))",
        },
    ]
